package recipes_test

import (
	"fmt"
	"strings"

	"github.com/mind-vm/sqlb/migrate"
	"github.com/mind-vm/sqlb/schema"
)

// Diff returns migration changes as values. Nothing runs: your runner applies
// them, or a person reads them first, which is the difference between a
// migration tool and a generator of migrations.
//
// The first migration is a diff against nothing.
func Example_migrateFirstMigration() {
	target := schema.NewRegistry()
	target.Table("orgs",
		schema.UUIDv7("id").PrimaryKey(),
		schema.Text("name").Sortable(),
		schema.Timestamps(),
	)

	changes, err := migrate.Diff(schema.NewRegistry(), target, migrate.MinPostgres(18))
	if err != nil {
		panic(err)
	}
	for _, c := range changes {
		fmt.Println(c.Up)
	}
	// Output:
	// CREATE TABLE "orgs" (
	//     "id" uuid NOT NULL DEFAULT uuidv7(),
	//     "name" text NOT NULL,
	//     "created_at" timestamptz NOT NULL DEFAULT now(),
	//     "updated_at" timestamptz NOT NULL DEFAULT now(),
	//     CONSTRAINT "orgs_pkey" PRIMARY KEY ("id")
	// );
}

// Every later migration is the same call with a different left-hand side: what
// the database has now, against what the schema declares. `sqlb migrate` gets
// "now" by replaying the checked-in history into a shadow database; introspect
// gets it from a live one.
func Example_migrateAddingAColumn() {
	current := schema.NewRegistry()
	current.Table("posts",
		schema.UUIDv7("id").PrimaryKey(),
		schema.Text("title"),
	)

	target := schema.NewRegistry()
	target.Table("posts",
		schema.UUIDv7("id").PrimaryKey(),
		schema.Text("title"),
		schema.Text("slug").Unique().Filterable(),
	).Index("slug")

	changes, err := migrate.Diff(current, target)
	if err != nil {
		panic(err)
	}
	for _, c := range changes {
		fmt.Println(c.Up)
	}
	// Output:
	// ALTER TABLE "posts" ADD COLUMN "slug" text NOT NULL;
	// ALTER TABLE "posts" ADD CONSTRAINT "posts_slug_key" UNIQUE ("slug");
	// CREATE INDEX CONCURRENTLY "posts_slug_idx" ON "posts" ("slug");
}

// A change that can lose data is marked, carries the reason, and renders
// commented out unless the caller passes AllowDestructive. Dropping a column
// should be a deliberate act with a flag attached, not something that happens
// because a generator decided it.
func Example_migrateDestructiveChangeIsCommentedOut() {
	current := schema.NewRegistry()
	current.Table("posts",
		schema.UUIDv7("id").PrimaryKey(),
		schema.Text("title"),
		schema.Text("subtitle"),
	)

	target := schema.NewRegistry()
	target.Table("posts",
		schema.UUIDv7("id").PrimaryKey(),
		schema.Text("title"),
	)

	changes, err := migrate.Diff(current, target)
	if err != nil {
		panic(err)
	}
	for _, c := range changes {
		fmt.Printf("destructive=%v %s\n  reason: %s\n", c.Destructive, c.Up, c.Reason)
	}

	files, err := migrate.Render(
		migrate.Migration{Version: "00002", Name: "drops_subtitle", Changes: changes},
		migrate.Options{Format: migrate.Goose},
	)
	if err != nil {
		panic(err)
	}
	for name, body := range files {
		fmt.Println("--", name)
		fmt.Println(strings.TrimSpace(body))
	}
	// Output:
	// destructive=true ALTER TABLE "posts" DROP COLUMN "subtitle";
	//   reason: dropping posts.subtitle deletes its contents. The Down restores the column but not the values
	// -- 00002_drops_subtitle.sql
	// -- Generated by sqlb. Review before applying.
	//
	// -- +goose Up
	// -- drop column posts.subtitle
	// -- DESTRUCTIVE: dropping posts.subtitle deletes its contents. The Down
	// --   restores the column but not the values
	// -- Review, then uncomment to apply. Generated commented out on purpose.
	// -- ALTER TABLE "posts" DROP COLUMN "subtitle";
	//
	// -- +goose Down
	// -- DESTRUCTIVE: dropping posts.subtitle deletes its contents. The Down
	// --   restores the column but not the values
	// -- Review, then uncomment to apply. Generated commented out on purpose.
	// -- ALTER TABLE "posts" ADD COLUMN "subtitle" text NOT NULL;
}

// A CREATE INDEX comes out CONCURRENTLY, and migrate.Split gives it a file of
// its own — transaction control in goose and golang-migrate is per file, so a
// statement that cannot run inside a transaction cannot share one with
// statements that should.
//
// Blocking is the hook for a policy this package cannot have: whether a full
// table scan is acceptable depends on how many rows the table holds, which is
// not in the schema. A project that knows its big tables can refuse a migration
// touching one, or route it to whoever sequences an expand/contract rollout.
func Example_migrateReportsBlockingChanges() {
	current := schema.NewRegistry()
	current.Table("posts",
		schema.UUIDv7("id").PrimaryKey(),
		schema.Text("title"),
	)

	target := schema.NewRegistry()
	target.Table("posts",
		schema.UUIDv7("id").PrimaryKey(),
		schema.Text("title"),
		schema.BigInt("view_count").Default(schema.Value(0)),
	).Index("view_count")

	changes, err := migrate.Diff(current, target)
	if err != nil {
		panic(err)
	}
	m := migrate.Migration{Version: "00002", Name: "adds_view_count", Changes: changes}

	fmt.Println("destructive:", m.Destructive())
	for _, c := range m.Blocking() {
		fmt.Println("blocking:", c.Up)
	}
	// Output:
	// destructive: false
}
