// Code generated by github.com/mind-vm/sqlb. DO NOT EDIT.

package blog

import (
	"encoding/json"
	"errors"
	"time"

	"github.com/danielgtaylor/huma/v2"
	"github.com/mind-vm/sqlb"
	"github.com/mind-vm/sqlb/rest"
)

// AuthorCreate is the request body for creating a Author.
//
// Read-only columns are absent: the database or a BeforeCreate hook owns them.
// A column with a default is optional, so leaving it out means the database
// supplies the value rather than the zero value overwriting it.
type AuthorCreate struct {
	OrgID string `json:"org_id"`
	Email string `json:"email"`
	Name  string `json:"name"`
}

// Row builds the row to insert. It satisfies rest.CreateBody.
func (c AuthorCreate) Row() (*Author, error) {
	row := &Author{}
	row.OrgID = c.OrgID
	row.Email = c.Email
	row.Name = c.Name
	return row, nil
}

// AuthorPatch is the request body for patching a Author.
//
// Every field is a pointer and every field is optional, so a request writes
// only the columns it names. Immutable columns are absent: they are settable
// once, at create.
type AuthorPatch struct {
	OrgID *string `json:"org_id,omitempty"`
	Email *string `json:"email,omitempty"`
	Name  *string `json:"name,omitempty"`

	// present records which properties the request body actually carried.
	present map[string]bool
}

// UnmarshalJSON decodes the body and remembers which properties were present.
//
// Without this a nil pointer would be ambiguous: `{}` and `{"org_id": null}` decode
// identically, but the first must change nothing and the second must write NULL.
func (u *AuthorPatch) UnmarshalJSON(data []byte) error {
	type plain AuthorPatch
	if err := json.Unmarshal(data, (*plain)(u)); err != nil {
		return err
	}
	var keys map[string]json.RawMessage
	if err := json.Unmarshal(data, &keys); err != nil {
		return err
	}
	u.present = make(map[string]bool, len(keys))
	for k := range keys {
		u.present[k] = true
	}
	return nil
}

// Changes reports the columns the request named. It satisfies rest.UpdateBody.
func (u AuthorPatch) Changes() (map[string]any, error) {
	out := make(map[string]any, len(u.present))
	if u.present["org_id"] {
		if u.OrgID == nil {
			return nil, errors.New("org_id is not nullable and cannot be set to null")
		}
		out["org_id"] = *u.OrgID
	}
	if u.present["email"] {
		if u.Email == nil {
			return nil, errors.New("email is not nullable and cannot be set to null")
		}
		out["email"] = *u.Email
	}
	if u.present["name"] {
		if u.Name == nil {
			return nil, errors.New("name is not nullable and cannot be set to null")
		}
		out["name"] = *u.Name
	}
	return out, nil
}

// PostCreate is the request body for creating a Post.
//
// Read-only columns are absent: the database or a BeforeCreate hook owns them.
// A column with a default is optional, so leaving it out means the database
// supplies the value rather than the zero value overwriting it.
type PostCreate struct {
	OrgID       string      `json:"org_id"`
	AuthorID    string      `json:"author_id"`
	Title       string      `json:"title"`
	Body        string      `json:"body"`
	Status      *PostStatus `json:"status,omitempty" enum:"draft,review,published"`
	PublishedAt *time.Time  `json:"published_at,omitempty"`
}

// Row builds the row to insert. It satisfies rest.CreateBody.
func (c PostCreate) Row() (*Post, error) {
	row := &Post{}
	row.OrgID = c.OrgID
	row.AuthorID = c.AuthorID
	row.Title = c.Title
	row.Body = c.Body
	if c.Status != nil {
		row.Status = *c.Status
	}
	row.PublishedAt = c.PublishedAt
	return row, nil
}

// Explicit names the columns this request carried, so that a sent zero value
// is written rather than being read as "absent, use the default". It satisfies
// rest.CreateExplicit.
func (c PostCreate) Explicit() []string {
	var cols []string
	if c.Status != nil {
		cols = append(cols, "status")
	}
	return cols
}

// PostPatch is the request body for patching a Post.
//
// Every field is a pointer and every field is optional, so a request writes
// only the columns it names. Immutable columns are absent: they are settable
// once, at create.
type PostPatch struct {
	OrgID       *string     `json:"org_id,omitempty"`
	AuthorID    *string     `json:"author_id,omitempty"`
	Title       *string     `json:"title,omitempty"`
	Body        *string     `json:"body,omitempty"`
	Status      *PostStatus `json:"status,omitempty" enum:"draft,review,published"`
	PublishedAt *time.Time  `json:"published_at,omitempty"`

	// present records which properties the request body actually carried.
	present map[string]bool
}

// UnmarshalJSON decodes the body and remembers which properties were present.
//
// Without this a nil pointer would be ambiguous: `{}` and `{"org_id": null}` decode
// identically, but the first must change nothing and the second must write NULL.
func (u *PostPatch) UnmarshalJSON(data []byte) error {
	type plain PostPatch
	if err := json.Unmarshal(data, (*plain)(u)); err != nil {
		return err
	}
	var keys map[string]json.RawMessage
	if err := json.Unmarshal(data, &keys); err != nil {
		return err
	}
	u.present = make(map[string]bool, len(keys))
	for k := range keys {
		u.present[k] = true
	}
	return nil
}

// Changes reports the columns the request named. It satisfies rest.UpdateBody.
func (u PostPatch) Changes() (map[string]any, error) {
	out := make(map[string]any, len(u.present))
	if u.present["org_id"] {
		if u.OrgID == nil {
			return nil, errors.New("org_id is not nullable and cannot be set to null")
		}
		out["org_id"] = *u.OrgID
	}
	if u.present["author_id"] {
		if u.AuthorID == nil {
			return nil, errors.New("author_id is not nullable and cannot be set to null")
		}
		out["author_id"] = *u.AuthorID
	}
	if u.present["title"] {
		if u.Title == nil {
			return nil, errors.New("title is not nullable and cannot be set to null")
		}
		out["title"] = *u.Title
	}
	if u.present["body"] {
		if u.Body == nil {
			return nil, errors.New("body is not nullable and cannot be set to null")
		}
		out["body"] = *u.Body
	}
	if u.present["status"] {
		if u.Status == nil {
			return nil, errors.New("status is not nullable and cannot be set to null")
		}
		out["status"] = *u.Status
	}
	if u.present["published_at"] {
		out["published_at"] = u.PublishedAt
	}
	return out, nil
}

// Register mounts every exposed resource on api.
//
// The handlers are rest.Resource, instantiated per model. Registration is
// generic rather than reflective because query hooks are keyed by type: a
// BeforeQuery hook registered on a model applies to its REST reads too, which
// is how tenant scoping stops being something each handler must remember.
func Register(api huma.API, db sqlb.Executor) error {
	if err := rest.Resource[Author, AuthorCreate, AuthorPatch](api, db, rest.Options{
		Path:            "/authors",
		Name:            "author",
		Tag:             "authors",
		Ops:             rest.OpCreate | rest.OpRead | rest.OpUpdate | rest.OpDelete | rest.OpList,
		DefaultPageSize: 25,
		MaxPageSize:     100,
		Expandable:      []string{"org", "posts"},
	}); err != nil {
		return err
	}
	if err := rest.Resource[Org, rest.None[Org], rest.None[Org]](api, db, rest.Options{
		Path:        "/orgs",
		Name:        "org",
		Tag:         "orgs",
		Ops:         rest.OpRead | rest.OpList,
		Description: "A tenant. Every other table is scoped to one.",
		Expandable:  []string{"authors"},
	}); err != nil {
		return err
	}
	if err := rest.Resource[Post, PostCreate, PostPatch](api, db, rest.Options{
		Path:            "/posts",
		Name:            "post",
		Tag:             "posts",
		Ops:             rest.OpCreate | rest.OpRead | rest.OpUpdate | rest.OpList,
		Description:     "A blog post.",
		DefaultPageSize: 20,
		MaxPageSize:     100,
		MaxFilters:      12,
		MaxSortTerms:    4,
		MaxOffset:       5000,
		DefaultSort:     []string{"-created_at"},
		Expandable:      []string{"author"},
	}); err != nil {
		return err
	}
	return nil
}
