// Code generated by github.com/mind-vm/sqlb. DO NOT EDIT.

package evolve

import (
	"time"

	"github.com/mind-vm/sqlb"
)

type customerColumns struct {
	ID           sqlb.Col[string]
	EmailAddress sqlb.TextCol[string]
	Name         sqlb.TextCol[string]
	CreatedAt    sqlb.Col[time.Time]
	UpdatedAt    sqlb.Col[time.Time]
}

// CustomerCols are the typed columns of customers.
var CustomerCols = customerColumns{
	ID:           sqlb.Typed[string]("id"),
	EmailAddress: sqlb.TextColumn[string]("email_address"),
	Name:         sqlb.TextColumn[string]("name"),
	CreatedAt:    sqlb.Typed[time.Time]("created_at"),
	UpdatedAt:    sqlb.Typed[time.Time]("updated_at"),
}

// CustomerUpdate is a typed update statement for customers.
type CustomerUpdate struct {
	stmt *sqlb.Update[Customer]
}

// UpdateCustomer starts a typed update.
func UpdateCustomer() *CustomerUpdate {
	return &CustomerUpdate{stmt: sqlb.UpdateRows[Customer]()}
}

// SetEmailAddress sets email_address.
func (u *CustomerUpdate) SetEmailAddress(v string) *CustomerUpdate {
	u.stmt.Set("email_address", v)
	return u
}

// SetName sets name.
func (u *CustomerUpdate) SetName(v string) *CustomerUpdate {
	u.stmt.Set("name", v)
	return u
}

// SetCreatedAt sets created_at.
func (u *CustomerUpdate) SetCreatedAt(v time.Time) *CustomerUpdate {
	u.stmt.Set("created_at", v)
	return u
}

// SetUpdatedAt sets updated_at.
func (u *CustomerUpdate) SetUpdatedAt(v time.Time) *CustomerUpdate {
	u.stmt.Set("updated_at", v)
	return u
}

// Where narrows the affected rows.
func (u *CustomerUpdate) Where(preds ...sqlb.Pred) *CustomerUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *CustomerUpdate) Stmt() *sqlb.Update[Customer] { return u.stmt }

type supportAgentColumns struct {
	ID        sqlb.Col[string]
	Email     sqlb.TextCol[string]
	Name      sqlb.TextCol[string]
	Active    sqlb.Col[bool]
	CreatedAt sqlb.Col[time.Time]
	UpdatedAt sqlb.Col[time.Time]
}

// SupportAgentCols are the typed columns of support_agents.
var SupportAgentCols = supportAgentColumns{
	ID:        sqlb.Typed[string]("id"),
	Email:     sqlb.TextColumn[string]("email"),
	Name:      sqlb.TextColumn[string]("name"),
	Active:    sqlb.Typed[bool]("active"),
	CreatedAt: sqlb.Typed[time.Time]("created_at"),
	UpdatedAt: sqlb.Typed[time.Time]("updated_at"),
}

// SupportAgentUpdate is a typed update statement for support_agents.
type SupportAgentUpdate struct {
	stmt *sqlb.Update[SupportAgent]
}

// UpdateSupportAgent starts a typed update.
func UpdateSupportAgent() *SupportAgentUpdate {
	return &SupportAgentUpdate{stmt: sqlb.UpdateRows[SupportAgent]()}
}

// SetEmail sets email.
func (u *SupportAgentUpdate) SetEmail(v string) *SupportAgentUpdate {
	u.stmt.Set("email", v)
	return u
}

// SetName sets name.
func (u *SupportAgentUpdate) SetName(v string) *SupportAgentUpdate {
	u.stmt.Set("name", v)
	return u
}

// SetActive sets active.
func (u *SupportAgentUpdate) SetActive(v bool) *SupportAgentUpdate {
	u.stmt.Set("active", v)
	return u
}

// SetCreatedAt sets created_at.
func (u *SupportAgentUpdate) SetCreatedAt(v time.Time) *SupportAgentUpdate {
	u.stmt.Set("created_at", v)
	return u
}

// SetUpdatedAt sets updated_at.
func (u *SupportAgentUpdate) SetUpdatedAt(v time.Time) *SupportAgentUpdate {
	u.stmt.Set("updated_at", v)
	return u
}

// Where narrows the affected rows.
func (u *SupportAgentUpdate) Where(preds ...sqlb.Pred) *SupportAgentUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *SupportAgentUpdate) Stmt() *sqlb.Update[SupportAgent] { return u.stmt }

type ticketColumns struct {
	ID         sqlb.Col[string]
	CustomerID sqlb.Col[string]
	Subject    sqlb.TextCol[string]
	Body       sqlb.TextCol[string]
	Status     sqlb.Col[TicketStatus]
	Priority   sqlb.Col[TicketPriority]
	CreatedAt  sqlb.Col[time.Time]
	UpdatedAt  sqlb.Col[time.Time]
}

// TicketCols are the typed columns of tickets.
var TicketCols = ticketColumns{
	ID:         sqlb.Typed[string]("id"),
	CustomerID: sqlb.Typed[string]("customer_id"),
	Subject:    sqlb.TextColumn[string]("subject"),
	Body:       sqlb.TextColumn[string]("body"),
	Status:     sqlb.Typed[TicketStatus]("status"),
	Priority:   sqlb.Typed[TicketPriority]("priority"),
	CreatedAt:  sqlb.Typed[time.Time]("created_at"),
	UpdatedAt:  sqlb.Typed[time.Time]("updated_at"),
}

// TicketUpdate is a typed update statement for tickets.
type TicketUpdate struct {
	stmt *sqlb.Update[Ticket]
}

// UpdateTicket starts a typed update.
func UpdateTicket() *TicketUpdate {
	return &TicketUpdate{stmt: sqlb.UpdateRows[Ticket]()}
}

// SetCustomerID sets customer_id.
func (u *TicketUpdate) SetCustomerID(v string) *TicketUpdate {
	u.stmt.Set("customer_id", v)
	return u
}

// SetSubject sets subject.
func (u *TicketUpdate) SetSubject(v string) *TicketUpdate {
	u.stmt.Set("subject", v)
	return u
}

// SetBody sets body.
func (u *TicketUpdate) SetBody(v string) *TicketUpdate {
	u.stmt.Set("body", v)
	return u
}

// SetStatus sets status.
func (u *TicketUpdate) SetStatus(v TicketStatus) *TicketUpdate {
	u.stmt.Set("status", v)
	return u
}

// SetPriority sets priority.
func (u *TicketUpdate) SetPriority(v TicketPriority) *TicketUpdate {
	u.stmt.Set("priority", v)
	return u
}

// SetCreatedAt sets created_at.
func (u *TicketUpdate) SetCreatedAt(v time.Time) *TicketUpdate {
	u.stmt.Set("created_at", v)
	return u
}

// SetUpdatedAt sets updated_at.
func (u *TicketUpdate) SetUpdatedAt(v time.Time) *TicketUpdate {
	u.stmt.Set("updated_at", v)
	return u
}

// Where narrows the affected rows.
func (u *TicketUpdate) Where(preds ...sqlb.Pred) *TicketUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *TicketUpdate) Stmt() *sqlb.Update[Ticket] { return u.stmt }
