// Code generated by github.com/mind-vm/sqlb. DO NOT EDIT.

package evolve

import (
	"encoding/json"
	"errors"

	"github.com/danielgtaylor/huma/v2"
	"github.com/mind-vm/sqlb"
	"github.com/mind-vm/sqlb/rest"
)

// CustomerCreate is the request body for creating a Customer.
//
// Read-only columns are absent: the database or a BeforeCreate hook owns them.
// A column with a default is optional, so leaving it out means the database
// supplies the value rather than the zero value overwriting it.
type CustomerCreate struct {
	EmailAddress string `json:"email_address"`
	Name         string `json:"name"`
}

// Row builds the row to insert. It satisfies rest.CreateBody.
func (c CustomerCreate) Row() (*Customer, error) {
	row := &Customer{}
	row.EmailAddress = c.EmailAddress
	row.Name = c.Name
	return row, nil
}

// CustomerPatch is the request body for patching a Customer.
//
// Every field is a pointer and every field is optional, so a request writes
// only the columns it names. Immutable columns are absent: they are settable
// once, at create.
type CustomerPatch struct {
	EmailAddress *string `json:"email_address,omitempty"`
	Name         *string `json:"name,omitempty"`

	// present records which properties the request body actually carried.
	present map[string]bool
}

// UnmarshalJSON decodes the body and remembers which properties were present.
//
// Without this a nil pointer would be ambiguous: `{}` and `{"email_address": null}` decode
// identically, but the first must change nothing and the second must write NULL.
func (u *CustomerPatch) UnmarshalJSON(data []byte) error {
	type plain CustomerPatch
	if err := json.Unmarshal(data, (*plain)(u)); err != nil {
		return err
	}
	var keys map[string]json.RawMessage
	if err := json.Unmarshal(data, &keys); err != nil {
		return err
	}
	u.present = make(map[string]bool, len(keys))
	for k := range keys {
		u.present[k] = true
	}
	return nil
}

// Changes reports the columns the request named. It satisfies rest.UpdateBody.
func (u CustomerPatch) Changes() (map[string]any, error) {
	out := make(map[string]any, len(u.present))
	if u.present["email_address"] {
		if u.EmailAddress == nil {
			return nil, errors.New("email_address is not nullable and cannot be set to null")
		}
		out["email_address"] = *u.EmailAddress
	}
	if u.present["name"] {
		if u.Name == nil {
			return nil, errors.New("name is not nullable and cannot be set to null")
		}
		out["name"] = *u.Name
	}
	return out, nil
}

// TicketCreate is the request body for creating a Ticket.
//
// Read-only columns are absent: the database or a BeforeCreate hook owns them.
// A column with a default is optional, so leaving it out means the database
// supplies the value rather than the zero value overwriting it.
type TicketCreate struct {
	CustomerID string          `json:"customer_id"`
	Subject    string          `json:"subject"`
	Body       string          `json:"body"`
	Status     *TicketStatus   `json:"status,omitempty" enum:"open,pending,closed"`
	Priority   *TicketPriority `json:"priority,omitempty" enum:"low,normal,high,urgent"`
}

// Row builds the row to insert. It satisfies rest.CreateBody.
func (c TicketCreate) Row() (*Ticket, error) {
	row := &Ticket{}
	row.CustomerID = c.CustomerID
	row.Subject = c.Subject
	row.Body = c.Body
	if c.Status != nil {
		row.Status = *c.Status
	}
	if c.Priority != nil {
		row.Priority = *c.Priority
	}
	return row, nil
}

// TicketPatch is the request body for patching a Ticket.
//
// Every field is a pointer and every field is optional, so a request writes
// only the columns it names. Immutable columns are absent: they are settable
// once, at create.
type TicketPatch struct {
	CustomerID *string         `json:"customer_id,omitempty"`
	Subject    *string         `json:"subject,omitempty"`
	Body       *string         `json:"body,omitempty"`
	Status     *TicketStatus   `json:"status,omitempty" enum:"open,pending,closed"`
	Priority   *TicketPriority `json:"priority,omitempty" enum:"low,normal,high,urgent"`

	// present records which properties the request body actually carried.
	present map[string]bool
}

// UnmarshalJSON decodes the body and remembers which properties were present.
//
// Without this a nil pointer would be ambiguous: `{}` and `{"customer_id": null}` decode
// identically, but the first must change nothing and the second must write NULL.
func (u *TicketPatch) UnmarshalJSON(data []byte) error {
	type plain TicketPatch
	if err := json.Unmarshal(data, (*plain)(u)); err != nil {
		return err
	}
	var keys map[string]json.RawMessage
	if err := json.Unmarshal(data, &keys); err != nil {
		return err
	}
	u.present = make(map[string]bool, len(keys))
	for k := range keys {
		u.present[k] = true
	}
	return nil
}

// Changes reports the columns the request named. It satisfies rest.UpdateBody.
func (u TicketPatch) Changes() (map[string]any, error) {
	out := make(map[string]any, len(u.present))
	if u.present["customer_id"] {
		if u.CustomerID == nil {
			return nil, errors.New("customer_id is not nullable and cannot be set to null")
		}
		out["customer_id"] = *u.CustomerID
	}
	if u.present["subject"] {
		if u.Subject == nil {
			return nil, errors.New("subject is not nullable and cannot be set to null")
		}
		out["subject"] = *u.Subject
	}
	if u.present["body"] {
		if u.Body == nil {
			return nil, errors.New("body is not nullable and cannot be set to null")
		}
		out["body"] = *u.Body
	}
	if u.present["status"] {
		if u.Status == nil {
			return nil, errors.New("status is not nullable and cannot be set to null")
		}
		out["status"] = *u.Status
	}
	if u.present["priority"] {
		if u.Priority == nil {
			return nil, errors.New("priority is not nullable and cannot be set to null")
		}
		out["priority"] = *u.Priority
	}
	return out, nil
}

// Register mounts every exposed resource on api.
//
// The handlers are rest.Resource, instantiated per model. Registration is
// generic rather than reflective because query hooks are keyed by type: a
// BeforeQuery hook registered on a model applies to its REST reads too, which
// is how tenant scoping stops being something each handler must remember.
func Register(api huma.API, db sqlb.Executor) error {
	if err := rest.Resource[Customer, CustomerCreate, CustomerPatch](api, db, rest.Options{
		Path:            "/customers",
		Name:            "customer",
		Tag:             "customers",
		Ops:             rest.OpCreate | rest.OpRead | rest.OpUpdate | rest.OpList,
		Description:     "Whoever a ticket is on behalf of.",
		DefaultPageSize: 25,
		MaxPageSize:     100,
	}); err != nil {
		return err
	}
	if err := rest.Resource[SupportAgent, rest.None[SupportAgent], rest.None[SupportAgent]](api, db, rest.Options{
		Path:        "/support_agents",
		Name:        "support_agent",
		Tag:         "support_agents",
		Ops:         rest.OpRead | rest.OpList,
		Description: "Someone who answers tickets.",
	}); err != nil {
		return err
	}
	if err := rest.Resource[Ticket, TicketCreate, TicketPatch](api, db, rest.Options{
		Path:            "/tickets",
		Name:            "ticket",
		Tag:             "tickets",
		Ops:             rest.OpCreate | rest.OpRead | rest.OpUpdate | rest.OpList,
		Description:     "One request from one customer.",
		DefaultPageSize: 20,
		MaxPageSize:     100,
		Expandable:      []string{"customer"},
	}); err != nil {
		return err
	}
	return nil
}
