// Code generated by github.com/mind-vm/sqlb. DO NOT EDIT.
//
// The typed client for this schema: row types, request parameters, the encoder
// for the filter grammar, transport functions and cache keys.
//
// It imports nothing. The transport is injected, because session storage,
// token refresh and redirect-on-401 are the application's and are not
// derivable from a schema — the same seam the server takes by mounting onto a
// router the application built.
//
// Property names are the wire spelling, which is the column's own name unless
// the schema declared a WireCase. There is no mapping layer either way: the
// spelling is computed once, at generation time, so there is nothing between
// the response and the caller.
//
// ADR-0028, ADR-0036.
import type { ArrayCond, ChangeEvent, ChangeOp, ChangeStreamOptions, Collection, Cond, DayMatch, NullCheck, Page, TextMatch, Transport } from './runtime.gen.ts';
import { encodeItemQuery, encodeListQuery, itemPath, subscribeEvents } from './runtime.gen.ts';
export * from './runtime.gen.ts';

// --------------------------------------------------------------- comments

/** A comment on a task. */
export interface Comment {
  id: string;
  workspace_id: string;
  task_id: string;
  author_id: string;
  body: string;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

/**
 * The request body for creating a Comment.
 *
 * Read-only columns are absent: the database or a BeforeCreate hook owns
 * them. A column with a default is optional.
 */
export interface CommentCreate {
  task_id: string;
  body: string;
}

// ------------------------------------------------------------------ lists

/** A named list of tasks within a workspace. */
export interface List {
  id: string;
  workspace_id: string;
  name: string;
  description: string;
  color: string;
  position: number;
  archived: boolean;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
  /** Filled in by `expand: ['tasks']`, absent otherwise. Capped at 20 rows. */
  tasks?: Collection<Task>;
}

/**
 * The request body for creating a List.
 *
 * Read-only columns are absent: the database or a BeforeCreate hook owns
 * them. A column with a default is optional.
 */
export interface ListCreate {
  name: string;
  description: string;
  color?: string;
  position?: number;
  archived?: boolean;
}

/**
 * The request body for patching a List.
 *
 * Every property is optional, so a request writes only the columns it
 * names. Immutable columns are absent: they are settable once, at create.
 * Sending `null` for a nullable column writes NULL; omitting it changes
 * nothing, which is the distinction the server reads off the JSON body.
 */
export interface ListPatch {
  name?: string;
  description?: string;
  color?: string;
  position?: number;
  archived?: boolean;
}

// ------------------------------------------------------------ memberships

/** The memberships.role column's value set. */
export type MembershipRole = 'owner' | 'admin' | 'member';

/** A user's membership of a workspace, and their role in it. */
export interface Membership {
  id: string;
  workspace_id: string;
  user_id: string;
  role: MembershipRole;
  created_at: string;
  updated_at: string;
}

/**
 * The request body for creating a Membership.
 *
 * Read-only columns are absent: the database or a BeforeCreate hook owns
 * them. A column with a default is optional.
 */
export interface MembershipCreate {
  user_id: string;
  role?: MembershipRole;
}

// --------------------------------------------------------------- profiles

/** A user's extended profile. One-to-one with users: user_id is unique. */
export interface Profile {
  id: string;
  user_id: string;
  bio: string | null;
  created_at: string;
  updated_at: string;
}

/**
 * The request body for creating a Profile.
 *
 * Read-only columns are absent: the database or a BeforeCreate hook owns
 * them. A column with a default is optional.
 */
export interface ProfileCreate {
  user_id: string;
  bio?: string | null;
}

// ------------------------------------------------------------------ tasks

/** The tasks.status column's value set. */
export type TaskStatus = 'todo' | 'in_progress' | 'blocked' | 'done';

/** The tasks.priority column's value set. */
export type TaskPriority = 'low' | 'medium' | 'high' | 'urgent';

/** A unit of work, belonging to one list. */
export interface Task {
  id: string;
  workspace_id: string;
  list_id: string;
  /** Filled in by `expand: ['list']`, absent otherwise. */
  list?: List;
  assignee_id: string | null;
  author_id: string;
  title: string;
  description: string;
  /** Free-form labels. Filter with has, hasany or hasall. */
  labels: string[];
  status: TaskStatus;
  priority: TaskPriority;
  due_at: string | null;
  completed_at: string | null;
  position: number;
  comment_count: number;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

/**
 * The request body for creating a Task.
 *
 * Read-only columns are absent: the database or a BeforeCreate hook owns
 * them. A column with a default is optional.
 */
export interface TaskCreate {
  list_id: string;
  assignee_id?: string | null;
  title: string;
  description: string;
  /** Free-form labels. Filter with has, hasany or hasall. */
  labels?: string[];
  status?: TaskStatus;
  priority?: TaskPriority;
  due_at?: string | null;
  position?: number;
}

/**
 * The request body for patching a Task.
 *
 * Every property is optional, so a request writes only the columns it
 * names. Immutable columns are absent: they are settable once, at create.
 * Sending `null` for a nullable column writes NULL; omitting it changes
 * nothing, which is the distinction the server reads off the JSON body.
 */
export interface TaskPatch {
  list_id?: string;
  assignee_id?: string | null;
  title?: string;
  description?: string;
  /** Free-form labels. Filter with has, hasany or hasall. */
  labels?: string[];
  status?: TaskStatus;
  priority?: TaskPriority;
  due_at?: string | null;
  position?: number;
}

/** The request body for `POST /tasks/{id}/complete`. */
export interface CompleteTaskInput {
  /** Recorded as a comment on the task, in the same transaction. */
  note?: string | null;
}

// ------------------------------------------------------------------ users

/** A row of users. */
export interface User {
  id: string;
  email: string;
  name: string;
  created_at: string;
  updated_at: string;
  /** Filled in by `expand: ['profile']`, absent otherwise. */
  profile?: Profile | null;
}

// ------------------------------------------------------------- workspaces

/** A tenant. Lists, tasks and comments all belong to exactly one. */
export interface Workspace {
  id: string;
  name: string;
  slug: string;
  created_at: string;
  updated_at: string;
}

// -------------------------------------------------------------- /comments

/** Columns `select` may name. The primary key is always returned. */
export type CommentColumn =
  | 'id'
  | 'workspace_id'
  | 'task_id'
  | 'author_id'
  | 'body'
  | 'created_at'
  | 'updated_at'
  | 'deleted_at';

/** Sortable columns, with their descending forms. */
export type CommentSort = 'created_at' | '-created_at' | 'updated_at' | '-updated_at';

/**
 * Filter conditions, one property per filterable column.
 *
 * A bare value is equality; an object names operators. The operator set is
 * narrowed by column type, so a pattern match against a number and a null
 * test against a non-nullable column do not compile.
 */
export type CommentWhere = {
  id?: Cond<string>;
  workspace_id?: Cond<string>;
  task_id?: Cond<string>;
  author_id?: Cond<string>;
  body?: Cond<string, TextMatch>;
};

/** Parameters for `GET /comments`. */
export interface CommentListParams<S extends CommentColumn = CommentColumn> {
  where?: CommentWhere;
  /** Case-insensitive substring match, fanned out over the searchable columns. */
  search?: string;
  /** Ordering, most significant first. */
  sort?: CommentSort | readonly CommentSort[];
  /** Columns to return. Omitted columns are absent from the response, and the
   * response type narrows to match. */
  select?: readonly S[];
  page?: number;
  per_page?: number;
  /** Resume after a `next_cursor` from a previous response. Cannot be combined
   * with `page`, and is only valid for the `sort` it was issued under. */
  cursor?: string;
  /** Ask for a total row count, which costs a second query. */
  count?: 'exact';
  /** Parameters this vocabulary cannot express, appended verbatim. Reaching for
   * it often means the typed layer is in the wrong place — ADR-0028 says so and
   * names it as the signal to watch. */
  params?: Record<string, string | readonly string[]>;
}

/**
 * Parameters for `GET /comments/{id}`.
 *
 * There is no `select` here: the item endpoint rejects unknown query
 * parameters and does not declare one.
 */
export type CommentGetParams = Record<string, never>;

/**
 * A Comment as one request asked for it: the selected columns, plus the relations
 * it expanded.
 */
export type CommentRow<S extends CommentColumn = CommentColumn> =
  Pick<Comment, S | 'id'>;

/** `GET /comments` — the filtered, sorted, paged collection. */
export function listComments<S extends CommentColumn = CommentColumn>(
  request: Transport,
  params: CommentListParams<S> = {},
  signal?: AbortSignal,
): Promise<Page<CommentRow<S>>> {
  return request({ method: 'GET', path: '/comments', query: encodeListQuery(params), signal });
}

/** `GET /comments/{id}` — one row by primary key. */
export function getComment(
  request: Transport,
  id: string | number,
  params: CommentGetParams = {},
  signal?: AbortSignal,
): Promise<CommentRow<CommentColumn>> {
  return request({ method: 'GET', path: itemPath('/comments', id), query: encodeItemQuery(params), signal });
}

/** `POST /comments` — create a row. */
export function createComment(request: Transport, body: CommentCreate, signal?: AbortSignal): Promise<Comment> {
  return request({ method: 'POST', path: '/comments', body, signal });
}

/**
 * Cache keys for /comments. Deriving them is what keeps a mutation's invalidation
 * and a change-feed subscriber's invalidation from being two lists that can
 * disagree.
 */
export const commentKeys = {
  all: () => ['comments'] as const,
  lists: () => ['comments', 'list'] as const,
  list: (params: unknown = {}) => ['comments', 'list', params] as const,
  infinites: () => ['comments', 'infinite'] as const,
  infinite: (params: unknown = {}) => ['comments', 'infinite', params] as const,
  details: () => ['comments', 'detail'] as const,
  detail: (id: string | number, params: unknown = {}) => ['comments', 'detail', String(id), params] as const,
};

// ----------------------------------------------------------------- /lists

/** Columns `select` may name. The primary key is always returned. */
export type ListColumn =
  | 'id'
  | 'workspace_id'
  | 'name'
  | 'description'
  | 'color'
  | 'position'
  | 'archived'
  | 'created_at'
  | 'updated_at'
  | 'deleted_at';

/** Sortable columns, with their descending forms. */
export type ListSort =
  | 'name'
  | '-name'
  | 'position'
  | '-position'
  | 'archived'
  | '-archived'
  | 'created_at'
  | '-created_at'
  | 'updated_at'
  | '-updated_at';

/** Relations `expand` may name. */
export type ListExpand = 'tasks';

/**
 * Filter conditions, one property per filterable column.
 *
 * A bare value is equality; an object names operators. The operator set is
 * narrowed by column type, so a pattern match against a number and a null
 * test against a non-nullable column do not compile.
 */
export type ListWhere = {
  id?: Cond<string>;
  workspace_id?: Cond<string>;
  name?: Cond<string, TextMatch>;
  description?: Cond<string, TextMatch>;
  color?: Cond<string, TextMatch>;
  archived?: Cond<boolean>;
};

/** Parameters for `GET /lists`. */
export interface ListListParams<S extends ListColumn = ListColumn, E extends ListExpand = never> {
  where?: ListWhere;
  /** Case-insensitive substring match, fanned out over the searchable columns. */
  search?: string;
  /** Ordering, most significant first. */
  sort?: ListSort | readonly ListSort[];
  /** Columns to return. Omitted columns are absent from the response, and the
   * response type narrows to match. */
  select?: readonly S[];
  expand?: readonly E[];
  page?: number;
  per_page?: number;
  /** Resume after a `next_cursor` from a previous response. Cannot be combined
   * with `page`, and is only valid for the `sort` it was issued under. */
  cursor?: string;
  /** Ask for a total row count, which costs a second query. */
  count?: 'exact';
  /** Parameters this vocabulary cannot express, appended verbatim. Reaching for
   * it often means the typed layer is in the wrong place — ADR-0028 says so and
   * names it as the signal to watch. */
  params?: Record<string, string | readonly string[]>;
}

/**
 * Parameters for `GET /lists/{id}`.
 *
 * There is no `select` here: the item endpoint rejects unknown query
 * parameters and does not declare one.
 */
export interface ListGetParams<E extends ListExpand = never> {
  expand?: readonly E[];
}

/**
 * A List as one request asked for it: the selected columns, plus the relations
 * it expanded.
 */
export type ListRow<S extends ListColumn = ListColumn, E extends ListExpand = never> =
  Pick<List, S | 'id'>
  & ('tasks' extends E ? { tasks: Collection<Task> } : unknown);

/** `GET /lists` — the filtered, sorted, paged collection. */
export function listLists<S extends ListColumn = ListColumn, E extends ListExpand = never>(
  request: Transport,
  params: ListListParams<S, E> = {},
  signal?: AbortSignal,
): Promise<Page<ListRow<S, E>>> {
  return request({ method: 'GET', path: '/lists', query: encodeListQuery(params), signal });
}

/** `GET /lists/{id}` — one row by primary key. */
export function getList<E extends ListExpand = never>(
  request: Transport,
  id: string | number,
  params: ListGetParams<E> = {},
  signal?: AbortSignal,
): Promise<ListRow<ListColumn, E>> {
  return request({ method: 'GET', path: itemPath('/lists', id), query: encodeItemQuery(params), signal });
}

/** `POST /lists` — create a row. */
export function createList(request: Transport, body: ListCreate, signal?: AbortSignal): Promise<List> {
  return request({ method: 'POST', path: '/lists', body, signal });
}

/** `PATCH /lists/{id}` — write the columns the body names, and no others. */
export function updateList(request: Transport, id: string | number, body: ListPatch, signal?: AbortSignal): Promise<List> {
  return request({ method: 'PATCH', path: itemPath('/lists', id), body, signal });
}

/**
 * Cache keys for /lists. Deriving them is what keeps a mutation's invalidation
 * and a change-feed subscriber's invalidation from being two lists that can
 * disagree.
 */
export const listKeys = {
  all: () => ['lists'] as const,
  lists: () => ['lists', 'list'] as const,
  list: (params: unknown = {}) => ['lists', 'list', params] as const,
  infinites: () => ['lists', 'infinite'] as const,
  infinite: (params: unknown = {}) => ['lists', 'infinite', params] as const,
  details: () => ['lists', 'detail'] as const,
  detail: (id: string | number, params: unknown = {}) => ['lists', 'detail', String(id), params] as const,
};

// ----------------------------------------------------------- /memberships

/** Columns `select` may name. The primary key is always returned. */
export type MembershipColumn =
  | 'id'
  | 'workspace_id'
  | 'user_id'
  | 'role'
  | 'created_at'
  | 'updated_at';

/** Sortable columns, with their descending forms. */
export type MembershipSort =
  | 'role'
  | '-role'
  | 'created_at'
  | '-created_at'
  | 'updated_at'
  | '-updated_at';

/**
 * Filter conditions, one property per filterable column.
 *
 * A bare value is equality; an object names operators. The operator set is
 * narrowed by column type, so a pattern match against a number and a null
 * test against a non-nullable column do not compile.
 */
export type MembershipWhere = {
  id?: Cond<string>;
  workspace_id?: Cond<string>;
  user_id?: Cond<string>;
  role?: Cond<MembershipRole>;
};

/** Parameters for `GET /memberships`. */
export interface MembershipListParams<S extends MembershipColumn = MembershipColumn> {
  where?: MembershipWhere;
  /** Ordering, most significant first. */
  sort?: MembershipSort | readonly MembershipSort[];
  /** Columns to return. Omitted columns are absent from the response, and the
   * response type narrows to match. */
  select?: readonly S[];
  page?: number;
  per_page?: number;
  /** Resume after a `next_cursor` from a previous response. Cannot be combined
   * with `page`, and is only valid for the `sort` it was issued under. */
  cursor?: string;
  /** Ask for a total row count, which costs a second query. */
  count?: 'exact';
  /** Parameters this vocabulary cannot express, appended verbatim. Reaching for
   * it often means the typed layer is in the wrong place — ADR-0028 says so and
   * names it as the signal to watch. */
  params?: Record<string, string | readonly string[]>;
}

/**
 * Parameters for `GET /memberships/{id}`.
 *
 * There is no `select` here: the item endpoint rejects unknown query
 * parameters and does not declare one.
 */
export type MembershipGetParams = Record<string, never>;

/**
 * A Membership as one request asked for it: the selected columns, plus the relations
 * it expanded.
 */
export type MembershipRow<S extends MembershipColumn = MembershipColumn> =
  Pick<Membership, S | 'id'>;

/** `GET /memberships` — the filtered, sorted, paged collection. */
export function listMemberships<S extends MembershipColumn = MembershipColumn>(
  request: Transport,
  params: MembershipListParams<S> = {},
  signal?: AbortSignal,
): Promise<Page<MembershipRow<S>>> {
  return request({ method: 'GET', path: '/memberships', query: encodeListQuery(params), signal });
}

/** `GET /memberships/{id}` — one row by primary key. */
export function getMembership(
  request: Transport,
  id: string | number,
  params: MembershipGetParams = {},
  signal?: AbortSignal,
): Promise<MembershipRow<MembershipColumn>> {
  return request({ method: 'GET', path: itemPath('/memberships', id), query: encodeItemQuery(params), signal });
}

/** `POST /memberships` — create a row. */
export function createMembership(request: Transport, body: MembershipCreate, signal?: AbortSignal): Promise<Membership> {
  return request({ method: 'POST', path: '/memberships', body, signal });
}

/** `DELETE /memberships/{id}`. */
export function deleteMembership(request: Transport, id: string | number, signal?: AbortSignal): Promise<void> {
  return request({ method: 'DELETE', path: itemPath('/memberships', id), signal });
}

/**
 * Cache keys for /memberships. Deriving them is what keeps a mutation's invalidation
 * and a change-feed subscriber's invalidation from being two lists that can
 * disagree.
 */
export const membershipKeys = {
  all: () => ['memberships'] as const,
  lists: () => ['memberships', 'list'] as const,
  list: (params: unknown = {}) => ['memberships', 'list', params] as const,
  infinites: () => ['memberships', 'infinite'] as const,
  infinite: (params: unknown = {}) => ['memberships', 'infinite', params] as const,
  details: () => ['memberships', 'detail'] as const,
  detail: (id: string | number, params: unknown = {}) => ['memberships', 'detail', String(id), params] as const,
};

// -------------------------------------------------------------- /profiles

/** Columns `select` may name. The primary key is always returned. */
export type ProfileColumn =
  | 'id'
  | 'user_id'
  | 'bio'
  | 'created_at'
  | 'updated_at';

/** Sortable columns, with their descending forms. */
export type ProfileSort = 'created_at' | '-created_at' | 'updated_at' | '-updated_at';

/**
 * Filter conditions, one property per filterable column.
 *
 * A bare value is equality; an object names operators. The operator set is
 * narrowed by column type, so a pattern match against a number and a null
 * test against a non-nullable column do not compile.
 */
export type ProfileWhere = {
  id?: Cond<string>;
};

/** Parameters for `GET /profiles`. */
export interface ProfileListParams<S extends ProfileColumn = ProfileColumn> {
  where?: ProfileWhere;
  /** Ordering, most significant first. */
  sort?: ProfileSort | readonly ProfileSort[];
  /** Columns to return. Omitted columns are absent from the response, and the
   * response type narrows to match. */
  select?: readonly S[];
  page?: number;
  per_page?: number;
  /** Resume after a `next_cursor` from a previous response. Cannot be combined
   * with `page`, and is only valid for the `sort` it was issued under. */
  cursor?: string;
  /** Ask for a total row count, which costs a second query. */
  count?: 'exact';
  /** Parameters this vocabulary cannot express, appended verbatim. Reaching for
   * it often means the typed layer is in the wrong place — ADR-0028 says so and
   * names it as the signal to watch. */
  params?: Record<string, string | readonly string[]>;
}

/**
 * A Profile as one request asked for it: the selected columns, plus the relations
 * it expanded.
 */
export type ProfileRow<S extends ProfileColumn = ProfileColumn> =
  Pick<Profile, S | 'id'>;

/** `POST /profiles` — create a row. */
export function createProfile(request: Transport, body: ProfileCreate, signal?: AbortSignal): Promise<Profile> {
  return request({ method: 'POST', path: '/profiles', body, signal });
}

/**
 * Cache keys for /profiles. Deriving them is what keeps a mutation's invalidation
 * and a change-feed subscriber's invalidation from being two lists that can
 * disagree.
 */
export const profileKeys = {
  all: () => ['profiles'] as const,
  lists: () => ['profiles', 'list'] as const,
  list: (params: unknown = {}) => ['profiles', 'list', params] as const,
  infinites: () => ['profiles', 'infinite'] as const,
  infinite: (params: unknown = {}) => ['profiles', 'infinite', params] as const,
  details: () => ['profiles', 'detail'] as const,
  detail: (id: string | number, params: unknown = {}) => ['profiles', 'detail', String(id), params] as const,
};

// ----------------------------------------------------------------- /tasks

/** Columns `select` may name. The primary key is always returned. */
export type TaskColumn =
  | 'id'
  | 'workspace_id'
  | 'list_id'
  | 'assignee_id'
  | 'author_id'
  | 'title'
  | 'description'
  | 'labels'
  | 'status'
  | 'priority'
  | 'due_at'
  | 'completed_at'
  | 'position'
  | 'comment_count'
  | 'created_at'
  | 'updated_at'
  | 'deleted_at';

/** Sortable columns, with their descending forms. */
export type TaskSort =
  | 'title'
  | '-title'
  | 'status'
  | '-status'
  | 'priority'
  | '-priority'
  | 'due_at'
  | '-due_at'
  | 'completed_at'
  | '-completed_at'
  | 'position'
  | '-position'
  | 'comment_count'
  | '-comment_count'
  | 'created_at'
  | '-created_at'
  | 'updated_at'
  | '-updated_at';

/** Relations `expand` may name. */
export type TaskExpand = 'list';

/**
 * Filter conditions, one property per filterable column.
 *
 * A bare value is equality; an object names operators. The operator set is
 * narrowed by column type, so a pattern match against a number and a null
 * test against a non-nullable column do not compile.
 */
export type TaskWhere = {
  id?: Cond<string>;
  workspace_id?: Cond<string>;
  list_id?: Cond<string>;
  assignee_id?: Cond<string, NullCheck>;
  title?: Cond<string, TextMatch>;
  description?: Cond<string, TextMatch>;
  labels?: ArrayCond<string>;
  status?: Cond<TaskStatus>;
  priority?: Cond<TaskPriority>;
  due_at?: Cond<string | Date, DayMatch & NullCheck>;
  completed_at?: Cond<string | Date, DayMatch & NullCheck>;
  comment_count?: Cond<number>;
};

/** Parameters for `GET /tasks`. */
export interface TaskListParams<S extends TaskColumn = TaskColumn, E extends TaskExpand = never> {
  where?: TaskWhere;
  /** Case-insensitive substring match, fanned out over the searchable columns. */
  search?: string;
  /** Ordering, most significant first. */
  sort?: TaskSort | readonly TaskSort[];
  /** Columns to return. Omitted columns are absent from the response, and the
   * response type narrows to match. */
  select?: readonly S[];
  expand?: readonly E[];
  page?: number;
  per_page?: number;
  /** Resume after a `next_cursor` from a previous response. Cannot be combined
   * with `page`, and is only valid for the `sort` it was issued under. */
  cursor?: string;
  /** Ask for a total row count, which costs a second query. */
  count?: 'exact';
  /** Parameters this vocabulary cannot express, appended verbatim. Reaching for
   * it often means the typed layer is in the wrong place — ADR-0028 says so and
   * names it as the signal to watch. */
  params?: Record<string, string | readonly string[]>;
}

/**
 * Parameters for `GET /tasks/{id}`.
 *
 * There is no `select` here: the item endpoint rejects unknown query
 * parameters and does not declare one.
 */
export interface TaskGetParams<E extends TaskExpand = never> {
  expand?: readonly E[];
}

/**
 * A Task as one request asked for it: the selected columns, plus the relations
 * it expanded.
 */
export type TaskRow<S extends TaskColumn = TaskColumn, E extends TaskExpand = never> =
  Pick<Task, S | 'id'>
  & ('list' extends E ? { list: List } : unknown);

/** `GET /tasks` — the filtered, sorted, paged collection. */
export function listTasks<S extends TaskColumn = TaskColumn, E extends TaskExpand = never>(
  request: Transport,
  params: TaskListParams<S, E> = {},
  signal?: AbortSignal,
): Promise<Page<TaskRow<S, E>>> {
  return request({ method: 'GET', path: '/tasks', query: encodeListQuery(params), signal });
}

/** `GET /tasks/{id}` — one row by primary key. */
export function getTask<E extends TaskExpand = never>(
  request: Transport,
  id: string | number,
  params: TaskGetParams<E> = {},
  signal?: AbortSignal,
): Promise<TaskRow<TaskColumn, E>> {
  return request({ method: 'GET', path: itemPath('/tasks', id), query: encodeItemQuery(params), signal });
}

/** `POST /tasks` — create a row. */
export function createTask(request: Transport, body: TaskCreate, signal?: AbortSignal): Promise<Task> {
  return request({ method: 'POST', path: '/tasks', body, signal });
}

/** `PATCH /tasks/{id}` — write the columns the body names, and no others. */
export function updateTask(request: Transport, id: string | number, body: TaskPatch, signal?: AbortSignal): Promise<Task> {
  return request({ method: 'PATCH', path: itemPath('/tasks', id), body, signal });
}

/** `POST /tasks/{id}/complete` — complete a task. */
export function completeTask(request: Transport, id: string | number, body: CompleteTaskInput, signal?: AbortSignal): Promise<Task> {
  return request({ method: 'POST', path: itemPath('/tasks', id) + '/complete', body, signal });
}

/**
 * Cache keys for /tasks. Deriving them is what keeps a mutation's invalidation
 * and a change-feed subscriber's invalidation from being two lists that can
 * disagree.
 */
export const taskKeys = {
  all: () => ['tasks'] as const,
  lists: () => ['tasks', 'list'] as const,
  list: (params: unknown = {}) => ['tasks', 'list', params] as const,
  infinites: () => ['tasks', 'infinite'] as const,
  infinite: (params: unknown = {}) => ['tasks', 'infinite', params] as const,
  details: () => ['tasks', 'detail'] as const,
  detail: (id: string | number, params: unknown = {}) => ['tasks', 'detail', String(id), params] as const,
};

// ----------------------------------------------------------------- /users

/** Columns `select` may name. The primary key is always returned. */
export type UserColumn =
  | 'id'
  | 'email'
  | 'name'
  | 'created_at'
  | 'updated_at';

/** Sortable columns, with their descending forms. */
export type UserSort =
  | 'name'
  | '-name'
  | 'created_at'
  | '-created_at'
  | 'updated_at'
  | '-updated_at';

/** Relations `expand` may name. */
export type UserExpand = 'profile';

/**
 * Filter conditions, one property per filterable column.
 *
 * A bare value is equality; an object names operators. The operator set is
 * narrowed by column type, so a pattern match against a number and a null
 * test against a non-nullable column do not compile.
 */
export type UserWhere = {
  id?: Cond<string>;
  email?: Cond<string, TextMatch>;
  name?: Cond<string, TextMatch>;
};

/** Parameters for `GET /users`. */
export interface UserListParams<S extends UserColumn = UserColumn, E extends UserExpand = never> {
  where?: UserWhere;
  /** Case-insensitive substring match, fanned out over the searchable columns. */
  search?: string;
  /** Ordering, most significant first. */
  sort?: UserSort | readonly UserSort[];
  /** Columns to return. Omitted columns are absent from the response, and the
   * response type narrows to match. */
  select?: readonly S[];
  expand?: readonly E[];
  page?: number;
  per_page?: number;
  /** Resume after a `next_cursor` from a previous response. Cannot be combined
   * with `page`, and is only valid for the `sort` it was issued under. */
  cursor?: string;
  /** Ask for a total row count, which costs a second query. */
  count?: 'exact';
  /** Parameters this vocabulary cannot express, appended verbatim. Reaching for
   * it often means the typed layer is in the wrong place — ADR-0028 says so and
   * names it as the signal to watch. */
  params?: Record<string, string | readonly string[]>;
}

/**
 * Parameters for `GET /users/{id}`.
 *
 * There is no `select` here: the item endpoint rejects unknown query
 * parameters and does not declare one.
 */
export interface UserGetParams<E extends UserExpand = never> {
  expand?: readonly E[];
}

/**
 * A User as one request asked for it: the selected columns, plus the relations
 * it expanded.
 */
export type UserRow<S extends UserColumn = UserColumn, E extends UserExpand = never> =
  Pick<User, S | 'id'>
  & ('profile' extends E ? { profile: Profile | null } : unknown);

/** `GET /users` — the filtered, sorted, paged collection. */
export function listUsers<S extends UserColumn = UserColumn, E extends UserExpand = never>(
  request: Transport,
  params: UserListParams<S, E> = {},
  signal?: AbortSignal,
): Promise<Page<UserRow<S, E>>> {
  return request({ method: 'GET', path: '/users', query: encodeListQuery(params), signal });
}

/** `GET /users/{id}` — one row by primary key. */
export function getUser<E extends UserExpand = never>(
  request: Transport,
  id: string | number,
  params: UserGetParams<E> = {},
  signal?: AbortSignal,
): Promise<UserRow<UserColumn, E>> {
  return request({ method: 'GET', path: itemPath('/users', id), query: encodeItemQuery(params), signal });
}

/**
 * Cache keys for /users. Deriving them is what keeps a mutation's invalidation
 * and a change-feed subscriber's invalidation from being two lists that can
 * disagree.
 */
export const userKeys = {
  all: () => ['users'] as const,
  lists: () => ['users', 'list'] as const,
  list: (params: unknown = {}) => ['users', 'list', params] as const,
  infinites: () => ['users', 'infinite'] as const,
  infinite: (params: unknown = {}) => ['users', 'infinite', params] as const,
  details: () => ['users', 'detail'] as const,
  detail: (id: string | number, params: unknown = {}) => ['users', 'detail', String(id), params] as const,
};

// ------------------------------------------------------------ /workspaces

/** Columns `select` may name. The primary key is always returned. */
export type WorkspaceColumn =
  | 'id'
  | 'name'
  | 'slug'
  | 'created_at'
  | 'updated_at';

/** Sortable columns, with their descending forms. */
export type WorkspaceSort =
  | 'name'
  | '-name'
  | 'created_at'
  | '-created_at'
  | 'updated_at'
  | '-updated_at';

/**
 * Filter conditions, one property per filterable column.
 *
 * A bare value is equality; an object names operators. The operator set is
 * narrowed by column type, so a pattern match against a number and a null
 * test against a non-nullable column do not compile.
 */
export type WorkspaceWhere = {
  id?: Cond<string>;
  name?: Cond<string, TextMatch>;
  slug?: Cond<string, TextMatch>;
};

/** Parameters for `GET /workspaces`. */
export interface WorkspaceListParams<S extends WorkspaceColumn = WorkspaceColumn> {
  where?: WorkspaceWhere;
  /** Case-insensitive substring match, fanned out over the searchable columns. */
  search?: string;
  /** Ordering, most significant first. */
  sort?: WorkspaceSort | readonly WorkspaceSort[];
  /** Columns to return. Omitted columns are absent from the response, and the
   * response type narrows to match. */
  select?: readonly S[];
  page?: number;
  per_page?: number;
  /** Resume after a `next_cursor` from a previous response. Cannot be combined
   * with `page`, and is only valid for the `sort` it was issued under. */
  cursor?: string;
  /** Ask for a total row count, which costs a second query. */
  count?: 'exact';
  /** Parameters this vocabulary cannot express, appended verbatim. Reaching for
   * it often means the typed layer is in the wrong place — ADR-0028 says so and
   * names it as the signal to watch. */
  params?: Record<string, string | readonly string[]>;
}

/**
 * Parameters for `GET /workspaces/{id}`.
 *
 * There is no `select` here: the item endpoint rejects unknown query
 * parameters and does not declare one.
 */
export type WorkspaceGetParams = Record<string, never>;

/**
 * A Workspace as one request asked for it: the selected columns, plus the relations
 * it expanded.
 */
export type WorkspaceRow<S extends WorkspaceColumn = WorkspaceColumn> =
  Pick<Workspace, S | 'id'>;

/** `GET /workspaces` — the filtered, sorted, paged collection. */
export function listWorkspaces<S extends WorkspaceColumn = WorkspaceColumn>(
  request: Transport,
  params: WorkspaceListParams<S> = {},
  signal?: AbortSignal,
): Promise<Page<WorkspaceRow<S>>> {
  return request({ method: 'GET', path: '/workspaces', query: encodeListQuery(params), signal });
}

/** `GET /workspaces/{id}` — one row by primary key. */
export function getWorkspace(
  request: Transport,
  id: string | number,
  params: WorkspaceGetParams = {},
  signal?: AbortSignal,
): Promise<WorkspaceRow<WorkspaceColumn>> {
  return request({ method: 'GET', path: itemPath('/workspaces', id), query: encodeItemQuery(params), signal });
}

/**
 * Cache keys for /workspaces. Deriving them is what keeps a mutation's invalidation
 * and a change-feed subscriber's invalidation from being two lists that can
 * disagree.
 */
export const workspaceKeys = {
  all: () => ['workspaces'] as const,
  lists: () => ['workspaces', 'list'] as const,
  list: (params: unknown = {}) => ['workspaces', 'list', params] as const,
  infinites: () => ['workspaces', 'infinite'] as const,
  infinite: (params: unknown = {}) => ['workspaces', 'infinite', params] as const,
  details: () => ['workspaces', 'detail'] as const,
  detail: (id: string | number, params: unknown = {}) => ['workspaces', 'detail', String(id), params] as const,
};

// ------------------------------------------------------------ change feed

/**
 * Key factories by table name, for a subscriber that receives a table and a
 * row key and has to decide what to refetch.
 */
export const keysByTable = {
  comments: commentKeys,
  lists: listKeys,
  memberships: membershipKeys,
  profiles: profileKeys,
  tasks: taskKeys,
  users: userKeys,
  workspaces: workspaceKeys,
} as const;

/** A table this client serves. */
export type TableName = keyof typeof keysByTable;

/**
 * The keys one change invalidates, per table.
 *
 * A keyed event names one row, so it invalidates that row's detail queries
 * plus the lists and infinite walks it may have moved in or out of — not
 * every other row's detail. A keyless one invalidates the table, which is
 * what an event nobody could attribute to a single row asks for.
 */
const changeKeysByTable: Record<TableName, (key: string) => readonly (readonly unknown[])[]> = {
  comments: (key) =>
    key === ''
      ? [commentKeys.all()]
      : [commentKeys.lists(), commentKeys.infinites(), commentKeys.detail(key)],
  lists: (key) =>
    key === ''
      ? [listKeys.all()]
      : [listKeys.lists(), listKeys.infinites(), listKeys.detail(key)],
  memberships: (key) =>
    key === ''
      ? [membershipKeys.all()]
      : [membershipKeys.lists(), membershipKeys.infinites(), membershipKeys.detail(key)],
  profiles: (key) =>
    key === ''
      ? [profileKeys.all()]
      : [profileKeys.lists(), profileKeys.infinites(), profileKeys.detail(key)],
  tasks: (key) =>
    key === ''
      ? [taskKeys.all()]
      : [taskKeys.lists(), taskKeys.infinites(), taskKeys.detail(key)],
  users: (key) =>
    key === ''
      ? [userKeys.all()]
      : [userKeys.lists(), userKeys.infinites(), userKeys.detail(key)],
  workspaces: (key) =>
    key === ''
      ? [workspaceKeys.all()]
      : [workspaceKeys.lists(), workspaceKeys.infinites(), workspaceKeys.detail(key)],
};

/** One change to a table this client serves. */
export interface TableChange {
  /** The table that changed, narrowed to the ones this client serves. */
  table: TableName;
  /** The row's primary key, or empty when the whole table is invalidated. */
  key: string;
  op: ChangeOp;
  /** The cache keys that read what changed. Hand each to invalidateQueries. */
  keys: readonly (readonly unknown[])[];
}

/** Whether a table name off the wire is one this client serves. */
export function isTableName(table: string): table is TableName {
  return Object.hasOwn(changeKeysByTable, table);
}

/**
 * The cache keys one change invalidates — empty for a table this client does
 * not serve.
 *
 * Exported for a subscriber whose events arrive by some other route than the
 * endpoint: a socket a gateway relays, a service worker, a test.
 */
export function changeKeys(event: ChangeEvent): readonly (readonly unknown[])[] {
  return isTableName(event.table) ? changeKeysByTable[event.table](event.key) : [];
}

/**
 * Subscribes to the change feed, resolving each event to the keys it
 * invalidates. Returns the function that closes the stream.
 *
 *     const stop = subscribeChanges('/events', {
 *       onChange: ({ keys }) => keys.forEach((queryKey) => qc.invalidateQueries({ queryKey })),
 *       onReset: () => qc.invalidateQueries(),
 *     });
 *
 * An event naming a table this client does not serve is dropped: a client
 * generated from one module of a schema receives the other modules' events
 * too, and nothing here displays them. A reset is not dropped — it means the
 * stream could not be resumed, so what is on display is stale whatever it is
 * showing.
 */
export function subscribeChanges(
  url: string,
  options: ChangeStreamOptions<TableChange> = {},
): () => void {
  const onChange = options.onChange;
  return subscribeEvents(url, {
    ...options,
    onChange:
      onChange === undefined
        ? undefined
        : (event) => {
            if (!isTableName(event.table)) return;
            onChange({ ...event, table: event.table, keys: changeKeys(event) });
          },
  });
}
