// Code generated by github.com/mind-vm/sqlb. DO NOT EDIT.
//
// TanStack Query option factories, one per exposed resource.
//
// Option objects rather than hooks: a hook bakes in a framework and is the
// thing people copy out and edit, where an options object is spread and
// overridden. Deleting this file breaks only the call sites that used it — the
// types, the encoder and the keys next door do not depend on it.
//
// A mutation carries mutationFn and no onSuccess: what a write invalidates is
// not derivable from a schema. keysByTable is the mechanical half.
//
// ADR-0028.

import { infiniteQueryOptions, mutationOptions, queryOptions } from '@tanstack/react-query';
import type {
  ByListTasksParams,
  CommentColumn,
  CommentCreate,
  CommentGetParams,
  CommentListParams,
  CompleteTaskInput,
  ListColumn,
  ListCreate,
  ListExpand,
  ListGetParams,
  ListListParams,
  ListPatch,
  MembershipColumn,
  MembershipCreate,
  MembershipGetParams,
  MembershipListParams,
  ProfileCreate,
  TaskColumn,
  TaskCreate,
  TaskExpand,
  TaskGetParams,
  TaskListParams,
  TaskPatch,
  Transport,
  UserColumn,
  UserExpand,
  UserGetParams,
  UserListParams,
  WorkspaceColumn,
  WorkspaceGetParams,
  WorkspaceListParams,
} from './client.gen';
import {
  byListTasks,
  commentKeys,
  completeTask,
  createComment,
  createList,
  createMembership,
  createProfile,
  createTask,
  deleteMembership,
  getComment,
  getList,
  getMembership,
  getTask,
  getUser,
  getWorkspace,
  listComments,
  listKeys,
  listLists,
  listMemberships,
  listTasks,
  listUsers,
  listWorkspaces,
  membershipKeys,
  taskKeys,
  updateList,
  updateTask,
  userKeys,
  workspaceKeys,
} from './client.gen';

// -------------------------------------------------------------- /comments

/**
 * Read options for /comments, bound to a transport.
 *
 * `queryOptions` objects rather than hooks: an options object is spread and
 * overridden — `{ ...queries.list(p), staleTime: 30_000 }` — where a hook is
 * copied out and edited, which is the signal that a seam is in the wrong
 * place.
 */
export function commentQueries(request: Transport) {
  return {
    list: <S extends CommentColumn = CommentColumn>(params: CommentListParams<S> = {}) =>
      queryOptions({
        queryKey: commentKeys.list(params),
        queryFn: ({ signal }) => listComments(request, params, signal),
      }),
    infinite: <S extends CommentColumn = CommentColumn>(params: Omit<CommentListParams<S>, 'page' | 'cursor'> = {}) =>
      infiniteQueryOptions({
        queryKey: commentKeys.infinite(params),
        queryFn: ({ pageParam, signal }) => listComments(request, { ...params, cursor: pageParam }, signal),
        initialPageParam: undefined as string | undefined,
        getNextPageParam: (last) => last.next_cursor,
      }),
    detail: (id: string | number, params: CommentGetParams = {}) =>
      queryOptions({
        queryKey: commentKeys.detail(id, params),
        queryFn: ({ signal }) => getComment(request, id, params, signal),
      }),
  };
}

/**
 * Write options for /comments, bound to a transport.
 *
 * `mutationFn` and nothing else: what a write should invalidate is a policy
 * this file cannot derive, so it is spread in rather than edited out —
 * `useMutation({ ...commentMutations(request).create, onSuccess })`.
 */
export function commentMutations(request: Transport) {
  return {
    create: mutationOptions({
      mutationFn: (body: CommentCreate) => createComment(request, body),
    }),
  };
}

// ----------------------------------------------------------------- /lists

/**
 * Read options for /lists, bound to a transport.
 *
 * `queryOptions` objects rather than hooks: an options object is spread and
 * overridden — `{ ...queries.list(p), staleTime: 30_000 }` — where a hook is
 * copied out and edited, which is the signal that a seam is in the wrong
 * place.
 */
export function listQueries(request: Transport) {
  return {
    list: <S extends ListColumn = ListColumn, E extends ListExpand = never>(params: ListListParams<S, E> = {}) =>
      queryOptions({
        queryKey: listKeys.list(params),
        queryFn: ({ signal }) => listLists(request, params, signal),
      }),
    infinite: <S extends ListColumn = ListColumn, E extends ListExpand = never>(params: Omit<ListListParams<S, E>, 'page' | 'cursor'> = {}) =>
      infiniteQueryOptions({
        queryKey: listKeys.infinite(params),
        queryFn: ({ pageParam, signal }) => listLists(request, { ...params, cursor: pageParam }, signal),
        initialPageParam: undefined as string | undefined,
        getNextPageParam: (last) => last.next_cursor,
      }),
    detail: <E extends ListExpand = never>(id: string | number, params: ListGetParams<E> = {}) =>
      queryOptions({
        queryKey: listKeys.detail(id, params),
        queryFn: ({ signal }) => getList(request, id, params, signal),
      }),
  };
}

/**
 * Write options for /lists, bound to a transport.
 *
 * `mutationFn` and nothing else: what a write should invalidate is a policy
 * this file cannot derive, so it is spread in rather than edited out —
 * `useMutation({ ...listMutations(request).create, onSuccess })`.
 */
export function listMutations(request: Transport) {
  return {
    create: mutationOptions({
      mutationFn: (body: ListCreate) => createList(request, body),
    }),
    update: mutationOptions({
      mutationFn: ({ id, body }: { id: string | number; body: ListPatch }) => updateList(request, id, body),
    }),
  };
}

// ----------------------------------------------------------- /memberships

/**
 * Read options for /memberships, bound to a transport.
 *
 * `queryOptions` objects rather than hooks: an options object is spread and
 * overridden — `{ ...queries.list(p), staleTime: 30_000 }` — where a hook is
 * copied out and edited, which is the signal that a seam is in the wrong
 * place.
 */
export function membershipQueries(request: Transport) {
  return {
    list: <S extends MembershipColumn = MembershipColumn>(params: MembershipListParams<S> = {}) =>
      queryOptions({
        queryKey: membershipKeys.list(params),
        queryFn: ({ signal }) => listMemberships(request, params, signal),
      }),
    infinite: <S extends MembershipColumn = MembershipColumn>(params: Omit<MembershipListParams<S>, 'page' | 'cursor'> = {}) =>
      infiniteQueryOptions({
        queryKey: membershipKeys.infinite(params),
        queryFn: ({ pageParam, signal }) => listMemberships(request, { ...params, cursor: pageParam }, signal),
        initialPageParam: undefined as string | undefined,
        getNextPageParam: (last) => last.next_cursor,
      }),
    detail: (id: string | number, params: MembershipGetParams = {}) =>
      queryOptions({
        queryKey: membershipKeys.detail(id, params),
        queryFn: ({ signal }) => getMembership(request, id, params, signal),
      }),
  };
}

/**
 * Write options for /memberships, bound to a transport.
 *
 * `mutationFn` and nothing else: what a write should invalidate is a policy
 * this file cannot derive, so it is spread in rather than edited out —
 * `useMutation({ ...membershipMutations(request).create, onSuccess })`.
 */
export function membershipMutations(request: Transport) {
  return {
    create: mutationOptions({
      mutationFn: (body: MembershipCreate) => createMembership(request, body),
    }),
    delete: mutationOptions({
      mutationFn: (id: string | number) => deleteMembership(request, id),
    }),
  };
}

// -------------------------------------------------------------- /profiles

/**
 * Write options for /profiles, bound to a transport.
 *
 * `mutationFn` and nothing else: what a write should invalidate is a policy
 * this file cannot derive, so it is spread in rather than edited out —
 * `useMutation({ ...profileMutations(request).create, onSuccess })`.
 */
export function profileMutations(request: Transport) {
  return {
    create: mutationOptions({
      mutationFn: (body: ProfileCreate) => createProfile(request, body),
    }),
  };
}

// ----------------------------------------------------------------- /tasks

/**
 * Read options for /tasks, bound to a transport.
 *
 * `queryOptions` objects rather than hooks: an options object is spread and
 * overridden — `{ ...queries.list(p), staleTime: 30_000 }` — where a hook is
 * copied out and edited, which is the signal that a seam is in the wrong
 * place.
 */
export function taskQueries(request: Transport) {
  return {
    list: <S extends TaskColumn = TaskColumn, E extends TaskExpand = never>(params: TaskListParams<S, E> = {}) =>
      queryOptions({
        queryKey: taskKeys.list(params),
        queryFn: ({ signal }) => listTasks(request, params, signal),
      }),
    infinite: <S extends TaskColumn = TaskColumn, E extends TaskExpand = never>(params: Omit<TaskListParams<S, E>, 'page' | 'cursor'> = {}) =>
      infiniteQueryOptions({
        queryKey: taskKeys.infinite(params),
        queryFn: ({ pageParam, signal }) => listTasks(request, { ...params, cursor: pageParam }, signal),
        initialPageParam: undefined as string | undefined,
        getNextPageParam: (last) => last.next_cursor,
      }),
    detail: <E extends TaskExpand = never>(id: string | number, params: TaskGetParams<E> = {}) =>
      queryOptions({
        queryKey: taskKeys.detail(id, params),
        queryFn: ({ signal }) => getTask(request, id, params, signal),
      }),
    byList: (params: ByListTasksParams = {}) =>
      queryOptions({
        queryKey: taskKeys.query('by-list', params),
        queryFn: ({ signal }) => byListTasks(request, params, signal),
      }),
  };
}

/**
 * Write options for /tasks, bound to a transport.
 *
 * `mutationFn` and nothing else: what a write should invalidate is a policy
 * this file cannot derive, so it is spread in rather than edited out —
 * `useMutation({ ...taskMutations(request).create, onSuccess })`.
 */
export function taskMutations(request: Transport) {
  return {
    create: mutationOptions({
      mutationFn: (body: TaskCreate) => createTask(request, body),
    }),
    update: mutationOptions({
      mutationFn: ({ id, body }: { id: string | number; body: TaskPatch }) => updateTask(request, id, body),
    }),
    complete: mutationOptions({
      mutationFn: ({ id, body }: { id: string | number; body: CompleteTaskInput }) => completeTask(request, id, body),
    }),
  };
}

// ----------------------------------------------------------------- /users

/**
 * Read options for /users, bound to a transport.
 *
 * `queryOptions` objects rather than hooks: an options object is spread and
 * overridden — `{ ...queries.list(p), staleTime: 30_000 }` — where a hook is
 * copied out and edited, which is the signal that a seam is in the wrong
 * place.
 */
export function userQueries(request: Transport) {
  return {
    list: <S extends UserColumn = UserColumn, E extends UserExpand = never>(params: UserListParams<S, E> = {}) =>
      queryOptions({
        queryKey: userKeys.list(params),
        queryFn: ({ signal }) => listUsers(request, params, signal),
      }),
    infinite: <S extends UserColumn = UserColumn, E extends UserExpand = never>(params: Omit<UserListParams<S, E>, 'page' | 'cursor'> = {}) =>
      infiniteQueryOptions({
        queryKey: userKeys.infinite(params),
        queryFn: ({ pageParam, signal }) => listUsers(request, { ...params, cursor: pageParam }, signal),
        initialPageParam: undefined as string | undefined,
        getNextPageParam: (last) => last.next_cursor,
      }),
    detail: <E extends UserExpand = never>(id: string | number, params: UserGetParams<E> = {}) =>
      queryOptions({
        queryKey: userKeys.detail(id, params),
        queryFn: ({ signal }) => getUser(request, id, params, signal),
      }),
  };
}

// ------------------------------------------------------------ /workspaces

/**
 * Read options for /workspaces, bound to a transport.
 *
 * `queryOptions` objects rather than hooks: an options object is spread and
 * overridden — `{ ...queries.list(p), staleTime: 30_000 }` — where a hook is
 * copied out and edited, which is the signal that a seam is in the wrong
 * place.
 */
export function workspaceQueries(request: Transport) {
  return {
    list: <S extends WorkspaceColumn = WorkspaceColumn>(params: WorkspaceListParams<S> = {}) =>
      queryOptions({
        queryKey: workspaceKeys.list(params),
        queryFn: ({ signal }) => listWorkspaces(request, params, signal),
      }),
    infinite: <S extends WorkspaceColumn = WorkspaceColumn>(params: Omit<WorkspaceListParams<S>, 'page' | 'cursor'> = {}) =>
      infiniteQueryOptions({
        queryKey: workspaceKeys.infinite(params),
        queryFn: ({ pageParam, signal }) => listWorkspaces(request, { ...params, cursor: pageParam }, signal),
        initialPageParam: undefined as string | undefined,
        getNextPageParam: (last) => last.next_cursor,
      }),
    detail: (id: string | number, params: WorkspaceGetParams = {}) =>
      queryOptions({
        queryKey: workspaceKeys.detail(id, params),
        queryFn: ({ signal }) => getWorkspace(request, id, params, signal),
      }),
  };
}
