// Command migrate renders this example's schema into goose migrations.
//
//	go run ./cmd/migrate            write any migration that does not exist yet
//	go run ./cmd/migrate -force     rewrite them, for editing the schema in development
//
// It does not apply anything. sqlb produces migration files and stops there;
// the runner is goose, invoked by the fxkit glue at startup and by the
// tests. That split is the point — see example/tasks/cmd/migrate, which says
// it at length, and whose second migration is the interesting case this one
// does not have.
//
// What this one adds by hand is a single trigger, for a reason that applies to
// every schema declaring Timestamps(): updated_at is set by its column default
// at insert and by nothing at all afterwards. A trigger is the only place that
// covers every writer, including the migration that backfills a column and the
// psql session somebody used to fix a row.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"

	"github.com/mind-vm/sqlb/migrate"
	"github.com/mind-vm/sqlb/schema"

	// Imported for its side effects: declaring a table registers it.
	_ "github.com/mind-vm/sqlb/example/fxapp/noteschema"
)

func main() {
	dir := flag.String("dir", "store/migrations", "output directory")
	force := flag.Bool("force", false, "delete and rewrite existing migrations (development only)")
	flag.Parse()

	if err := run(*dir, *force); err != nil {
		fmt.Fprintln(os.Stderr, "migrate:", err)
		os.Exit(1)
	}
}

func run(dir string, force bool) error {
	// The current side of the diff is an empty registry: this is a baseline,
	// building the schema from nothing. Once a database exists, current should
	// come from shadow.Build — replaying the checked-in history — rather than
	// from this program's idea of what has been applied.
	changes, err := migrate.Diff(schema.NewRegistry(), schema.DefaultRegistry(), migrate.MinPostgres(18))
	if err != nil {
		return fmt.Errorf("diffing the schema: %w", err)
	}

	// The second migration's Options carries Handwritten: its Changes are
	// composed in triggers() below rather than produced by Diff, so it would
	// be false for its file to claim "Generated by sqlb" — and false in a way
	// `sqlb check` now reads back (issue #178): the header is a claim that
	// every statement in the file is DDL sqlb's own emitters could have
	// written, and CREATE TRIGGER / CREATE FUNCTION are exactly the DDL they
	// never emit.
	migrations := []migrationFile{
		{
			m:    migrate.Migration{Version: migrate.SequentialVersion(1), Name: "initial_schema", Changes: changes},
			opts: migrate.Options{Format: migrate.Goose},
		},
		{
			m:    migrate.Migration{Version: migrate.SequentialVersion(2), Name: "touch_updated_at", Changes: triggers()},
			opts: migrate.Options{Format: migrate.Goose, Handwritten: true},
		},
	}

	if force {
		if err := clear(dir, migrations); err != nil {
			return err
		}
	}

	for _, mf := range migrations {
		written, err := migrate.Write(dir, mf.m, mf.opts)
		if err != nil {
			return err
		}
		for _, f := range written {
			fmt.Println("wrote", f)
		}
	}
	return nil
}

// migrationFile pairs a Migration with the Options it renders under, since the
// two migrations here need different ones: the first is Diff's own output and
// the second is not (see the Handwritten note above).
type migrationFile struct {
	m    migrate.Migration
	opts migrate.Options
}

// clear removes exactly the files the run is about to write, and nothing else.
//
// migrate.Write refuses to overwrite, because a migration already applied
// somewhere must not change under the runner's feet. -force is the development
// escape from that rule, so it deletes only what Render says it would produce
// rather than everything in the directory.
func clear(dir string, migrations []migrationFile) error {
	for _, mf := range migrations {
		files, err := migrate.Render(mf.m, mf.opts)
		if err != nil {
			return err
		}
		for name := range files {
			if err := os.Remove(filepath.Join(dir, name)); err != nil && !os.IsNotExist(err) {
				return err
			}
		}
	}
	return nil
}

// tables carrying updated_at. Listed rather than derived from the registry
// because the trigger is hand-written anyway, and a list somebody has to
// extend when a table is added is more obvious than a loop that silently
// covers a new one.
var touched = []string{"spaces", "notes"}

func triggers() []migrate.Change {
	changes := []migrate.Change{{
		Comment: "updated_at is set by its column default at insert and by nothing afterwards. " +
			"A trigger is the only place this can live where every writer is covered — including " +
			"the ones that are not this application.",
		Up: `CREATE OR REPLACE FUNCTION touch_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$;`,
		Down: `DROP FUNCTION IF EXISTS touch_updated_at();`,
	}}

	for _, table := range touched {
		changes = append(changes, migrate.Change{
			Up: fmt.Sprintf(
				"CREATE TRIGGER %s_touch_updated_at BEFORE UPDATE ON %q\n"+
					"    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();", table, table),
			Down: fmt.Sprintf("DROP TRIGGER IF EXISTS %s_touch_updated_at ON %q;", table, table),
		})
	}
	return changes
}
