// Code generated by github.com/mind-vm/sqlb. DO NOT EDIT.

package cli

import (
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"os"
	"strconv"
	"strings"
	"time"

	"github.com/mind-vm/sqlb/example/tasks/cli/client"
	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

// --------------------------------------------------------------------- cobra

// nullableColumn is a column --set-null accepts, in its two spellings: the one
// the flag is written with, which is the column's own and does not move when
// the schema declares a WireCase, and the one the request body has to use,
// which does. Under the default they are the same string.
type nullableColumn struct {
	Column string
	Wire   string
}

// setNullFields records an explicit null for each named column.
//
// A value flag can say that a column is now empty; it cannot say that it is now
// null, and the two write different SQL. This is the command-line form of the
// presence map the generated patch body keeps for the same reason.
func setNullFields(body map[string]any, names []string, nullable []nullableColumn) error {
	allowed := make([]string, 0, len(nullable))
	for _, c := range nullable {
		allowed = append(allowed, c.Column)
	}
	for _, name := range names {
		column := strings.ReplaceAll(name, "-", "_")
		wire := ""
		for _, c := range nullable {
			if c.Column == column {
				wire = c.Wire
				break
			}
		}
		if wire == "" {
			return fmt.Errorf("--set-null %s: not a nullable column of this resource; allowed: %s",
				name, strings.Join(allowed, ", "))
		}
		body[wire] = nil
	}
	return nil
}

func envOr(name, def string) string {
	if v := os.Getenv(name); v != "" {
		return v
	}
	return def
}

// orString and orDuration resolve one setting's default.
//
// Binding a flag writes its default into the variable, so a Client the caller
// configured would be overwritten by registration alone. Feeding its value in
// as the default instead gives the precedence a reader would expect: the flag
// wins over the field, the field over the environment, and the environment
// over the built-in.
func orString(configured, def string) string {
	if configured != "" {
		return configured
	}
	return def
}

func orDuration(configured, def time.Duration) time.Duration {
	if configured != 0 {
		return configured
	}
	return def
}

// runRequest bridges cobra to the client's Run: the command supplies the
// context and the output stream, and everything else is the client package's.
//
// Named runRequest rather than run because a generated unexported identifier
// shares a package with whatever the consumer writes beside it, and run is a
// name a hand-written file in a command package is likely to want — the tasks
// example had one.
func runRequest(c *client.Client, cmd *cobra.Command, req client.Request, all bool) error {
	return c.Run(cmd.Context(), cmd.OutOrStdout(), req, all)
}

// normalizeFlag accepts a column's own spelling as well as the kebab-case one
// cobra conventionally uses, so a name read out of sqlb.json or out of an error
// response can be typed verbatim.
func normalizeFlag(_ *pflag.FlagSet, name string) pflag.NormalizedName {
	return pflag.NormalizedName(strings.ReplaceAll(name, "_", "-"))
}

// registerCompletion offers a fixed set of values for a flag.
//
// The error is dropped deliberately: it reports only that the flag does not
// exist, which would be a generator bug rather than a runtime condition, and
// the flag is declared one line above every call.
func registerCompletion(cmd *cobra.Command, flag string, values []string) {
	_ = cmd.RegisterFlagCompletionFunc(flag,
		func(*cobra.Command, []string, string) ([]string, cobra.ShellCompDirective) {
			return values, cobra.ShellCompDirectiveNoFileComp
		})
}

// New returns the root command.
//
// c carries what the schema cannot derive — the base URL, the credential, the
// timeout — and is bound to the persistent flags below. Pass nil for a client
// configured entirely from flags and the environment; pass one with Transport
// set to route every request through your own code instead.
//
//	func main() {
//	    if err := cli.New(nil).Execute(); err != nil {
//	        os.Exit(1)
//	    }
//	}
func New(c *client.Client) *cobra.Command {
	if c == nil {
		c = &client.Client{}
	}
	root := &cobra.Command{
		Use:   "taskctl",
		Short: "Command-line client for the taskctl API",
		Long: `taskctl drives the API generated from this project's sqlb schema.

Every response is written to stdout as JSON, so output pipes into jq without a
flag. Failures go to stderr and set a non-zero exit code; a rejected request
prints what the server would have accepted instead, which is usually the whole
fix.

Configuration comes from $TASKCTL_BASE_URL and $TASKCTL_TOKEN, or from --base-url
and --token.

Filtering, sorting, searching and expansion are restricted to the columns that
declared the capability, so a "list" command's --help is an exact statement of
what that resource accepts.`,
		SilenceUsage: true,
	}
	// Column names are snake_case, and cobra flags are conventionally kebab.
	// Accepting both spellings means a caller that read a column name out of
	// sqlb.json can type it verbatim.
	root.SetGlobalNormalizationFunc(normalizeFlag)

	flags := root.PersistentFlags()
	flags.StringVar(&c.BaseURL, "base-url", orString(c.BaseURL, envOr("TASKCTL_BASE_URL", "http://localhost:8080")),
		"Root of the API, without a trailing slash. Defaults to $TASKCTL_BASE_URL.")
	flags.StringVar(&c.Token, "token", orString(c.Token, os.Getenv("TASKCTL_TOKEN")),
		"Bearer token, sent as Authorization. Defaults to $TASKCTL_TOKEN, which is where it\n"+
			"belongs: a token on the command line is visible in the process list.")
	flags.DurationVar(&c.Timeout, "timeout", orDuration(c.Timeout, 30*time.Second), "Per-request timeout.")
	flags.BoolVar(&c.Compact, "compact", c.Compact,
		"Write each response as one line rather than indented.")
	flags.BoolVarP(&c.Verbose, "verbose", "v", c.Verbose,
		"Log each request's method and URL to stderr.")

	root.AddCommand(newCommentsCommand(c))
	root.AddCommand(newListsCommand(c))
	root.AddCommand(newMembershipsCommand(c))
	root.AddCommand(newProfilesCommand(c))
	root.AddCommand(newTasksCommand(c))
	root.AddCommand(newUsersCommand(c))
	root.AddCommand(newWorkspacesCommand(c))
	return root
}

// ---------------------------------------------------------------- /comments

// newCommentsCommand groups the operations /comments exposes.
func newCommentsCommand(c *client.Client) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "comments",
		Short: "A comment on a task",
	}
	cmd.AddCommand(newCommentsListCommand(c))
	cmd.AddCommand(newCommentsGetCommand(c))
	cmd.AddCommand(newCommentsCreateCommand(c))
	return cmd
}

// newCommentsListCommand is GET /comments.
func newCommentsListCommand(c *client.Client) *cobra.Command {
	var (
		filterID          []string
		filterWorkspaceID []string
		filterTaskID      []string
		filterAuthorID    []string
		filterBody        []string
		sort              []string
		select_           []string
		search            string
		page              int
		perPage           int
		count             bool
		cursor            string
		all               bool
	)
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List comments",
		Long: `A comment on a task.

GET /comments

A filter flag takes operator.value, or a bare value for equality, and repeating
one conjoins its conditions — a lower and an upper bound on the same column are
two occurrences of its flag.

Only the columns that declared a capability are reachable through it, so the
flags below are the complete list: a column absent from them cannot be
filtered, sorted or searched by any spelling.`,
		Example: `  # The first page, twenty rows at a time
  taskctl comments list --per-page 20

  # Conditions on one column conjoin; conditions on two intersect
  taskctl comments list --body contains.something

  # Ordered, and projected down to the columns about to be read
  taskctl comments list --sort -created_at --select id,workspace_id

  # Every matching row, walked by cursor rather than by page number
  taskctl comments list --all`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			q := url.Values{}
			for _, v := range filterID {
				q.Add("id", v)
			}
			for _, v := range filterWorkspaceID {
				q.Add("workspace_id", v)
			}
			for _, v := range filterTaskID {
				q.Add("task_id", v)
			}
			for _, v := range filterAuthorID {
				q.Add("author_id", v)
			}
			for _, v := range filterBody {
				q.Add("body", v)
			}
			if search != "" {
				q.Set("search", search)
			}
			if len(sort) > 0 {
				q.Set("sort", strings.Join(sort, ","))
			}
			if len(select_) > 0 {
				q.Set("select", strings.Join(select_, ","))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", strconv.Itoa(page))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", strconv.Itoa(perPage))
			}
			if count {
				q.Set("count", "exact")
			}
			if cursor != "" {
				q.Set("cursor", cursor)
			}
			if all && (cmd.Flags().Changed("page") || cursor != "") {
				return errors.New("--all walks the result set with cursors, so it cannot be combined with --page or --cursor")
			}
			return runRequest(c, cmd, client.Request{Method: http.MethodGet, Path: "/comments", Query: q}, all)
		},
	}
	flags := cmd.Flags()
	flags.StringArrayVar(&filterID, "id", nil,
		`Filter on id, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterWorkspaceID, "workspace-id", nil,
		`Filter on workspace_id, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterTaskID, "task-id", nil,
		`Filter on task_id, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterAuthorID, "author-id", nil,
		`Filter on author_id, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterBody, "body", nil,
		`Filter on body, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringSliceVar(&sort, "sort", nil,
		`Ordering, most significant first. Prefix a column with - for descending.
Columns: created_at, updated_at.`)
	registerCompletion(cmd, "sort", []string{"created_at", "-created_at", "updated_at", "-updated_at"})
	flags.StringSliceVar(&select_, "select", nil,
		`Columns to return; the primary key is always included. Omitted columns are
absent from the response rather than present and empty.
Columns: id, workspace_id, task_id, author_id, body, created_at, updated_at, deleted_at.`)
	registerCompletion(cmd, "select", []string{"id", "workspace_id", "task_id", "author_id", "body", "created_at", "updated_at", "deleted_at"})
	flags.StringVar(&search, "search", "",
		"Case-insensitive substring match, fanned out across body.")
	flags.IntVar(&page, "page", 1, "Page number, 1-based.")
	flags.IntVar(&perPage, "per-page", 0, `Rows per page. A value above the resource's ceiling is capped rather than
rejected.`)
	flags.BoolVar(&count, "count", false, `Include the total number of matching rows. It costs a second query, which is
why has_more is always present and this is not.`)
	flags.StringVar(&cursor, "cursor", "", `Resume after the next_cursor of a previous response. Cursor paging costs the
same at any depth and cannot skip or repeat a row when the table is written to
mid-walk, so prefer it to --page for anything that walks a whole result set. A
cursor is only valid for the --sort it was issued under.`)
	flags.BoolVar(&all, "all", false, `Follow next_cursor until the result set is exhausted and write every row as one
response. This is the loop a caller would otherwise write, and it pages by
cursor, so a concurrent insert cannot make it read a row twice.`)
	return cmd
}

// newCommentsGetCommand is GET /comments/{id}.
func newCommentsGetCommand(c *client.Client) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Fetch one comment by primary key",
		Long: `GET /comments/{id}

The item endpoint declares no query parameters but expand, and rejects any
other rather than answering a question that was not asked.`,
		Example: "  taskctl comments get <id>",
		Args:    cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			q := url.Values{}
			return runRequest(c, cmd, client.Request{Method: http.MethodGet, Path: client.ItemPath("/comments", args[0]), Query: q}, false)
		},
	}
	return cmd
}

// newCommentsCreateCommand is Post /comments.
func newCommentsCreateCommand(c *client.Client) *cobra.Command {
	var (
		valTaskID string
		valBody   string
	)
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create one comment",
		Args:  cobra.NoArgs,
		Long: `POST /comments

Read-only columns have no flag: the database or a BeforeCreate hook owns them,
so there is nothing for a caller to send. A column with a default is optional,
and leaving it out means the database supplies the value rather than the zero
value overwriting it.`,
		Example: "  taskctl comments create --task-id <task_id> --body '<body>'",
		RunE: func(cmd *cobra.Command, _ []string) error {
			body := map[string]any{}
			if cmd.Flags().Changed("task-id") {
				body["task_id"] = valTaskID
			}
			if cmd.Flags().Changed("body") {
				body["body"] = valBody
			}
			return runRequest(c, cmd, client.Request{Method: http.MethodPost, Path: "/comments", Body: body}, false)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&valTaskID, "task-id", "",
		"UUID. References tasks. Required.")
	_ = cmd.MarkFlagRequired("task-id")
	flags.StringVar(&valBody, "body", "",
		"Required.")
	_ = cmd.MarkFlagRequired("body")
	return cmd
}

// ------------------------------------------------------------------- /lists

// newListsCommand groups the operations /lists exposes.
func newListsCommand(c *client.Client) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "lists",
		Short: "A named list of tasks within a workspace",
	}
	cmd.AddCommand(newListsListCommand(c))
	cmd.AddCommand(newListsGetCommand(c))
	cmd.AddCommand(newListsCreateCommand(c))
	cmd.AddCommand(newListsUpdateCommand(c))
	return cmd
}

// newListsListCommand is GET /lists.
func newListsListCommand(c *client.Client) *cobra.Command {
	var (
		filterID          []string
		filterWorkspaceID []string
		filterName        []string
		filterDescription []string
		filterColor       []string
		filterArchived    []string
		sort              []string
		select_           []string
		expand            []string
		search            string
		page              int
		perPage           int
		count             bool
		cursor            string
		all               bool
	)
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List lists",
		Long: `A named list of tasks within a workspace.

GET /lists

A filter flag takes operator.value, or a bare value for equality, and repeating
one conjoins its conditions — a lower and an upper bound on the same column are
two occurrences of its flag.

Only the columns that declared a capability are reachable through it, so the
flags below are the complete list: a column absent from them cannot be
filtered, sorted or searched by any spelling.`,
		Example: `  # The first page, twenty rows at a time
  taskctl lists list --per-page 20

  # Conditions on one column conjoin; conditions on two intersect
  taskctl lists list --name contains.something

  # Ordered, and projected down to the columns about to be read
  taskctl lists list --sort -name --select id,workspace_id

  # Every matching row, walked by cursor rather than by page number
  taskctl lists list --all`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			q := url.Values{}
			for _, v := range filterID {
				q.Add("id", v)
			}
			for _, v := range filterWorkspaceID {
				q.Add("workspace_id", v)
			}
			for _, v := range filterName {
				q.Add("name", v)
			}
			for _, v := range filterDescription {
				q.Add("description", v)
			}
			for _, v := range filterColor {
				q.Add("color", v)
			}
			for _, v := range filterArchived {
				q.Add("archived", v)
			}
			if search != "" {
				q.Set("search", search)
			}
			if len(sort) > 0 {
				q.Set("sort", strings.Join(sort, ","))
			}
			if len(select_) > 0 {
				q.Set("select", strings.Join(select_, ","))
			}
			if len(expand) > 0 {
				q.Set("expand", strings.Join(expand, ","))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", strconv.Itoa(page))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", strconv.Itoa(perPage))
			}
			if count {
				q.Set("count", "exact")
			}
			if cursor != "" {
				q.Set("cursor", cursor)
			}
			if all && (cmd.Flags().Changed("page") || cursor != "") {
				return errors.New("--all walks the result set with cursors, so it cannot be combined with --page or --cursor")
			}
			return runRequest(c, cmd, client.Request{Method: http.MethodGet, Path: "/lists", Query: q}, all)
		},
	}
	flags := cmd.Flags()
	flags.StringArrayVar(&filterID, "id", nil,
		`Filter on id, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterWorkspaceID, "workspace-id", nil,
		`Filter on workspace_id, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterName, "name", nil,
		`Filter on name, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterDescription, "description", nil,
		`Filter on description, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterColor, "color", nil,
		`Filter on color, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterArchived, "archived", nil,
		`Filter on archived, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between.`)
	flags.StringSliceVar(&sort, "sort", nil,
		`Ordering, most significant first. Prefix a column with - for descending.
Columns: name, position, archived, created_at, updated_at.`)
	registerCompletion(cmd, "sort", []string{"name", "-name", "position", "-position", "archived", "-archived", "created_at", "-created_at", "updated_at", "-updated_at"})
	flags.StringSliceVar(&select_, "select", nil,
		`Columns to return; the primary key is always included. Omitted columns are
absent from the response rather than present and empty.
Columns: id, workspace_id, name, description, color, position, archived, created_at, updated_at, deleted_at.`)
	registerCompletion(cmd, "select", []string{"id", "workspace_id", "name", "description", "color", "position", "archived", "created_at", "updated_at", "deleted_at"})
	flags.StringSliceVar(&expand, "expand", nil,
		"Relations to embed in each row. Relations: tasks.")
	registerCompletion(cmd, "expand", []string{"tasks"})
	flags.StringVar(&search, "search", "",
		"Case-insensitive substring match, fanned out across name, description.")
	flags.IntVar(&page, "page", 1, "Page number, 1-based.")
	flags.IntVar(&perPage, "per-page", 0, `Rows per page. A value above the resource's ceiling is capped rather than
rejected.`)
	flags.BoolVar(&count, "count", false, `Include the total number of matching rows. It costs a second query, which is
why has_more is always present and this is not.`)
	flags.StringVar(&cursor, "cursor", "", `Resume after the next_cursor of a previous response. Cursor paging costs the
same at any depth and cannot skip or repeat a row when the table is written to
mid-walk, so prefer it to --page for anything that walks a whole result set. A
cursor is only valid for the --sort it was issued under.`)
	flags.BoolVar(&all, "all", false, `Follow next_cursor until the result set is exhausted and write every row as one
response. This is the loop a caller would otherwise write, and it pages by
cursor, so a concurrent insert cannot make it read a row twice.`)
	return cmd
}

// newListsGetCommand is GET /lists/{id}.
func newListsGetCommand(c *client.Client) *cobra.Command {
	var expand []string
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Fetch one list by primary key",
		Long: `GET /lists/{id}

The item endpoint declares no query parameters but expand, and rejects any
other rather than answering a question that was not asked.`,
		Example: `  taskctl lists get <id>

  # With tasks embedded, in one request
  taskctl lists get <id> --expand tasks`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			q := url.Values{}
			if len(expand) > 0 {
				q.Set("expand", strings.Join(expand, ","))
			}
			return runRequest(c, cmd, client.Request{Method: http.MethodGet, Path: client.ItemPath("/lists", args[0]), Query: q}, false)
		},
	}
	cmd.Flags().StringSliceVar(&expand, "expand", nil,
		"Relations to embed. Relations: tasks.")
	registerCompletion(cmd, "expand", []string{"tasks"})
	return cmd
}

// newListsCreateCommand is Post /lists.
func newListsCreateCommand(c *client.Client) *cobra.Command {
	var (
		valName        string
		valDescription string
		valColor       string
		valPosition    int32
		valArchived    bool
	)
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create one list",
		Args:  cobra.NoArgs,
		Long: `POST /lists

Read-only columns have no flag: the database or a BeforeCreate hook owns them,
so there is nothing for a caller to send. A column with a default is optional,
and leaving it out means the database supplies the value rather than the zero
value overwriting it.`,
		Example: "  taskctl lists create --name '<name>' --description '<description>'",
		RunE: func(cmd *cobra.Command, _ []string) error {
			body := map[string]any{}
			if cmd.Flags().Changed("name") {
				body["name"] = valName
			}
			if cmd.Flags().Changed("description") {
				body["description"] = valDescription
			}
			if cmd.Flags().Changed("color") {
				body["color"] = valColor
			}
			if cmd.Flags().Changed("position") {
				body["position"] = valPosition
			}
			if cmd.Flags().Changed("archived") {
				body["archived"] = valArchived
			}
			return runRequest(c, cmd, client.Request{Method: http.MethodPost, Path: "/lists", Body: body}, false)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&valName, "name", "",
		"Required.")
	_ = cmd.MarkFlagRequired("name")
	flags.StringVar(&valDescription, "description", "",
		"Required.")
	_ = cmd.MarkFlagRequired("description")
	flags.StringVar(&valColor, "color", "",
		"Optional; left out, the database supplies its default.")
	flags.Int32Var(&valPosition, "position", 0,
		"Optional; left out, the database supplies its default.")
	flags.BoolVar(&valArchived, "archived", false,
		"Optional; left out, the database supplies its default.")
	return cmd
}

// newListsUpdateCommand is Patch /lists/{id}.
func newListsUpdateCommand(c *client.Client) *cobra.Command {
	var (
		valName        string
		valDescription string
		valColor       string
		valPosition    int32
		valArchived    bool
	)
	cmd := &cobra.Command{
		Use:   "update <id>",
		Short: "Update one list by primary key",
		Args:  cobra.ExactArgs(1),
		Long: `PATCH /lists/{id}

Only the flags you pass are sent, so an update writes the columns it names and
no others — which is also why a flag left out and a flag set to an empty value
mean different things. Immutable columns have no flag here: they are settable
once, at create.`,
		Example: "  taskctl lists update <id> --name '<name>'",
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]any{}
			if cmd.Flags().Changed("name") {
				body["name"] = valName
			}
			if cmd.Flags().Changed("description") {
				body["description"] = valDescription
			}
			if cmd.Flags().Changed("color") {
				body["color"] = valColor
			}
			if cmd.Flags().Changed("position") {
				body["position"] = valPosition
			}
			if cmd.Flags().Changed("archived") {
				body["archived"] = valArchived
			}
			if len(body) == 0 {
				return errors.New("nothing to update: pass at least one field flag")
			}
			return runRequest(c, cmd, client.Request{Method: http.MethodPatch, Path: client.ItemPath("/lists", args[0]), Body: body}, false)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&valName, "name", "",
		"Sets name.")
	flags.StringVar(&valDescription, "description", "",
		"Sets description.")
	flags.StringVar(&valColor, "color", "",
		"Sets color.")
	flags.Int32Var(&valPosition, "position", 0,
		"Sets position.")
	flags.BoolVar(&valArchived, "archived", false,
		"Sets archived.")
	return cmd
}

// ------------------------------------------------------------- /memberships

// newMembershipsCommand groups the operations /memberships exposes.
func newMembershipsCommand(c *client.Client) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "memberships",
		Short: "A user's membership of a workspace, and their role in it",
	}
	cmd.AddCommand(newMembershipsListCommand(c))
	cmd.AddCommand(newMembershipsGetCommand(c))
	cmd.AddCommand(newMembershipsCreateCommand(c))
	cmd.AddCommand(newMembershipsDeleteCommand(c))
	return cmd
}

// newMembershipsListCommand is GET /memberships.
func newMembershipsListCommand(c *client.Client) *cobra.Command {
	var (
		filterID          []string
		filterWorkspaceID []string
		filterUserID      []string
		filterRole        []string
		sort              []string
		select_           []string
		page              int
		perPage           int
		count             bool
		cursor            string
		all               bool
	)
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List memberships",
		Long: `A user's membership of a workspace, and their role in it.

GET /memberships

A filter flag takes operator.value, or a bare value for equality, and repeating
one conjoins its conditions — a lower and an upper bound on the same column are
two occurrences of its flag.

Only the columns that declared a capability are reachable through it, so the
flags below are the complete list: a column absent from them cannot be
filtered, sorted or searched by any spelling.`,
		Example: `  # The first page, twenty rows at a time
  taskctl memberships list --per-page 20

  # Conditions on one column conjoin; conditions on two intersect
  taskctl memberships list --role eq.owner

  # Ordered, and projected down to the columns about to be read
  taskctl memberships list --sort -role --select id,workspace_id

  # Every matching row, walked by cursor rather than by page number
  taskctl memberships list --all`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			q := url.Values{}
			for _, v := range filterID {
				q.Add("id", v)
			}
			for _, v := range filterWorkspaceID {
				q.Add("workspace_id", v)
			}
			for _, v := range filterUserID {
				q.Add("user_id", v)
			}
			for _, v := range filterRole {
				q.Add("role", v)
			}
			if len(sort) > 0 {
				q.Set("sort", strings.Join(sort, ","))
			}
			if len(select_) > 0 {
				q.Set("select", strings.Join(select_, ","))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", strconv.Itoa(page))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", strconv.Itoa(perPage))
			}
			if count {
				q.Set("count", "exact")
			}
			if cursor != "" {
				q.Set("cursor", cursor)
			}
			if all && (cmd.Flags().Changed("page") || cursor != "") {
				return errors.New("--all walks the result set with cursors, so it cannot be combined with --page or --cursor")
			}
			return runRequest(c, cmd, client.Request{Method: http.MethodGet, Path: "/memberships", Query: q}, all)
		},
	}
	flags := cmd.Flags()
	flags.StringArrayVar(&filterID, "id", nil,
		`Filter on id, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterWorkspaceID, "workspace-id", nil,
		`Filter on workspace_id, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterUserID, "user-id", nil,
		`Filter on user_id, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterRole, "role", nil,
		`Filter on role, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.
Values: owner, admin, member.`)
	registerCompletion(cmd, "role", []string{"owner", "admin", "member", "eq.owner", "eq.admin", "eq.member"})
	flags.StringSliceVar(&sort, "sort", nil,
		`Ordering, most significant first. Prefix a column with - for descending.
Columns: role, created_at, updated_at.`)
	registerCompletion(cmd, "sort", []string{"role", "-role", "created_at", "-created_at", "updated_at", "-updated_at"})
	flags.StringSliceVar(&select_, "select", nil,
		`Columns to return; the primary key is always included. Omitted columns are
absent from the response rather than present and empty.
Columns: id, workspace_id, user_id, role, created_at, updated_at.`)
	registerCompletion(cmd, "select", []string{"id", "workspace_id", "user_id", "role", "created_at", "updated_at"})
	flags.IntVar(&page, "page", 1, "Page number, 1-based.")
	flags.IntVar(&perPage, "per-page", 0, `Rows per page. A value above the resource's ceiling is capped rather than
rejected.`)
	flags.BoolVar(&count, "count", false, `Include the total number of matching rows. It costs a second query, which is
why has_more is always present and this is not.`)
	flags.StringVar(&cursor, "cursor", "", `Resume after the next_cursor of a previous response. Cursor paging costs the
same at any depth and cannot skip or repeat a row when the table is written to
mid-walk, so prefer it to --page for anything that walks a whole result set. A
cursor is only valid for the --sort it was issued under.`)
	flags.BoolVar(&all, "all", false, `Follow next_cursor until the result set is exhausted and write every row as one
response. This is the loop a caller would otherwise write, and it pages by
cursor, so a concurrent insert cannot make it read a row twice.`)
	return cmd
}

// newMembershipsGetCommand is GET /memberships/{id}.
func newMembershipsGetCommand(c *client.Client) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Fetch one membership by primary key",
		Long: `GET /memberships/{id}

The item endpoint declares no query parameters but expand, and rejects any
other rather than answering a question that was not asked.`,
		Example: "  taskctl memberships get <id>",
		Args:    cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			q := url.Values{}
			return runRequest(c, cmd, client.Request{Method: http.MethodGet, Path: client.ItemPath("/memberships", args[0]), Query: q}, false)
		},
	}
	return cmd
}

// newMembershipsCreateCommand is Post /memberships.
func newMembershipsCreateCommand(c *client.Client) *cobra.Command {
	var (
		valUserID string
		valRole   string
	)
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create one membership",
		Args:  cobra.NoArgs,
		Long: `POST /memberships

Read-only columns have no flag: the database or a BeforeCreate hook owns them,
so there is nothing for a caller to send. A column with a default is optional,
and leaving it out means the database supplies the value rather than the zero
value overwriting it.`,
		Example: "  taskctl memberships create --user-id <user_id>",
		RunE: func(cmd *cobra.Command, _ []string) error {
			body := map[string]any{}
			if cmd.Flags().Changed("user-id") {
				body["user_id"] = valUserID
			}
			if cmd.Flags().Changed("role") {
				body["role"] = valRole
			}
			return runRequest(c, cmd, client.Request{Method: http.MethodPost, Path: "/memberships", Body: body}, false)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&valUserID, "user-id", "",
		"UUID. References users. Required.")
	_ = cmd.MarkFlagRequired("user-id")
	flags.StringVar(&valRole, "role", "",
		"One of: owner, admin, member. Optional; left out, the database supplies its default.")
	registerCompletion(cmd, "role", []string{"owner", "admin", "member"})
	return cmd
}

// newMembershipsDeleteCommand is DELETE /memberships/{id}.
func newMembershipsDeleteCommand(c *client.Client) *cobra.Command {
	return &cobra.Command{
		Use:   "delete <id>",
		Short: "Delete one membership by primary key",
		Long: `DELETE /memberships/{id}

A successful delete writes nothing: the response carries no body, so there is
nothing to print.`,
		Example: "  taskctl memberships delete <id>",
		Args:    cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			return runRequest(c, cmd, client.Request{Method: http.MethodDelete, Path: client.ItemPath("/memberships", args[0])}, false)
		},
	}
}

// ---------------------------------------------------------------- /profiles

// newProfilesCommand groups the operations /profiles exposes.
func newProfilesCommand(c *client.Client) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "profiles",
		Short: "A user's extended profile. One-to-one with users: user_id is unique",
	}
	cmd.AddCommand(newProfilesCreateCommand(c))
	return cmd
}

// newProfilesCreateCommand is Post /profiles.
func newProfilesCreateCommand(c *client.Client) *cobra.Command {
	var (
		valUserID string
		valBio    string
	)
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create one profile",
		Args:  cobra.NoArgs,
		Long: `POST /profiles

Read-only columns have no flag: the database or a BeforeCreate hook owns them,
so there is nothing for a caller to send. A column with a default is optional,
and leaving it out means the database supplies the value rather than the zero
value overwriting it.`,
		Example: "  taskctl profiles create --user-id <user_id>",
		RunE: func(cmd *cobra.Command, _ []string) error {
			body := map[string]any{}
			if cmd.Flags().Changed("user-id") {
				body["user_id"] = valUserID
			}
			if cmd.Flags().Changed("bio") {
				body["bio"] = valBio
			}
			return runRequest(c, cmd, client.Request{Method: http.MethodPost, Path: "/profiles", Body: body}, false)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&valUserID, "user-id", "",
		"UUID. References users. Required.")
	_ = cmd.MarkFlagRequired("user-id")
	flags.StringVar(&valBio, "bio", "",
		"Optional; left out, the column is null.")
	return cmd
}

// ------------------------------------------------------------------- /tasks

// newTasksCommand groups the operations /tasks exposes.
func newTasksCommand(c *client.Client) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "tasks",
		Short: "A unit of work, belonging to one list",
	}
	cmd.AddCommand(newTasksListCommand(c))
	cmd.AddCommand(newTasksGetCommand(c))
	cmd.AddCommand(newTasksCreateCommand(c))
	cmd.AddCommand(newTasksUpdateCommand(c))
	cmd.AddCommand(newTasksCompleteCommand(c))
	return cmd
}

// newTasksListCommand is GET /tasks.
func newTasksListCommand(c *client.Client) *cobra.Command {
	var (
		filterID           []string
		filterWorkspaceID  []string
		filterListID       []string
		filterAssigneeID   []string
		filterTitle        []string
		filterDescription  []string
		filterLabels       []string
		filterStatus       []string
		filterPriority     []string
		filterDueAt        []string
		filterCompletedAt  []string
		filterCommentCount []string
		sort               []string
		select_            []string
		expand             []string
		search             string
		page               int
		perPage            int
		count              bool
		cursor             string
		all                bool
	)
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List tasks",
		Long: `A unit of work, belonging to one list.

GET /tasks

A filter flag takes operator.value, or a bare value for equality, and repeating
one conjoins its conditions — a lower and an upper bound on the same column are
two occurrences of its flag.

Only the columns that declared a capability are reachable through it, so the
flags below are the complete list: a column absent from them cannot be
filtered, sorted or searched by any spelling.`,
		Example: `  # The first page, twenty rows at a time
  taskctl tasks list --per-page 20

  # Conditions on one column conjoin; conditions on two intersect
  taskctl tasks list --status eq.todo

  # Ordered, and projected down to the columns about to be read
  taskctl tasks list --sort -title --select id,workspace_id

  # Every matching row, walked by cursor rather than by page number
  taskctl tasks list --all`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			q := url.Values{}
			for _, v := range filterID {
				q.Add("id", v)
			}
			for _, v := range filterWorkspaceID {
				q.Add("workspace_id", v)
			}
			for _, v := range filterListID {
				q.Add("list_id", v)
			}
			for _, v := range filterAssigneeID {
				q.Add("assignee_id", v)
			}
			for _, v := range filterTitle {
				q.Add("title", v)
			}
			for _, v := range filterDescription {
				q.Add("description", v)
			}
			for _, v := range filterLabels {
				q.Add("labels", v)
			}
			for _, v := range filterStatus {
				q.Add("status", v)
			}
			for _, v := range filterPriority {
				q.Add("priority", v)
			}
			for _, v := range filterDueAt {
				q.Add("due_at", v)
			}
			for _, v := range filterCompletedAt {
				q.Add("completed_at", v)
			}
			for _, v := range filterCommentCount {
				q.Add("comment_count", v)
			}
			if search != "" {
				q.Set("search", search)
			}
			if len(sort) > 0 {
				q.Set("sort", strings.Join(sort, ","))
			}
			if len(select_) > 0 {
				q.Set("select", strings.Join(select_, ","))
			}
			if len(expand) > 0 {
				q.Set("expand", strings.Join(expand, ","))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", strconv.Itoa(page))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", strconv.Itoa(perPage))
			}
			if count {
				q.Set("count", "exact")
			}
			if cursor != "" {
				q.Set("cursor", cursor)
			}
			if all && (cmd.Flags().Changed("page") || cursor != "") {
				return errors.New("--all walks the result set with cursors, so it cannot be combined with --page or --cursor")
			}
			return runRequest(c, cmd, client.Request{Method: http.MethodGet, Path: "/tasks", Query: q}, all)
		},
	}
	flags := cmd.Flags()
	flags.StringArrayVar(&filterID, "id", nil,
		`Filter on id, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterWorkspaceID, "workspace-id", nil,
		`Filter on workspace_id, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterListID, "list-id", nil,
		`Filter on list_id, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterAssigneeID, "assignee-id", nil,
		`Filter on assignee_id, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, isnull, notnull, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterTitle, "title", nil,
		`Filter on title, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterDescription, "description", nil,
		`Filter on description, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterLabels, "labels", nil,
		`Free-form labels. Filter with has, hasany or hasall.
Filter on labels, an array column: written operator.value, or a bare
comma-separated list for whole-array equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, has, hasany, hasall, nhas, nhasany, nhasall.`)
	flags.StringArrayVar(&filterStatus, "status", nil,
		`Filter on status, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.
Values: todo, in_progress, blocked, done.`)
	registerCompletion(cmd, "status", []string{"todo", "in_progress", "blocked", "done", "eq.todo", "eq.in_progress", "eq.blocked", "eq.done"})
	flags.StringArrayVar(&filterPriority, "priority", nil,
		`Filter on priority, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.
Values: low, medium, high, urgent.`)
	registerCompletion(cmd, "priority", []string{"low", "medium", "high", "urgent", "eq.low", "eq.medium", "eq.high", "eq.urgent"})
	flags.StringArrayVar(&filterDueAt, "due-at", nil,
		`Filter on due_at, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, isnull, notnull.`)
	flags.StringArrayVar(&filterCompletedAt, "completed-at", nil,
		`Filter on completed_at, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, isnull, notnull.`)
	flags.StringArrayVar(&filterCommentCount, "comment-count", nil,
		`Filter on comment_count, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between.`)
	flags.StringSliceVar(&sort, "sort", nil,
		`Ordering, most significant first. Prefix a column with - for descending.
Columns: title, status, priority, due_at, completed_at, position, comment_count, created_at, updated_at.`)
	registerCompletion(cmd, "sort", []string{"title", "-title", "status", "-status", "priority", "-priority", "due_at", "-due_at", "completed_at", "-completed_at", "position", "-position", "comment_count", "-comment_count", "created_at", "-created_at", "updated_at", "-updated_at"})
	flags.StringSliceVar(&select_, "select", nil,
		`Columns to return; the primary key is always included. Omitted columns are
absent from the response rather than present and empty.
Columns: id, workspace_id, list_id, assignee_id, author_id, title, description, labels, status, priority, due_at, completed_at, position, comment_count, created_at, updated_at, deleted_at.`)
	registerCompletion(cmd, "select", []string{"id", "workspace_id", "list_id", "assignee_id", "author_id", "title", "description", "labels", "status", "priority", "due_at", "completed_at", "position", "comment_count", "created_at", "updated_at", "deleted_at"})
	flags.StringSliceVar(&expand, "expand", nil,
		"Relations to embed in each row. Relations: list.")
	registerCompletion(cmd, "expand", []string{"list"})
	flags.StringVar(&search, "search", "",
		"Case-insensitive substring match, fanned out across title, description.")
	flags.IntVar(&page, "page", 1, "Page number, 1-based.")
	flags.IntVar(&perPage, "per-page", 0, `Rows per page. A value above the resource's ceiling is capped rather than
rejected.`)
	flags.BoolVar(&count, "count", false, `Include the total number of matching rows. It costs a second query, which is
why has_more is always present and this is not.`)
	flags.StringVar(&cursor, "cursor", "", `Resume after the next_cursor of a previous response. Cursor paging costs the
same at any depth and cannot skip or repeat a row when the table is written to
mid-walk, so prefer it to --page for anything that walks a whole result set. A
cursor is only valid for the --sort it was issued under.`)
	flags.BoolVar(&all, "all", false, `Follow next_cursor until the result set is exhausted and write every row as one
response. This is the loop a caller would otherwise write, and it pages by
cursor, so a concurrent insert cannot make it read a row twice.`)
	return cmd
}

// newTasksGetCommand is GET /tasks/{id}.
func newTasksGetCommand(c *client.Client) *cobra.Command {
	var expand []string
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Fetch one task by primary key",
		Long: `GET /tasks/{id}

The item endpoint declares no query parameters but expand, and rejects any
other rather than answering a question that was not asked.`,
		Example: `  taskctl tasks get <id>

  # With list embedded, in one request
  taskctl tasks get <id> --expand list`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			q := url.Values{}
			if len(expand) > 0 {
				q.Set("expand", strings.Join(expand, ","))
			}
			return runRequest(c, cmd, client.Request{Method: http.MethodGet, Path: client.ItemPath("/tasks", args[0]), Query: q}, false)
		},
	}
	cmd.Flags().StringSliceVar(&expand, "expand", nil,
		"Relations to embed. Relations: list.")
	registerCompletion(cmd, "expand", []string{"list"})
	return cmd
}

// newTasksCreateCommand is Post /tasks.
func newTasksCreateCommand(c *client.Client) *cobra.Command {
	var (
		valListID      string
		valAssigneeID  string
		valTitle       string
		valDescription string
		valLabels      string
		valStatus      string
		valPriority    string
		valDueAt       string
		valPosition    int32
	)
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create one task",
		Args:  cobra.NoArgs,
		Long: `POST /tasks

Read-only columns have no flag: the database or a BeforeCreate hook owns them,
so there is nothing for a caller to send. A column with a default is optional,
and leaving it out means the database supplies the value rather than the zero
value overwriting it.`,
		Example: "  taskctl tasks create --list-id <list_id> --title '<title>' --description '<description>'",
		RunE: func(cmd *cobra.Command, _ []string) error {
			body := map[string]any{}
			if cmd.Flags().Changed("list-id") {
				body["list_id"] = valListID
			}
			if cmd.Flags().Changed("assignee-id") {
				body["assignee_id"] = valAssigneeID
			}
			if cmd.Flags().Changed("title") {
				body["title"] = valTitle
			}
			if cmd.Flags().Changed("description") {
				body["description"] = valDescription
			}
			if cmd.Flags().Changed("labels") {
				body["labels"] = valLabels
			}
			if cmd.Flags().Changed("status") {
				body["status"] = valStatus
			}
			if cmd.Flags().Changed("priority") {
				body["priority"] = valPriority
			}
			if cmd.Flags().Changed("due-at") {
				body["due_at"] = valDueAt
			}
			if cmd.Flags().Changed("position") {
				body["position"] = valPosition
			}
			return runRequest(c, cmd, client.Request{Method: http.MethodPost, Path: "/tasks", Body: body}, false)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&valListID, "list-id", "",
		"UUID. References lists. Required.")
	_ = cmd.MarkFlagRequired("list-id")
	flags.StringVar(&valAssigneeID, "assignee-id", "",
		"UUID. References users. Optional; left out, the column is null.")
	flags.StringVar(&valTitle, "title", "",
		"Required.")
	_ = cmd.MarkFlagRequired("title")
	flags.StringVar(&valDescription, "description", "",
		"Required.")
	_ = cmd.MarkFlagRequired("description")
	flags.StringVar(&valLabels, "labels", "",
		"Free-form labels. Filter with has, hasany or hasall. Optional; left out, the database supplies its default.")
	flags.StringVar(&valStatus, "status", "",
		"One of: todo, in_progress, blocked, done. Optional; left out, the database supplies its default.")
	registerCompletion(cmd, "status", []string{"todo", "in_progress", "blocked", "done"})
	flags.StringVar(&valPriority, "priority", "",
		"One of: low, medium, high, urgent. Optional; left out, the database supplies its default.")
	registerCompletion(cmd, "priority", []string{"low", "medium", "high", "urgent"})
	flags.StringVar(&valDueAt, "due-at", "",
		"RFC 3339 timestamp, e.g. 2026-07-28T09:00:00Z. Optional; left out, the column is null.")
	flags.Int32Var(&valPosition, "position", 0,
		"Optional; left out, the database supplies its default.")
	return cmd
}

// newTasksUpdateCommand is Patch /tasks/{id}.
func newTasksUpdateCommand(c *client.Client) *cobra.Command {
	var (
		valListID      string
		valAssigneeID  string
		valTitle       string
		valDescription string
		valLabels      string
		valStatus      string
		valPriority    string
		valDueAt       string
		valPosition    int32
		setNull        []string
	)
	cmd := &cobra.Command{
		Use:   "update <id>",
		Short: "Update one task by primary key",
		Args:  cobra.ExactArgs(1),
		Long: `PATCH /tasks/{id}

Only the flags you pass are sent, so an update writes the columns it names and
no others — which is also why a flag left out and a flag set to an empty value
mean different things. Immutable columns have no flag here: they are settable
once, at create.`,
		Example: `  taskctl tasks update <id> --status todo

  # Back to null, which no value flag can say
  taskctl tasks update <id> --set-null assignee_id`,
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]any{}
			if cmd.Flags().Changed("list-id") {
				body["list_id"] = valListID
			}
			if cmd.Flags().Changed("assignee-id") {
				body["assignee_id"] = valAssigneeID
			}
			if cmd.Flags().Changed("title") {
				body["title"] = valTitle
			}
			if cmd.Flags().Changed("description") {
				body["description"] = valDescription
			}
			if cmd.Flags().Changed("labels") {
				body["labels"] = valLabels
			}
			if cmd.Flags().Changed("status") {
				body["status"] = valStatus
			}
			if cmd.Flags().Changed("priority") {
				body["priority"] = valPriority
			}
			if cmd.Flags().Changed("due-at") {
				body["due_at"] = valDueAt
			}
			if cmd.Flags().Changed("position") {
				body["position"] = valPosition
			}
			if err := setNullFields(body, setNull, []nullableColumn{{"assignee_id", "assignee_id"}, {"due_at", "due_at"}}); err != nil {
				return err
			}
			if len(body) == 0 {
				return errors.New("nothing to update: pass at least one field flag")
			}
			return runRequest(c, cmd, client.Request{Method: http.MethodPatch, Path: client.ItemPath("/tasks", args[0]), Body: body}, false)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&valListID, "list-id", "",
		"UUID. References lists.")
	flags.StringVar(&valAssigneeID, "assignee-id", "",
		"UUID. References users.")
	flags.StringVar(&valTitle, "title", "",
		"Sets title.")
	flags.StringVar(&valDescription, "description", "",
		"Sets description.")
	flags.StringVar(&valLabels, "labels", "",
		"Free-form labels. Filter with has, hasany or hasall.")
	flags.StringVar(&valStatus, "status", "",
		"One of: todo, in_progress, blocked, done.")
	registerCompletion(cmd, "status", []string{"todo", "in_progress", "blocked", "done"})
	flags.StringVar(&valPriority, "priority", "",
		"One of: low, medium, high, urgent.")
	registerCompletion(cmd, "priority", []string{"low", "medium", "high", "urgent"})
	flags.StringVar(&valDueAt, "due-at", "",
		"RFC 3339 timestamp, e.g. 2026-07-28T09:00:00Z.")
	flags.Int32Var(&valPosition, "position", 0,
		"Sets position.")
	flags.StringArrayVar(&setNull, "set-null", nil,
		`Set a column to null, which no value flag can express. Repeatable.
Columns: assignee_id, due_at.`)
	registerCompletion(cmd, "set-null", []string{"assignee_id", "due_at"})
	return cmd
}

// newTasksCompleteCommand is POST /tasks/{id}/complete.
func newTasksCompleteCommand(c *client.Client) *cobra.Command {
	var (
		valNote string
	)
	cmd := &cobra.Command{
		Use:   "complete <id>",
		Short: "Complete a task",
		Long: `POST /tasks/{id}/complete

Marks the task done and stamps its completion time. A task that is already done is refused with a 409.

A verb on one row. The server fetches it and runs the transition.
It answers with the row as it now stands.

The response row carries status, completed_at, and no other column the server changed on it.

Beyond that row the route writes: comments.
The schema declares that set; nothing enforces it.`,
		Example: "  taskctl tasks complete <id>",
		Args:    cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			body := map[string]any{}
			if cmd.Flags().Changed("note") {
				body["note"] = valNote
			}
			return runRequest(c, cmd, client.Request{Method: http.MethodPost, Path: client.ItemPath("/tasks", args[0]) + "/complete", Body: body}, false)
		},
	}
	flags := cmd.Flags()
	flags.StringVar(&valNote, "note", "",
		"Recorded as a comment on the task, in the same transaction. Optional.")
	return cmd
}

// ------------------------------------------------------------------- /users

// newUsersCommand groups the operations /users exposes.
func newUsersCommand(c *client.Client) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "users",
		Short: "Work with users",
	}
	cmd.AddCommand(newUsersListCommand(c))
	cmd.AddCommand(newUsersGetCommand(c))
	return cmd
}

// newUsersListCommand is GET /users.
func newUsersListCommand(c *client.Client) *cobra.Command {
	var (
		filterID    []string
		filterEmail []string
		filterName  []string
		sort        []string
		select_     []string
		expand      []string
		search      string
		page        int
		perPage     int
		count       bool
		cursor      string
		all         bool
	)
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List users",
		Long: `GET /users

A filter flag takes operator.value, or a bare value for equality, and repeating
one conjoins its conditions — a lower and an upper bound on the same column are
two occurrences of its flag.

Only the columns that declared a capability are reachable through it, so the
flags below are the complete list: a column absent from them cannot be
filtered, sorted or searched by any spelling.`,
		Example: `  # The first page, twenty rows at a time
  taskctl users list --per-page 20

  # Conditions on one column conjoin; conditions on two intersect
  taskctl users list --email contains.something

  # Ordered, and projected down to the columns about to be read
  taskctl users list --sort -name --select id,email

  # Every matching row, walked by cursor rather than by page number
  taskctl users list --all`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			q := url.Values{}
			for _, v := range filterID {
				q.Add("id", v)
			}
			for _, v := range filterEmail {
				q.Add("email", v)
			}
			for _, v := range filterName {
				q.Add("name", v)
			}
			if search != "" {
				q.Set("search", search)
			}
			if len(sort) > 0 {
				q.Set("sort", strings.Join(sort, ","))
			}
			if len(select_) > 0 {
				q.Set("select", strings.Join(select_, ","))
			}
			if len(expand) > 0 {
				q.Set("expand", strings.Join(expand, ","))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", strconv.Itoa(page))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", strconv.Itoa(perPage))
			}
			if count {
				q.Set("count", "exact")
			}
			if cursor != "" {
				q.Set("cursor", cursor)
			}
			if all && (cmd.Flags().Changed("page") || cursor != "") {
				return errors.New("--all walks the result set with cursors, so it cannot be combined with --page or --cursor")
			}
			return runRequest(c, cmd, client.Request{Method: http.MethodGet, Path: "/users", Query: q}, all)
		},
	}
	flags := cmd.Flags()
	flags.StringArrayVar(&filterID, "id", nil,
		`Filter on id, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterEmail, "email", nil,
		`Filter on email, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterName, "name", nil,
		`Filter on name, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringSliceVar(&sort, "sort", nil,
		`Ordering, most significant first. Prefix a column with - for descending.
Columns: name, created_at, updated_at.`)
	registerCompletion(cmd, "sort", []string{"name", "-name", "created_at", "-created_at", "updated_at", "-updated_at"})
	flags.StringSliceVar(&select_, "select", nil,
		`Columns to return; the primary key is always included. Omitted columns are
absent from the response rather than present and empty.
Columns: id, email, name, created_at, updated_at.`)
	registerCompletion(cmd, "select", []string{"id", "email", "name", "created_at", "updated_at"})
	flags.StringSliceVar(&expand, "expand", nil,
		"Relations to embed in each row. Relations: profile.")
	registerCompletion(cmd, "expand", []string{"profile"})
	flags.StringVar(&search, "search", "",
		"Case-insensitive substring match, fanned out across email, name.")
	flags.IntVar(&page, "page", 1, "Page number, 1-based.")
	flags.IntVar(&perPage, "per-page", 0, `Rows per page. A value above the resource's ceiling is capped rather than
rejected.`)
	flags.BoolVar(&count, "count", false, `Include the total number of matching rows. It costs a second query, which is
why has_more is always present and this is not.`)
	flags.StringVar(&cursor, "cursor", "", `Resume after the next_cursor of a previous response. Cursor paging costs the
same at any depth and cannot skip or repeat a row when the table is written to
mid-walk, so prefer it to --page for anything that walks a whole result set. A
cursor is only valid for the --sort it was issued under.`)
	flags.BoolVar(&all, "all", false, `Follow next_cursor until the result set is exhausted and write every row as one
response. This is the loop a caller would otherwise write, and it pages by
cursor, so a concurrent insert cannot make it read a row twice.`)
	return cmd
}

// newUsersGetCommand is GET /users/{id}.
func newUsersGetCommand(c *client.Client) *cobra.Command {
	var expand []string
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Fetch one user by primary key",
		Long: `GET /users/{id}

The item endpoint declares no query parameters but expand, and rejects any
other rather than answering a question that was not asked.`,
		Example: `  taskctl users get <id>

  # With profile embedded, in one request
  taskctl users get <id> --expand profile`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			q := url.Values{}
			if len(expand) > 0 {
				q.Set("expand", strings.Join(expand, ","))
			}
			return runRequest(c, cmd, client.Request{Method: http.MethodGet, Path: client.ItemPath("/users", args[0]), Query: q}, false)
		},
	}
	cmd.Flags().StringSliceVar(&expand, "expand", nil,
		"Relations to embed. Relations: profile.")
	registerCompletion(cmd, "expand", []string{"profile"})
	return cmd
}

// -------------------------------------------------------------- /workspaces

// newWorkspacesCommand groups the operations /workspaces exposes.
func newWorkspacesCommand(c *client.Client) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "workspaces",
		Short: "A tenant. Lists, tasks and comments all belong to exactly one",
	}
	cmd.AddCommand(newWorkspacesListCommand(c))
	cmd.AddCommand(newWorkspacesGetCommand(c))
	return cmd
}

// newWorkspacesListCommand is GET /workspaces.
func newWorkspacesListCommand(c *client.Client) *cobra.Command {
	var (
		filterID   []string
		filterName []string
		filterSlug []string
		sort       []string
		select_    []string
		search     string
		page       int
		perPage    int
		count      bool
		cursor     string
		all        bool
	)
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List workspaces",
		Long: `A tenant. Lists, tasks and comments all belong to exactly one.

GET /workspaces

A filter flag takes operator.value, or a bare value for equality, and repeating
one conjoins its conditions — a lower and an upper bound on the same column are
two occurrences of its flag.

Only the columns that declared a capability are reachable through it, so the
flags below are the complete list: a column absent from them cannot be
filtered, sorted or searched by any spelling.`,
		Example: `  # The first page, twenty rows at a time
  taskctl workspaces list --per-page 20

  # Conditions on one column conjoin; conditions on two intersect
  taskctl workspaces list --name contains.something

  # Ordered, and projected down to the columns about to be read
  taskctl workspaces list --sort -name --select id,name

  # Every matching row, walked by cursor rather than by page number
  taskctl workspaces list --all`,
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			q := url.Values{}
			for _, v := range filterID {
				q.Add("id", v)
			}
			for _, v := range filterName {
				q.Add("name", v)
			}
			for _, v := range filterSlug {
				q.Add("slug", v)
			}
			if search != "" {
				q.Set("search", search)
			}
			if len(sort) > 0 {
				q.Set("sort", strings.Join(sort, ","))
			}
			if len(select_) > 0 {
				q.Set("select", strings.Join(select_, ","))
			}
			if cmd.Flags().Changed("page") {
				q.Set("page", strconv.Itoa(page))
			}
			if cmd.Flags().Changed("per-page") {
				q.Set("per_page", strconv.Itoa(perPage))
			}
			if count {
				q.Set("count", "exact")
			}
			if cursor != "" {
				q.Set("cursor", cursor)
			}
			if all && (cmd.Flags().Changed("page") || cursor != "") {
				return errors.New("--all walks the result set with cursors, so it cannot be combined with --page or --cursor")
			}
			return runRequest(c, cmd, client.Request{Method: http.MethodGet, Path: "/workspaces", Query: q}, all)
		},
	}
	flags := cmd.Flags()
	flags.StringArrayVar(&filterID, "id", nil,
		`Filter on id, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterName, "name", nil,
		`Filter on name, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringArrayVar(&filterSlug, "slug", nil,
		`Filter on slug, written operator.value, or a bare value for equality.
Repeat the flag to conjoin conditions. Operators: eq, ne, gt, gte, lt, lte, in, nin, between, like, ilike, contains, startswith, endswith.`)
	flags.StringSliceVar(&sort, "sort", nil,
		`Ordering, most significant first. Prefix a column with - for descending.
Columns: name, created_at, updated_at.`)
	registerCompletion(cmd, "sort", []string{"name", "-name", "created_at", "-created_at", "updated_at", "-updated_at"})
	flags.StringSliceVar(&select_, "select", nil,
		`Columns to return; the primary key is always included. Omitted columns are
absent from the response rather than present and empty.
Columns: id, name, slug, created_at, updated_at.`)
	registerCompletion(cmd, "select", []string{"id", "name", "slug", "created_at", "updated_at"})
	flags.StringVar(&search, "search", "",
		"Case-insensitive substring match, fanned out across name.")
	flags.IntVar(&page, "page", 1, "Page number, 1-based.")
	flags.IntVar(&perPage, "per-page", 0, `Rows per page. A value above the resource's ceiling is capped rather than
rejected.`)
	flags.BoolVar(&count, "count", false, `Include the total number of matching rows. It costs a second query, which is
why has_more is always present and this is not.`)
	flags.StringVar(&cursor, "cursor", "", `Resume after the next_cursor of a previous response. Cursor paging costs the
same at any depth and cannot skip or repeat a row when the table is written to
mid-walk, so prefer it to --page for anything that walks a whole result set. A
cursor is only valid for the --sort it was issued under.`)
	flags.BoolVar(&all, "all", false, `Follow next_cursor until the result set is exhausted and write every row as one
response. This is the loop a caller would otherwise write, and it pages by
cursor, so a concurrent insert cannot make it read a row twice.`)
	return cmd
}

// newWorkspacesGetCommand is GET /workspaces/{id}.
func newWorkspacesGetCommand(c *client.Client) *cobra.Command {
	cmd := &cobra.Command{
		Use:   "get <id>",
		Short: "Fetch one workspace by primary key",
		Long: `GET /workspaces/{id}

The item endpoint declares no query parameters but expand, and rejects any
other rather than answering a question that was not asked.`,
		Example: "  taskctl workspaces get <id>",
		Args:    cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			q := url.Values{}
			return runRequest(c, cmd, client.Request{Method: http.MethodGet, Path: client.ItemPath("/workspaces", args[0]), Query: q}, false)
		},
	}
	return cmd
}
