// Code generated by github.com/mind-vm/sqlb. DO NOT EDIT.

package outbox

import (
	"encoding/json"
	"time"

	"github.com/mind-vm/sqlb"
)

type outboxEventColumns struct {
	ID          sqlb.Col[int64]
	Topic       sqlb.TextCol[string]
	Payload     sqlb.Col[json.RawMessage]
	Status      sqlb.Col[OutboxEventStatus]
	Attempts    sqlb.Col[int32]
	MaxAttempts sqlb.Col[int32]
	AvailableAt sqlb.Col[time.Time]
	CreatedAt   sqlb.Col[time.Time]
	UpdatedAt   sqlb.Col[time.Time]
}

// OutboxEventCols are the typed columns of outbox_events.
var OutboxEventCols = outboxEventColumns{
	ID:          sqlb.Typed[int64]("id"),
	Topic:       sqlb.TextColumn[string]("topic"),
	Payload:     sqlb.Typed[json.RawMessage]("payload"),
	Status:      sqlb.Typed[OutboxEventStatus]("status"),
	Attempts:    sqlb.Typed[int32]("attempts"),
	MaxAttempts: sqlb.Typed[int32]("max_attempts"),
	AvailableAt: sqlb.Typed[time.Time]("available_at"),
	CreatedAt:   sqlb.Typed[time.Time]("created_at"),
	UpdatedAt:   sqlb.Typed[time.Time]("updated_at"),
}

// OutboxEventUpdate is a typed update statement for outbox_events.
type OutboxEventUpdate struct {
	stmt *sqlb.Update[OutboxEvent]
}

// UpdateOutboxEvent starts a typed update.
func UpdateOutboxEvent() *OutboxEventUpdate {
	return &OutboxEventUpdate{stmt: sqlb.UpdateRows[OutboxEvent]()}
}

// SetTopic sets topic.
func (u *OutboxEventUpdate) SetTopic(v string) *OutboxEventUpdate {
	u.stmt.Set("topic", v)
	return u
}

// SetPayload sets payload.
func (u *OutboxEventUpdate) SetPayload(v json.RawMessage) *OutboxEventUpdate {
	u.stmt.Set("payload", v)
	return u
}

// SetStatus sets status.
func (u *OutboxEventUpdate) SetStatus(v OutboxEventStatus) *OutboxEventUpdate {
	u.stmt.Set("status", v)
	return u
}

// SetAttempts sets attempts.
func (u *OutboxEventUpdate) SetAttempts(v int32) *OutboxEventUpdate {
	u.stmt.Set("attempts", v)
	return u
}

// SetMaxAttempts sets max_attempts.
func (u *OutboxEventUpdate) SetMaxAttempts(v int32) *OutboxEventUpdate {
	u.stmt.Set("max_attempts", v)
	return u
}

// SetAvailableAt sets available_at.
func (u *OutboxEventUpdate) SetAvailableAt(v time.Time) *OutboxEventUpdate {
	u.stmt.Set("available_at", v)
	return u
}

// SetCreatedAt sets created_at.
func (u *OutboxEventUpdate) SetCreatedAt(v time.Time) *OutboxEventUpdate {
	u.stmt.Set("created_at", v)
	return u
}

// SetUpdatedAt sets updated_at.
func (u *OutboxEventUpdate) SetUpdatedAt(v time.Time) *OutboxEventUpdate {
	u.stmt.Set("updated_at", v)
	return u
}

// Where narrows the affected rows.
func (u *OutboxEventUpdate) Where(preds ...sqlb.Pred) *OutboxEventUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *OutboxEventUpdate) Stmt() *sqlb.Update[OutboxEvent] { return u.stmt }
