// Code generated by github.com/mind-vm/sqlb. DO NOT EDIT.

package outbox

import (
	"encoding/json"
	"time"
)

// OutboxEventStatus is the outbox_events.status column's value set.
type OutboxEventStatus string

const (
	OutboxEventStatusPending    OutboxEventStatus = "pending"
	OutboxEventStatusProcessing OutboxEventStatus = "processing"
	OutboxEventStatusDone       OutboxEventStatus = "done"
	OutboxEventStatusDead       OutboxEventStatus = "dead"
)

// OutboxEvent is a row of outbox_events.
type OutboxEvent struct {
	ID          int64             `db:"id" json:"id" sqlb:"type:bigint,pk,default,filter,readonly"`
	Topic       string            `db:"topic" json:"topic" sqlb:"type:text,filter"`
	Payload     json.RawMessage   `db:"payload" json:"payload" sqlb:"type:jsonb"`
	Status      OutboxEventStatus `db:"status" json:"status" sqlb:"type:enum,default,filter"`
	Attempts    int32             `db:"attempts" json:"attempts" sqlb:"type:int,default,filter"`
	MaxAttempts int32             `db:"max_attempts" json:"max_attempts" sqlb:"type:int,default"`
	AvailableAt time.Time         `db:"available_at" json:"available_at" sqlb:"type:timestamptz,default,filter"`
	CreatedAt   time.Time         `db:"created_at" json:"created_at" sqlb:"type:timestamptz,default,sort,readonly"`
	UpdatedAt   time.Time         `db:"updated_at" json:"updated_at" sqlb:"type:timestamptz,default,sort,readonly"`
}

// TableName is the table OutboxEvent maps to.
func (OutboxEvent) TableName() string { return "outbox_events" }
