package codegen

// `sqlb check -database` asks the question `sqlb check` could not: does the
// declaration still describe the table the database actually has?
//
// Without it, check compares committed output against the declaration and never
// opens a database — so pointing it at a dead one still passes, and nothing in
// the toolchain verifies that the schema a project calls its single source of
// truth is still true (issue #54). Between a hand-edited migration, a hotfix
// applied by someone with psql open, and a column added by another service, a
// declaration drifts from its database silently and stays wrong until the day a
// generated statement names a column that is not there.
//
// # What it compares
//
// Only the tables the schema declares. An incremental adoption declares a
// handful while the database holds dozens, and diffing five tables against
// sixty-nine would report the other sixty-four as tables to drop — which is not
// drift, it is the adoption working as intended. So the introspection is
// narrowed to the declared names, and a declared table the database does not
// have shows up as the create it is.
//
// # What it costs the database
//
// One catalog read, and — for a schema with CHECK constraints — one ADD
// CONSTRAINT … NOT VALID per check inside a transaction that is always rolled
// back. NOT VALID means no table scan, so the probe is a catalog write and a
// brief lock rather than a read of every row. Postgres stores a check as a
// parse tree and hands back its own spelling, so without that probe every check
// in the schema reads as drift forever (issue #24, and Diff's own doc comment).
//
// # Migration provenance
//
// The base `check` — no -database needed — also scans committed migration
// files for a gap between the two halves above: a file can carry sqlb's
// "Generated by sqlb" header and have had DDL pasted into it that neither half
// would ever see. check -database only catches an edit once it has reached a
// database being pointed at, and only when it changes something the schema
// declares; a CREATE TRIGGER does neither. See checkMigrationProvenance and
// issue #178.

import (
	"context"
	"flag"
	"io"
	"strings"

	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/mind-vm/sqlb"
	"github.com/mind-vm/sqlb/introspect"
	"github.com/mind-vm/sqlb/migrate"
	"github.com/mind-vm/sqlb/schema"
	"github.com/mind-vm/sqlb/shadow"
)

// runCheck is the driver's `check` verb: report stale generated files, and —
// with -database — report a declaration that no longer describes the database.
func runCheck(p Project, opts Options, args []string, stdout, stderr io.Writer) int {
	fs := flag.NewFlagSet("sqlb check", flag.ContinueOnError)
	fs.SetOutput(stderr)
	dsn := fs.String("database", "",
		"also compare the declared schema against this live database, and fail on drift")
	lint := fs.String("lint", string(lintSummary), lintLevelUsage)
	if err := fs.Parse(args); err != nil {
		return 2
	}
	if fs.NArg() > 0 {
		say(stderr, "sqlb: check takes no positional arguments, got %q\n", fs.Arg(0))
		return 2
	}
	level, err := parseLintLevel(*lint)
	if err != nil {
		say(stderr, "sqlb: %v\n", err)
		return 2
	}

	// What follows is ordered advice first, verdicts last, because check
	// answers two different questions in one stream and only one of them is
	// the reason anybody ran it (#267). Every failure is recorded here rather
	// than printed where it is found, so the command can close with a line
	// that says what its exit code means — the property that makes the answer
	// findable however long the advisory block above it grows.
	var failures []string
	stale, err := Check(opts)
	if err != nil {
		line(stderr, err)
		return 1
	}

	// Lint answers a different question than staleness or drift: not "is this
	// wrong" but "will this behave badly in production" (schema/lint.go).
	// Advisory by the same rule the introspection report and the unprobed-check
	// list already follow — printed, never added to the exit code — because
	// #201 found the cost of silence here is real (every one of sixteen tables
	// in a port carried the same unflagged mistake) but a schema can have a
	// good reason to keep any one diagnostic, and a gate that cannot be right
	// about that should not fail the build over it.
	diags := opts.Registry.Lint()
	if listed := level.listed(diags); len(listed) > 0 {
		line(stderr, "sqlb: lint found:")
		line(stderr, listed)
	}

	// A database is not needed for this one: it is a textual scan of the
	// migration files already on disk, so it belongs in the fast half of
	// check alongside the generated-file comparison, not gated behind
	// -database.
	if p.MigrationsDir != "" {
		violations, err := checkMigrationProvenance(p.MigrationsDir)
		if err != nil {
			line(stderr, err)
			return 1
		}
		if len(violations) > 0 {
			line(stderr, "sqlb: these migration files carry sqlb's header but contain DDL sqlb "+
				"never emits, so the header's claim cannot be trusted (issue #178):")
			for _, v := range violations {
				line(stderr, "  "+v.String())
			}
			line(stderr, "sqlb: if the file is genuinely hand-composed, remove the header line — "+
				"or render it with migrate.Options{Handwritten: true} so it never gets one")
			failures = append(failures, "a migration file's sqlb header cannot be trusted")
		}
	}

	if summary := level.summary(diags); summary != "" {
		line(stderr, summary)
	}

	if len(stale) > 0 {
		// Naming the command that fixes it matters more here than anywhere else
		// in sqlb: this message is read almost exclusively out of a CI log, by
		// someone who is not in the directory and has no idea what the
		// generator was called.
		line(stderr, "sqlb: generated files are out of date; run: sqlb generate")
		for _, f := range stale {
			line(stderr, "  "+f)
		}
		failures = append(failures, "generated files are out of date")
	} else {
		line(stderr, "sqlb: generated files are current")
	}

	if *dsn != "" {
		if failure := checkDrift(p, opts, *dsn, stdout, stderr); failure != "" {
			failures = append(failures, failure)
		}
	}

	// The last line, always, whatever was printed above it and however much of
	// it there was.
	if len(failures) > 0 {
		say(stderr, "sqlb: check failed: %s\n", strings.Join(failures, "; "))
		return 1
	}
	line(stderr, "sqlb: check passed")
	return 0
}

// checkDrift compares the declared schema against a live database. It returns
// the reason the check failed, or "" when the two agree — the caller collects
// those into check's closing line rather than each half printing its own
// verdict wherever it happens to finish (#267).
func checkDrift(p Project, opts Options, dsn string, stdout, stderr io.Writer) string {
	ctx := context.Background()

	pool, err := pgxpool.New(ctx, dsn)
	if err != nil {
		say(stderr, "sqlb: connecting to the database: %v\n", err)
		return "the database could not be reached"
	}
	defer pool.Close()

	declared := opts.Registry
	current, rep, err := introspect.Registry(ctx, sqlb.New(pool), introspect.Options{
		Schema: p.PostgresSchema,
		Module: p.Module,
		Only:   declaredTableNames(declared),
	})
	if err != nil {
		say(stderr, "sqlb: reading the database: %v\n", err)
		return "the database could not be read"
	}
	// The report is what the database has and this package cannot describe. It
	// is not drift — nothing here is wrong — but a gate that silently skipped
	// it would be claiming to have checked something it never looked at.
	if !rep.Empty() {
		line(stderr, "sqlb: the database has constructs the schema DSL cannot describe, "+
			"and they were not compared:")
		line(stderr, rep)
	}

	// Both sides have to spell their checks the way Postgres does, or every
	// check in the schema reads as drift.
	if unprobed, err := shadow.Normalize(ctx, pool, declared, shadow.Options{
		Schema: p.PostgresSchema,
	}); err != nil {
		say(stderr, "sqlb: normalising the declared checks: %v\n", err)
		return "the declared checks could not be normalised"
	} else if len(unprobed) > 0 {
		line(stderr, "sqlb: these checks could not be normalised, so they are compared as written:")
		for _, u := range unprobed {
			line(stderr, "  "+u)
		}
	}

	var diffOpts []migrate.Option
	if p.MinPostgres > 0 {
		diffOpts = append(diffOpts, migrate.MinPostgres(p.MinPostgres))
	}
	changes, err := migrate.Diff(current, declared, diffOpts...)
	if err != nil {
		say(stderr, "sqlb: comparing the schema with the database: %v\n", err)
		return "the schema and the database could not be compared"
	}
	if len(changes) == 0 {
		line(stderr, "sqlb: the database matches the schema")
		return ""
	}
	// A drop of an index nothing in the history created reads exactly like a
	// drop of one sqlb built, and only one of them is intended (#268).
	changes = noteIndexDrops(changes, current, declared, p.MigrationsDir)

	// The changes are the answer, so they go to stdout: this is the one thing
	// the command produces, and it is worth piping into a migration.
	say(stderr, "sqlb: the database does not match the schema (%d differences):\n", len(changes))
	for _, c := range changes {
		// One "--" per line: a comment can carry a note of its own now, and a
		// second line without the marker would be SQL rather than prose.
		for _, l := range strings.Split(c.Comment, "\n") {
			if l != "" {
				line(stdout, "-- "+l)
			}
		}
		line(stdout, strings.TrimSpace(c.Up))
	}
	line(stderr, "sqlb: run `sqlb migrate -name <what_changed>` if the schema is right, "+
		"or edit the declaration if the database is")
	return "the database does not match the schema"
}

// declaredTableNames is the storage names of the declared tables, which is what
// the database calls them and therefore what narrows the read.
func declaredTableNames(r *schema.Registry) []string {
	if r == nil {
		return nil
	}
	tables := r.Tables()
	out := make([]string, 0, len(tables))
	for _, t := range tables {
		out = append(out, t.Name())
	}
	return out
}
