package codegen

// Between generate-check and check -database sits the gap issue #178 names: a
// migration file that carries sqlb's provenance header
// ("-- Generated by sqlb. Review before applying.") but has since had DDL
// pasted into it that no sqlb emitter writes — a trigger, most often, because
// that is exactly what the schema DSL cannot express. Neither existing check
// sees it: check compares committed generated Go against the declaration, not
// migration bodies (drift.go's own doc comment says so), and check -database
// only catches an edit once it has reached a database being pointed at, and
// only when it changes something the schema declares — a CREATE TRIGGER
// changes neither.
//
// This is the narrow fix the issue prefers (its option 2, not the checksum in
// option 1): no format change to the header, just a scan of header-bearing
// files for DDL sqlb's own emitters never write. It needs no SQL parser
// because the positive list is short and the vocabulary sqlb does emit —
// listed below — never overlaps with it.
//
// A migration composed by hand and rendered with migrate.Options.Handwritten
// (docs/migrations/README.md's worked example, and example/tasks/cmd/migrate,
// example/fxapp/cmd/migrate) never carries the header, so it is invisible
// here — correctly: nothing here has grounds to distrust a file that never
// claimed to be schema-derived. A file with no header at all is the same
// "yours now" case and is skipped for the same reason.

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/mind-vm/sqlb/migrate"
)

// disallowedMigrationDDL is DDL sqlb's own emitters never write. Keeping the
// list positive — statements sqlb provably never emits — rather than trying to
// enumerate every possible hand-edit is what keeps it accurate instead of
// guessed: migrate/ddl.go and migrate/formats.go emit exactly CREATE TABLE,
// DROP TABLE, ALTER TABLE (ADD/DROP/ALTER COLUMN, RENAME TO/COLUMN/CONSTRAINT,
// ADD/DROP/VALIDATE CONSTRAINT), CREATE/DROP [UNIQUE] INDEX [CONCURRENTLY],
// ALTER INDEX RENAME and COMMENT ON TABLE/COLUMN — and none of that creates a
// trigger, a function, or an anonymous procedural block. These three forms are
// exactly the ones the issue names as the ones that actually bite.
var disallowedMigrationDDL = []struct {
	kind string
	re   *regexp.Regexp
}{
	{"CREATE TRIGGER", regexp.MustCompile(`(?i)\bCREATE\s+TRIGGER\b`)},
	{"CREATE FUNCTION", regexp.MustCompile(`(?i)\bCREATE\s+(OR\s+REPLACE\s+)?FUNCTION\b`)},
	// The tag between the dollar signs is optional and Postgres allows any
	// identifier there (DO $migration$ ... $migration$), so this matches the
	// delimiter rather than the literal "$$" the issue writes for short.
	{"DO $$ block", regexp.MustCompile(`(?i)\bDO\s+\$[A-Za-z_]*\$`)},
}

// ProvenanceViolation names one header-bearing migration file whose body
// contains DDL sqlb never emits, and the line that tripped it.
type ProvenanceViolation struct {
	File      string
	Kind      string
	Statement string
}

func (v ProvenanceViolation) String() string {
	return fmt.Sprintf("%s: %s (%s)", v.File, v.Statement, v.Kind)
}

// checkMigrationProvenance scans every .sql file directly inside dir — not
// recursively, matching how nextVersion and historyIsEmpty in migrate.go read
// the same directory — and reports the header-bearing ones whose body
// contains DDL sqlb's own emitters never write.
//
// A missing directory is not an error: a project with no MigrationsDir has
// nothing for this to scan, the same way historyIsEmpty treats it as empty
// rather than broken.
func checkMigrationProvenance(dir string) ([]ProvenanceViolation, error) {
	entries, err := os.ReadDir(dir)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}

	var violations []ProvenanceViolation
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".sql") {
			continue
		}
		path := filepath.Join(dir, e.Name())
		body, err := os.ReadFile(path)
		if err != nil {
			return nil, err
		}
		content := string(body)
		if !strings.Contains(content, migrate.Header) {
			// No header: this file never claimed to be sqlb's, so whatever it
			// contains is the "yours now" case the issue describes, not
			// sqlb's to police.
			continue
		}
		for _, line := range uncommentedLines(content) {
			for _, d := range disallowedMigrationDDL {
				if d.re.MatchString(line) {
					violations = append(violations, ProvenanceViolation{
						File:      path,
						Kind:      d.kind,
						Statement: strings.TrimSpace(line),
					})
				}
			}
		}
	}

	sort.Slice(violations, func(i, j int) bool {
		if violations[i].File != violations[j].File {
			return violations[i].File < violations[j].File
		}
		return violations[i].Statement < violations[j].Statement
	})
	return violations, nil
}

// uncommentedLines returns content's lines with every full-line "--" comment
// dropped, so a destructive-change Reason — human prose that routinely
// mentions "trigger" — is never mistaken for the DDL it might be describing.
//
// A line-level cut is enough: writeSection in migrate/formats.go always starts
// a comment on its own line and never shares one with a statement, so nothing
// sqlb itself renders puts SQL and a "--" prefix on the same line.
func uncommentedLines(content string) []string {
	lines := strings.Split(content, "\n")
	out := make([]string, 0, len(lines))
	for _, line := range lines {
		if strings.HasPrefix(strings.TrimSpace(line), "--") {
			continue
		}
		out = append(out, line)
	}
	return out
}
