package codegen_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/mind-vm/sqlb/codegen"
)

// provenanceProject is migrateProject without the ShadowDB requirement:
// these tests never replay history, they only read files off disk.
func provenanceProject(t *testing.T) codegen.Project {
	t.Helper()
	t.Chdir(t.TempDir())
	return codegen.Project{
		Options:       codegen.Options{Registry: fixture(), Dir: "out", Package: "gen"},
		MigrationsDir: "migrations",
	}
}

// writeMigration puts one migration file in place and generates a clean tree
// alongside it, so a test's assertions are about the provenance scan and
// nothing else — a stale models_gen.go would fail check for an unrelated
// reason and make the assertion meaningless.
func writeMigration(t *testing.T, p codegen.Project, name, body string) {
	t.Helper()
	if err := os.MkdirAll(p.MigrationsDir, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(p.MigrationsDir, name), []byte(body), 0o644); err != nil {
		t.Fatal(err)
	}
	if code, out := run(t, p, "generate"); code != 0 {
		t.Fatalf("generate: exit %d, output:\n%s", code, out)
	}
}

const header = "-- Generated by sqlb. Review before applying."

// The case the issue is about: a file that still claims sqlb's header has had
// a CREATE TRIGGER pasted into it — DDL none of sqlb's emitters write, so
// neither generate-check nor check -database would ever see it. ADR-0016: this
// is the guard proven to fail before the next test proves it passes.
func TestCheckFailsOnATriggerInAHeaderedMigration(t *testing.T) {
	p := provenanceProject(t)
	writeMigration(t, p, "00001_add_trigger.sql", header+`

-- +goose Up
ALTER TABLE "blog_entries" ADD COLUMN "note" text;

CREATE TRIGGER blog_entries_touch BEFORE UPDATE ON "blog_entries"
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- +goose Down
ALTER TABLE "blog_entries" DROP COLUMN "note";
`)

	code, out := run(t, p, "check")
	if code == 0 {
		t.Fatalf("check passed on a header-bearing migration containing CREATE TRIGGER, "+
			"which sqlb never emits:\n%s", out)
	}
	if !strings.Contains(out, "00001_add_trigger.sql") {
		t.Errorf("check failed without naming the file:\n%s", out)
	}
	if !strings.Contains(out, "CREATE TRIGGER") {
		t.Errorf("check failed without naming the offending statement:\n%s", out)
	}
}

// The other DDL forms sqlb never emits, named by the issue alongside triggers:
// a function and a bare DO block.
func TestCheckFailsOnAFunctionAndADoBlock(t *testing.T) {
	p := provenanceProject(t)
	writeMigration(t, p, "00001_function.sql", header+`

-- +goose Up
CREATE FUNCTION touch_updated_at() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$;

-- +goose Down
DROP FUNCTION touch_updated_at();
`)

	if code, out := run(t, p, "check"); code == 0 {
		t.Fatalf("check passed on a header-bearing CREATE FUNCTION:\n%s", out)
	} else if !strings.Contains(out, "CREATE FUNCTION") {
		t.Errorf("check failed without naming CREATE FUNCTION:\n%s", out)
	}

	p2 := provenanceProject(t)
	writeMigration(t, p2, "00001_do_block.sql", header+`

-- +goose Up
DO $$
BEGIN
    PERFORM 1;
END;
$$;
`)
	if code, out := run(t, p2, "check"); code == 0 {
		t.Fatalf("check passed on a header-bearing DO $$ block:\n%s", out)
	} else if !strings.Contains(out, "DO $$") {
		t.Errorf("check failed without naming the DO $$ block:\n%s", out)
	}
}

// A clean, header-bearing migration containing only DDL sqlb's own emitters
// write must stay clean. This is the other half of ADR-0016: a guard that
// always fails is exactly as useless as one that never does.
func TestCheckStaysCleanOnAnOrdinaryGeneratedMigration(t *testing.T) {
	p := provenanceProject(t)
	writeMigration(t, p, "00001_add_column.sql", header+`

-- +goose Up
ALTER TABLE "blog_entries" ADD COLUMN "note" text;
CREATE INDEX "blog_entries_note_idx" ON "blog_entries" ("note");

-- +goose Down
DROP INDEX "blog_entries_note_idx";
ALTER TABLE "blog_entries" DROP COLUMN "note";
`)

	if code, out := run(t, p, "check"); code != 0 {
		t.Fatalf("check failed on a migration containing only DDL sqlb itself emits:\n%s", out)
	}
}

// The false positive the issue explicitly warns about: a destructive-change
// comment block whose human-written Reason mentions "trigger" in prose, with
// no actual DDL sqlb never emits. needsStatementBlock (migrate/migrate.go)
// already expects this kind of human writing inside a generated file, and the
// scan must not confuse prose for a statement.
func TestCheckIgnoresProseMentioningTrigger(t *testing.T) {
	p := provenanceProject(t)
	writeMigration(t, p, "00001_destructive.sql", header+`

-- +goose Up
-- DESTRUCTIVE: dropping this column also drops the trigger function that
--   reads it, and any CREATE TRIGGER a follow-up migration adds to replace
--   it will need to be reviewed on its own.
-- Review, then uncomment to apply. Generated commented out on purpose.
-- ALTER TABLE "blog_entries" DROP COLUMN "secret";

-- +goose Down
`)

	if code, out := run(t, p, "check"); code != 0 {
		t.Fatalf("check failed on a comment that only mentions CREATE TRIGGER in prose, "+
			"never emitting the statement itself:\n%s", out)
	}
}

// The issue's "yours now" case: a migration with no header at all is not
// sqlb's to police, whatever DDL it contains — a CREATE TRIGGER here is
// exactly what a project that owns its own migrations is expected to write.
func TestCheckIgnoresATriggerInAnUnheaderedMigration(t *testing.T) {
	p := provenanceProject(t)
	writeMigration(t, p, "00001_handwritten.sql", `-- +goose Up
CREATE TRIGGER blog_entries_touch BEFORE UPDATE ON "blog_entries"
    FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- +goose Down
DROP TRIGGER IF EXISTS blog_entries_touch ON "blog_entries";
`)

	if code, out := run(t, p, "check"); code != 0 {
		t.Fatalf("check failed on an unheadered migration, which is not sqlb's to police:\n%s", out)
	}
}
