package codegen

import (
	"bytes"
	"fmt"
	"sort"
	"strconv"
	"strings"

	"github.com/mind-vm/sqlb/schema"
)

// RenderSchema renders a registry as the Go source that would declare it.
//
// It is the other half of adoption. introspect turns a database into a
// *schema.Registry; this turns that registry into the schema.go a project
// edits from then on, which is what makes "point sqlb at an existing database"
// a complete story rather than an intermediate data structure (ADR-0014).
//
// # This output is meant to be edited
//
// Every other artefact in this package is generated on every build and carries
// a DO NOT EDIT header. This one is the opposite: it is written once, at the
// moment of adoption, and then becomes the source of truth that everything else
// is generated *from*. The header says so, because a reader who has met the
// other files will otherwise assume their habits apply here.
//
// # Nothing is exposed, and no capabilities are set
//
// Capabilities cannot be inferred from DDL. A filterable column is a decision
// about what the outside world may ask, and a database schema does not record
// decisions — so everything renders with none, and nothing is exposed over
// REST. Widening it is then a deliberate, reviewable edit rather than something
// that happened because a generator felt confident (ADR-0006, ADR-0014).
//
// # Table names are not singularised
//
// A table called orgs renders as `var Orgs`, not `var Org`. Singularising is a
// guess that is wrong often enough to matter — status, address, series — and a
// wrong Go identifier is a compile error at best and a confusing rename at
// worst. Renaming the variable afterwards is a one-line edit that the compiler
// checks; this generator does not do it for you.
func RenderSchema(r *schema.Registry, opts SchemaOptions) ([]byte, error) {
	if r == nil {
		return nil, fmt.Errorf("codegen: RenderSchema needs a registry")
	}
	if opts.Package == "" {
		return nil, fmt.Errorf("codegen: RenderSchema needs a package name")
	}

	tables, err := declarationOrder(r.Tables())
	if err != nil {
		return nil, err
	}

	names := varNames(tables)

	buf := schemaHeader(opts)
	if r.Module() != "" {
		fmt.Fprintf(buf, "// %s owns these tables. Their storage names carry the module prefix;\n", r.Module())
		fmt.Fprintf(buf, "// the declarations below use the local name and the registry applies it.\n")
		fmt.Fprintf(buf, "var %s = schema.NewModule(%s)\n\n", opts.registryVar(), strconv.Quote(r.Module()))
	}

	for i, t := range tables {
		if i > 0 {
			buf.WriteString("\n")
		}
		if err := renderTable(buf, t, names, r, opts); err != nil {
			return nil, err
		}
	}

	return gofmt(opts.fileName(), buf.Bytes())
}

// SchemaOptions configures RenderSchema.
type SchemaOptions struct {
	// Package is the package clause. Required.
	Package string

	// File names the output in error messages and in the generated header. It
	// is not written to; the caller decides where the bytes go.
	File string

	// RegistryVar overrides the variable a module registry is held in.
	// Ignored for a registry with no module.
	RegistryVar string
}

func (o SchemaOptions) fileName() string {
	return orDefault(o.File, "schema.go")
}

func (o SchemaOptions) registryVar() string {
	return orDefault(o.RegistryVar, "Module")
}

func schemaHeader(opts SchemaOptions) *bytes.Buffer {
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Package %s describes an existing database.\n//\n", opts.Package)
	b.WriteString(`// Generated by sqlb from a live schema — and then yours. Unlike the rest of
// sqlb's generated code this file is NOT regenerated and carries no DO NOT
// EDIT: it is the starting point for a schema you own, and from here it is the
// source of truth that models, columns and the REST surface are generated from.
//
// Every column imported with no capabilities and no REST exposure, because
// neither can be read from DDL. Adding them is a deliberate edit — start with
// what a client genuinely needs to filter, sort or search on.
`)
	fmt.Fprintf(&b, "package %s\n\nimport \"github.com/mind-vm/sqlb/schema\"\n\n", opts.Package)
	return &b
}

// declarationOrder sorts tables so that every reference target is declared
// before the table referring to it, because schema.Ref takes the target's Go
// variable — a table declared too early would name one that does not exist yet.
//
// Ties are broken by name so the output is deterministic.
//
// The cycle branch is not defensive duplication of introspect's identical check.
// It is what makes this walk terminate: RenderSchema is exported and takes any
// registry, and without it a cyclic one recurses until the stack runs out.
func declarationOrder(tables []*schema.TableDef) ([]*schema.TableDef, error) {
	byName := map[string]*schema.TableDef{}
	for _, t := range tables {
		byName[t.Name()] = t
	}

	sorted := append([]*schema.TableDef(nil), tables...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name() < sorted[j].Name() })

	var out []*schema.TableDef
	state := map[string]int{} // 0 unvisited, 1 in progress, 2 done
	var visit func(t *schema.TableDef, path []string) error
	visit = func(t *schema.TableDef, path []string) error {
		switch state[t.Name()] {
		case 2:
			return nil
		case 1:
			return fmt.Errorf(
				"codegen: %s form a foreign key cycle, which cannot be declared in Go: "+
					"each schema.Ref needs the target's variable to already exist. "+
					"Break it by making one side a schema.ExternalRef, which declares the "+
					"relationship without the Go dependency",
				strings.Join(append(path, t.Name()), " → "))
		}
		state[t.Name()] = 1
		for _, ref := range t.Relations() {
			r := ref.Desc().Ref
			if r == nil || r.External || r.Table == nil {
				continue
			}
			if target, ok := byName[r.Table.Name()]; ok && target != t {
				if err := visit(target, append(path, t.Name())); err != nil {
					return err
				}
			}
		}
		state[t.Name()] = 2
		out = append(out, t)
		return nil
	}

	for _, t := range sorted {
		if err := visit(t, nil); err != nil {
			return nil, err
		}
	}
	return out, nil
}

// varNames assigns each table a Go variable, disambiguating a collision rather
// than emitting two declarations with the same name.
func varNames(tables []*schema.TableDef) map[string]string {
	out := map[string]string{}
	used := map[string]bool{}
	for _, t := range tables {
		name := GoName(t.LocalName())
		if name == "" {
			name = GoName(t.Name())
		}
		candidate := name
		for i := 2; used[candidate]; i++ {
			candidate = fmt.Sprintf("%s%d", name, i)
		}
		used[candidate] = true
		out[t.Name()] = candidate
	}
	return out
}

func renderTable(b *bytes.Buffer, t *schema.TableDef, names map[string]string, r *schema.Registry, opts SchemaOptions) error {
	if c := t.Comment(); c != "" {
		fmt.Fprintf(b, "// %s\n", strings.ReplaceAll(c, "\n", "\n// "))
	}

	ctor := "schema.Table"
	if r.Module() != "" {
		ctor = opts.registryVar() + ".Table"
	}
	fmt.Fprintf(b, "var %s = %s(%s,\n", names[t.Name()], ctor, strconv.Quote(t.LocalName()))

	for _, f := range t.Fields() {
		src, err := renderField(f.Desc(), names)
		if err != nil {
			return fmt.Errorf("codegen: %s.%s: %w", t.Name(), f.Desc().Name, err)
		}
		fmt.Fprintf(b, "\t%s,\n", src)
	}
	b.WriteString(")")

	// Table-level modifiers, each on its own line so a diff after a hand edit
	// touches one of them rather than reflowing the lot.
	if c := t.Comment(); c != "" {
		fmt.Fprintf(b, ".\n\tDescribe(%s)", strconv.Quote(c))
	}
	if cols := t.CompositeKey(); len(cols) > 0 {
		quoted := make([]string, len(cols))
		for i, c := range cols {
			quoted[i] = strconv.Quote(c)
		}
		fmt.Fprintf(b, ".\n\tPrimaryKeyColumns(%s)", strings.Join(quoted, ", "))
	}
	if pk := t.PrimaryKeyName(); pk != "" {
		fmt.Fprintf(b, ".\n\tPrimaryKeyNamed(%s)", strconv.Quote(pk))
	}
	for _, c := range t.Checks() {
		fmt.Fprintf(b, ".\n\tCheck(%s, %s)", strconv.Quote(c.Name), strconv.Quote(c.Expr))
	}
	for _, u := range t.Uniques() {
		b.WriteString(".\n\t" + renderUnique(t, u))
	}
	for _, e := range t.Exclusions() {
		fmt.Fprintf(b, ".\n\tAddExclude(schema.Exclusion{\n\t\tName: %s,\n", strconv.Quote(e.Name))
		if e.Using != "" {
			fmt.Fprintf(b, "\t\tUsing: %s,\n", strconv.Quote(e.Using))
		}
		fmt.Fprintf(b, "\t\tElements: %s,\n", strconv.Quote(e.Elements))
		if e.Where != "" {
			fmt.Fprintf(b, "\t\tWhere: %s,\n", strconv.Quote(e.Where))
		}
		b.WriteString("\t})")
	}
	for _, idx := range t.Indexes() {
		b.WriteString(".\n\t" + renderIndex(t, idx))
	}
	b.WriteString("\n")
	return nil
}

// renderUnique uses the shorthand when the constraint's name is the one the
// convention derives, and UniqueNamed otherwise — the same rule renderIndex
// applies, and for the same reason: a name that came from somewhere else has to
// be kept, or the first diff after adoption drops and rebuilds the constraint.
func renderUnique(t *schema.TableDef, u schema.Unique) string {
	quoted := make([]string, len(u.Columns))
	for i, c := range u.Columns {
		quoted[i] = strconv.Quote(c)
	}
	args := strings.Join(quoted, ", ")
	derived := u.Name == t.Name()+"_"+strings.Join(u.Columns, "_")+"_key"

	// Deferral has no shorthand, so a deferred constraint takes the whole-struct
	// form the way a non-default index does. Rendering it as Unique() would emit
	// a declaration that diffs against the database it was read from.
	if u.Deferrable != schema.NotDeferrable {
		var b strings.Builder
		b.WriteString("AddUnique(schema.Unique{\n")
		if !derived {
			fmt.Fprintf(&b, "\t\tName:       %s,\n", strconv.Quote(u.Name))
		}
		fmt.Fprintf(&b, "\t\tColumns:    []string{%s},\n", args)
		fmt.Fprintf(&b, "\t\tDeferrable: %s,\n", deferrableExpr(u.Deferrable))
		b.WriteString("\t})")
		return b.String()
	}

	if derived {
		return fmt.Sprintf("Unique(%s)", args)
	}
	return fmt.Sprintf("UniqueNamed(%s, %s)", strconv.Quote(u.Name), args)
}

// deferrableExpr names the constant, so generated source reads like a
// declaration rather than like a string literal that happens to parse.
func deferrableExpr(d schema.Deferrable) string {
	switch d {
	case schema.DeferrableCheck:
		return "schema.DeferrableCheck"
	case schema.DeferredCheck:
		return "schema.DeferredCheck"
	}
	return "schema.NotDeferrable"
}

// renderIndex uses the shorthand when the index is exactly what the shorthand
// would have produced, and the explicit form otherwise. Comparing against the
// derived name is what decides it: an index whose name came from somewhere else
// has to keep that name, or the first diff after adoption drops and rebuilds it.
func renderIndex(t *schema.TableDef, idx schema.Index) string {
	quoted := make([]string, len(idx.Columns))
	for i, c := range idx.Columns {
		quoted[i] = strconv.Quote(c)
	}
	args := strings.Join(quoted, ", ")

	plain := idx.Where == "" && (idx.Method == "" || idx.Method == "btree") &&
		len(idx.Opclasses) == 0 && len(idx.With) == 0 && len(idx.Orders) == 0
	if plain && idx.Name == derivedIndexName(t, idx) {
		if idx.Unique {
			return fmt.Sprintf("UniqueIndex(%s)", args)
		}
		return fmt.Sprintf("Index(%s)", args)
	}

	var b strings.Builder
	b.WriteString("AddIndex(schema.Index{\n")
	fmt.Fprintf(&b, "\t\tName:    %s,\n", strconv.Quote(idx.Name))
	fmt.Fprintf(&b, "\t\tColumns: []string{%s},\n", args)
	if idx.Unique {
		b.WriteString("\t\tUnique:  true,\n")
	}
	if idx.Method != "" {
		fmt.Fprintf(&b, "\t\tMethod:  %s,\n", strconv.Quote(idx.Method))
	}
	if idx.Where != "" {
		fmt.Fprintf(&b, "\t\tWhere:   %s,\n", strconv.Quote(idx.Where))
	}
	// An operator class and a storage parameter are what make a pgvector index
	// the index it is, so a bootstrap that dropped them would render a schema
	// whose first migration Postgres refuses (issue #53).
	if len(idx.Opclasses) > 0 {
		fmt.Fprintf(&b, "\t\tOpclasses: %s,\n", renderStringMap(idx.Opclasses))
	}
	if len(idx.With) > 0 {
		fmt.Fprintf(&b, "\t\tWith:      %s,\n", renderStringMap(idx.With))
	}
	// And the sort order, for the same reason: an index backing a specific
	// ORDER BY is unusable in any other order, so a bootstrap that dropped it
	// would render a schema whose first diff proposes replacing the index it
	// was rendered from (issue #64).
	if len(idx.Orders) > 0 {
		fmt.Fprintf(&b, "\t\tOrders:    %s,\n", renderOrders(idx.Orders))
	}
	b.WriteString("\t})")
	return b.String()
}

// renderStringMap writes a map literal with its keys in sorted order, because a
// generated file whose contents depend on map iteration is a file that fails
// its own drift check every other run.
func renderStringMap(m map[string]string) string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	parts := make([]string, 0, len(keys))
	for _, k := range keys {
		parts = append(parts, fmt.Sprintf("%s: %s", strconv.Quote(k), strconv.Quote(m[k])))
	}
	return "map[string]string{" + strings.Join(parts, ", ") + "}"
}

// renderOrders writes the per-column sort orders, keys sorted for the same
// reason renderStringMap sorts its own.
func renderOrders(m map[string]schema.IndexOrder) string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	parts := make([]string, 0, len(keys))
	for _, k := range keys {
		var fields []string
		if m[k].Desc {
			fields = append(fields, "Desc: true")
		}
		switch m[k].Nulls {
		case schema.NullsFirst:
			fields = append(fields, "Nulls: schema.NullsFirst")
		case schema.NullsLast:
			fields = append(fields, "Nulls: schema.NullsLast")
		}
		parts = append(parts, fmt.Sprintf("%s: {%s}", strconv.Quote(k), strings.Join(fields, ", ")))
	}
	return "map[string]schema.IndexOrder{" + strings.Join(parts, ", ") + "}"
}

// derivedIndexName reproduces what TableDef.Index would have named this index.
// It goes through the real constructor rather than reimplementing the rule, so
// the two cannot drift apart.
func derivedIndexName(t *schema.TableDef, idx schema.Index) string {
	probe := schema.NewRegistry().Table(t.LocalName())
	if idx.Unique {
		probe.UniqueIndex(idx.Columns...)
	} else {
		probe.Index(idx.Columns...)
	}
	got := probe.Indexes()
	if len(got) == 0 {
		return ""
	}
	return got[len(got)-1].Name
}

func renderField(d *schema.FieldDesc, names map[string]string) (string, error) {
	var b strings.Builder

	// A computed column is its own constructor and takes none of the modifiers
	// below: every one of them is a statement about storage, and Validate
	// refuses each. Nothing introspected is ever computed — a database has no
	// such column to read back — so this is here for a registry that was
	// declared rather than imported.
	if d.Computed() {
		constant, err := typeConstant(d.Type)
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&b, "schema.Computed(%s, %s, schema.FromSQL(%s))",
			strconv.Quote(d.Name), constant, strconv.Quote(d.Expr))
		if len(d.Needs) > 0 {
			quoted := make([]string, len(d.Needs))
			for i, key := range d.Needs {
				quoted[i] = strconv.Quote(key)
			}
			fmt.Fprintf(&b, ".Needs(%s)", strings.Join(quoted, ", "))
		}
		return b.String(), nil
	}

	if d.Ref != nil {
		if err := renderRef(&b, d, names); err != nil {
			return "", err
		}
	} else {
		ctor, err := fieldConstructor(d)
		if err != nil {
			return "", err
		}
		b.WriteString(ctor)
	}

	// Array comes first among the modifiers, because it changes what the
	// constructor named — the element type — into the column's own type, and
	// reading it anywhere else would suggest the order does not matter.
	if d.Array {
		b.WriteString(".Array()")
	}

	// A reference is a uuid column whose name, type and default are decided by
	// Ref itself, so only the modifiers below apply to both kinds.
	// Before PrimaryKey, so a key column reads as what it is and then as what
	// it does — schema.BigInt("id").Identity().PrimaryKey().
	switch d.Auto {
	case schema.AutoIdentity:
		b.WriteString(".Identity()")
	case schema.AutoIdentityAlways:
		b.WriteString(".IdentityAlways()")
	}
	if d.PrimaryKey {
		b.WriteString(".PrimaryKey()")
	}
	if d.Unique {
		b.WriteString(".Unique()")
		if d.UniqueDeferrable == schema.DeferredCheck {
			b.WriteString(".Deferred()")
		}
	}
	if d.Nullable {
		b.WriteString(".Nullable()")
	}
	if d.Default != nil && !defaultIsImpliedByConstructor(d) {
		def, err := renderDefaultExpr(d.Default)
		if err != nil {
			return "", err
		}
		fmt.Fprintf(&b, ".Default(%s)", def)
	}
	if d.Comment != "" {
		fmt.Fprintf(&b, ".Comment(%s)", strconv.Quote(d.Comment))
	}
	if d.ConstraintName != "" {
		fmt.Fprintf(&b, ".ConstraintNamed(%s)", strconv.Quote(d.ConstraintName))
	}
	if d.CheckName != "" {
		fmt.Fprintf(&b, ".CheckNamed(%s)", strconv.Quote(d.CheckName))
	}
	return b.String(), nil
}

func renderRef(b *strings.Builder, d *schema.FieldDesc, names map[string]string) error {
	ref := d.Ref
	switch {
	case ref.External:
		fmt.Fprintf(b, "schema.ExternalRef(%s, %s)", strconv.Quote(ref.Name), strconv.Quote(ref.Target))
		if ref.Enforced {
			// The constraint is real, so the rendered declaration has to say
			// so — otherwise the round trip loses a foreign key the database
			// has and the next diff proposes dropping it.
			b.WriteString(".Enforced()")
		}
	case ref.Table == nil:
		return fmt.Errorf("reference %q has no target table", ref.Name)
	default:
		target, ok := names[ref.Table.Name()]
		if !ok {
			return fmt.Errorf("reference %q points at %q, which is not in this registry",
				ref.Name, ref.Table.Name())
		}
		fmt.Fprintf(b, "schema.Ref(%s, %s)", strconv.Quote(ref.Name), target)
	}

	// Ref names the column relation+"_id". Anything else has to be pinned, or
	// the declaration describes a column the database does not have.
	if d.Name != ref.Name+"_id" {
		fmt.Fprintf(b, ".Named(%s)", strconv.Quote(d.Name))
	}
	if ref.OnDelete != "" && ref.OnDelete != schema.NoAction {
		fmt.Fprintf(b, ".OnDelete(%s)", actionExpr(ref.OnDelete))
	}
	if ref.OnUpdate != "" && ref.OnUpdate != schema.NoAction {
		fmt.Fprintf(b, ".OnUpdate(%s)", actionExpr(ref.OnUpdate))
	}
	return nil
}

func actionExpr(a schema.RefAction) string {
	switch a {
	case schema.Cascade:
		return "schema.Cascade"
	case schema.Restrict:
		return "schema.Restrict"
	case schema.SetNull:
		return "schema.SetNull"
	case schema.SetDefault:
		return "schema.SetDefault"
	case schema.NoAction:
		return "schema.NoAction"
	}
	// Unreachable through the DSL, but rendering an unknown action as a string
	// literal would produce Go that does not compile, which is the better
	// failure than one that compiles and means something else.
	return "schema.RefAction(" + strconv.Quote(string(a)) + ")"
}

// fieldConstructor picks the DSL constructor for a column.
//
// UUIDv7 is the one place a default decides the constructor rather than a
// modifier: schema.UUIDv7(name) is a uuid column that already carries the
// generator, so rendering it as UUID(...).Default(GenUUIDv7()) would be correct
// but would not look like anything a person writes.
// typeConstant names the schema.Type constant for a logical type, for the one
// declaration that takes the type as an argument rather than choosing a
// constructor from it.
func typeConstant(t schema.Type) (string, error) {
	switch t {
	case schema.TypeText:
		return "schema.TypeText", nil
	case schema.TypeVarchar:
		return "schema.TypeVarchar", nil
	case schema.TypeSmallInt:
		return "schema.TypeSmallInt", nil
	case schema.TypeInt:
		return "schema.TypeInt", nil
	case schema.TypeBigInt:
		return "schema.TypeBigInt", nil
	case schema.TypeReal:
		return "schema.TypeReal", nil
	case schema.TypeFloat:
		return "schema.TypeFloat", nil
	case schema.TypeNumeric:
		return "schema.TypeNumeric", nil
	case schema.TypeBool:
		return "schema.TypeBool", nil
	case schema.TypeUUID:
		return "schema.TypeUUID", nil
	case schema.TypeTimestamp:
		return "schema.TypeTimestamp", nil
	case schema.TypeDate:
		return "schema.TypeDate", nil
	case schema.TypeTime:
		return "schema.TypeTime", nil
	case schema.TypeJSON:
		return "schema.TypeJSON", nil
	case schema.TypeBytes:
		return "schema.TypeBytes", nil
	}
	return "", fmt.Errorf("no schema.Type constant for %q", t)
}

func fieldConstructor(d *schema.FieldDesc) (string, error) {
	name := strconv.Quote(d.Name)
	// A serial is its own constructor, the way UUIDv7 is: the auto-ness is part
	// of what the column *is*, and rendering the plain integer plus a modifier
	// would read as an afterthought where the database has one word for it.
	// An identity is a modifier, which is what renderField adds — the two are
	// spelled differently here because they are spelled differently in SQL.
	if d.Auto == schema.AutoSerial {
		switch d.Type {
		case schema.TypeSmallInt:
			return "schema.SmallSerial(" + name + ")", nil
		case schema.TypeInt:
			return "schema.Serial(" + name + ")", nil
		case schema.TypeBigInt:
			return "schema.BigSerial(" + name + ")", nil
		}
		return "", fmt.Errorf("column %q is a serial over %q, which has no serial spelling", d.Name, d.Type)
	}
	switch d.Type {
	case schema.TypeText:
		return "schema.Text(" + name + ")", nil
	case schema.TypeVarchar:
		return fmt.Sprintf("schema.Varchar(%s, %d)", name, d.Size), nil
	case schema.TypeSmallInt:
		return "schema.SmallInt(" + name + ")", nil
	case schema.TypeInt:
		return "schema.Int(" + name + ")", nil
	case schema.TypeBigInt:
		return "schema.BigInt(" + name + ")", nil
	case schema.TypeReal:
		return "schema.Real(" + name + ")", nil
	case schema.TypeFloat:
		return "schema.Float(" + name + ")", nil
	case schema.TypeNumeric:
		// The precision is part of the type, so a bootstrap that dropped it
		// would render a schema whose first diff proposes rewriting the column
		// it was rendered from (issue #81).
		if d.Size > 0 {
			return fmt.Sprintf("schema.Numeric(%s, %d, %d)", name, d.Size, d.Scale), nil
		}
		return "schema.Numeric(" + name + ")", nil
	case schema.TypeBool:
		return "schema.Bool(" + name + ")", nil
	case schema.TypeUUID:
		if isGenUUIDv7(d.Default) {
			return "schema.UUIDv7(" + name + ")", nil
		}
		return "schema.UUID(" + name + ")", nil
	case schema.TypeTimestamp:
		return "schema.Timestamp(" + name + ")", nil
	case schema.TypeDate:
		return "schema.Date(" + name + ")", nil
	case schema.TypeTime:
		return "schema.Time(" + name + ")", nil
	case schema.TypeJSON:
		return "schema.JSON(" + name + ")", nil
	case schema.TypeBytes:
		return "schema.Bytes(" + name + ")", nil
	case schema.TypeEnum:
		values := make([]string, len(d.EnumValues))
		for i, v := range d.EnumValues {
			values[i] = strconv.Quote(v)
		}
		if len(values) == 0 {
			return "", fmt.Errorf("enum column has no values")
		}
		return fmt.Sprintf("schema.Enum(%s, %s)", name, strings.Join(values, ", ")), nil
	case schema.TypeVector:
		// The dimension is part of the type rather than a constraint on it
		// (ADR-0026), so it is an argument here exactly as it is at a call site
		// somebody wrote by hand. A real schema usually names a constant —
		// schema.Vector("embedding", ragcfg.Dim) — and this cannot know that,
		// so it writes the width the database has.
		if d.Dim <= 0 {
			return "", fmt.Errorf("vector column has no dimension")
		}
		return fmt.Sprintf("schema.Vector(%s, %d)", name, d.Dim), nil
	}
	return "", fmt.Errorf(
		"unknown column type %q; introspect and RenderSchema disagree about what the DSL can express, "+
			"which is a bug in sqlb rather than in your database (issue #53)", d.Type)
}

func defaultIsImpliedByConstructor(d *schema.FieldDesc) bool {
	return d.Type == schema.TypeUUID && isGenUUIDv7(d.Default)
}

func isGenUUIDv7(d *schema.Default) bool {
	return d != nil && d.Raw == schema.GenUUIDv7().Raw
}

// renderDefaultExpr renders a default as the DSL call that produces it,
// recognising the shipped generators by the exact text they emit — the same
// correspondence introspect uses reading them back.
func renderDefaultExpr(d *schema.Default) (string, error) {
	if d.Raw != "" {
		switch d.Raw {
		case schema.Now().Raw:
			return "schema.Now()", nil
		case schema.GenUUIDv7().Raw:
			return "schema.GenUUIDv7()", nil
		case schema.GenUUIDv4().Raw:
			return "schema.GenUUIDv4()", nil
		}
		return fmt.Sprintf("schema.Expr(%s)", strconv.Quote(d.Raw)), nil
	}

	switch v := d.Value.(type) {
	case nil:
		return "schema.Value(nil)", nil
	case string:
		return fmt.Sprintf("schema.Value(%s)", strconv.Quote(v)), nil
	case bool:
		return fmt.Sprintf("schema.Value(%t)", v), nil
	case int:
		return fmt.Sprintf("schema.Value(%d)", v), nil
	case int64:
		return fmt.Sprintf("schema.Value(int64(%d))", v), nil
	case float64:
		return fmt.Sprintf("schema.Value(%v)", v), nil
	}
	return "", fmt.Errorf("cannot render default value of type %T; it would need schema.Expr", d.Value)
}
