package codegen_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/jryannel/sqlb/codegen"
	"github.com/jryannel/sqlb/schema"
)

// tsFixture is restFixture plus an expandable reference in both directions, so
// that the emitted client has something to narrow a response by.
func tsFixture() *schema.Registry {
	r := schema.NewRegistry()
	org := r.Table("orgs",
		schema.UUIDv7("id").PrimaryKey(),
		schema.Text("name").Sortable(),
	).Expose(schema.REST{Ops: schema.OpRead | schema.OpList})

	r.Table("posts",
		schema.UUIDv7("id").PrimaryKey(),
		schema.Ref("org", org).OnDelete(schema.Cascade).Immutable().Filterable().
			Expandable().Inverse("posts").InverseExpandable(),
		schema.Text("title").Searchable().Sortable(),
		schema.Enum("status", "draft", "published").Default(schema.Value("draft")).Filterable(),
		schema.BigInt("view_count").ReadOnly().Filterable(),
		schema.Timestamp("published_at").Nullable().Filterable().Sortable(),
		schema.Text("secret").Hidden(),
	).Expose(schema.REST{Ops: schema.CRUD | schema.OpList, MaxPageSize: 50})
	return r
}

// generateTS returns the emitted TypeScript, keyed by file name.
func generateTS(t *testing.T, r *schema.Registry) map[string]string {
	t.Helper()
	dir := t.TempDir()
	files, err := codegen.Generate(codegen.Options{
		Registry: r, Dir: dir, Package: "gen", TSDir: "web/api",
	})
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	out := map[string]string{}
	for _, f := range files {
		if filepath.Ext(f) != ".ts" {
			continue
		}
		b, err := os.ReadFile(f)
		if err != nil {
			t.Fatal(err)
		}
		out[filepath.Base(f)] = string(b)
	}
	if len(out) == 0 {
		t.Fatal("no TypeScript was emitted")
	}
	return out
}

func TestTSRowTypesFollowTheWire(t *testing.T) {
	src := generateTS(t, tsFixture())["client.gen.ts"]

	for _, want := range []string{
		"// Code generated by github.com/jryannel/sqlb. DO NOT EDIT.",
		"export interface Post {",
		"id: string;",
		"org_id: string;",                  // snake_case, because that is the wire spelling
		"view_count: number;",              // bigint is a JSON number
		"Values above 2^53 lose precision", // and the loss is silent, so it is stated
		"status: PostStatus;",              // enum keeps its type
		"published_at: string | null;",     // nullable, and a timestamp is a string
		"export type PostStatus = 'draft' | 'published';",
	} {
		if !contains(src, want) {
			t.Errorf("row types missing %q:\n%s", want, src)
		}
	}

	// A hidden column has no spelling here at all: not in the row, not in the
	// projection vocabulary, not as a filter. This is the same guarantee the
	// typed column facade gives Go, carried across the wire.
	for _, forbidden := range []string{"secret"} {
		if contains(src, forbidden) {
			t.Errorf("a hidden column leaked into the client:\n%s", src)
		}
	}
}

func TestTSBodiesOmitWhatAClientMayNotSet(t *testing.T) {
	src := generateTS(t, tsFixture())["client.gen.ts"]

	create := section(t, src, "export interface PostCreate {", "\n}")
	for _, want := range []string{
		"title: string;",                // required
		"status?: PostStatus;",          // defaulted → optional
		"published_at?: string | null;", // nullable → optional, and nullable
	} {
		if !contains(create, want) {
			t.Errorf("create body missing %q:\n%s", want, create)
		}
	}
	// "{ id:" rather than "id:", which org_id would satisfy.
	for _, forbidden := range []string{"{ id:", "view_count", "secret"} {
		if contains(create, forbidden) {
			t.Errorf("create body should not carry %s:\n%s", forbidden, create)
		}
	}

	// An immutable column is settable once, at create, so the patch body has no
	// property for it — the same set the Go patch body uses.
	patch := section(t, src, "export interface PostPatch {", "\n}")
	if contains(patch, "org_id") {
		t.Errorf("an immutable column should be absent from the patch body:\n%s", patch)
	}
	if !contains(patch, "title?: string;") {
		t.Errorf("every patch property is optional:\n%s", patch)
	}
}

// The operator vocabulary per column is the thing an OpenAPI document cannot
// say, and the reason this generator exists rather than openapi-typescript.
func TestTSFilterOperatorsAreNarrowedByColumnType(t *testing.T) {
	src := generateTS(t, tsFixture())["client.gen.ts"]
	where := section(t, src, "export type PostWhere = {", "\n};")

	for _, want := range []string{
		"org_id?: Cond<string>;",     // no pattern operators
		"status?: Cond<PostStatus>;", // an enum compares by equality
		"view_count?: Cond<number>;", // nor on a number
		// A timestamp gets the whole-day operator, and being nullable it gets
		// the null tests too — the extras compose rather than replacing one
		// another (#241).
		"published_at?: Cond<string | Date, DayMatch & NullCheck>;",
	} {
		if !contains(where, want) {
			t.Errorf("filter conditions missing %q:\n%s", want, where)
		}
	}
	// title is Searchable, which implies Filterable, and it is text — so it is
	// the one column that gets the pattern operators.
	if !contains(where, "title?: Cond<string, TextMatch>;") {
		t.Errorf("a text column should offer the pattern operators:\n%s", where)
	}
	// And the day operator is offered to nothing else: it is the one operator
	// whose absence used to be silent, so its presence must not be broad.
	for _, line := range []string{"id?:", "org_id?:", "title?:", "status?:", "view_count?:"} {
		for _, l := range strings.Split(where, "\n") {
			if strings.Contains(l, line) && strings.Contains(l, "DayMatch") {
				t.Errorf("a non-timestamp column offers the day operator:\n%s", l)
			}
		}
	}
}

func TestTSVocabulariesComeFromCapabilities(t *testing.T) {
	src := generateTS(t, tsFixture())["client.gen.ts"]

	sort := section(t, src, "export type PostSort =", ";")
	for _, want := range []string{"'title'", "'-title'", "'published_at'", "'-published_at'"} {
		if !contains(sort, want) {
			t.Errorf("sort union missing %s:\n%s", want, sort)
		}
	}
	// status is filterable but not sortable, so it has no spelling in ?sort.
	if contains(sort, "'status'") {
		t.Errorf("a column that did not opt in to sorting should not be sortable:\n%s", sort)
	}

	if !contains(src, "export type PostExpand = 'org';") {
		t.Errorf("the forward relation should be expandable:\n%s", src)
	}
	if !contains(src, "export type OrgExpand = 'posts';") {
		t.Errorf("the declared inverse should be expandable from the other side:\n%s", src)
	}
}

// Expansion narrows by direction: an object forward, a capped envelope back.
// Typing the reverse as a bare array would reproduce on the client the silent
// truncation the envelope exists to prevent on the server.
func TestTSExpansionKeepsTheCollectionEnvelope(t *testing.T) {
	src := generateTS(t, tsFixture())["client.gen.ts"]

	if !contains(src, "& ('org' extends E ? { org: Org } : unknown)") {
		t.Errorf("a forward expansion should resolve to the row type:\n%s", src)
	}
	if !contains(src, "& ('posts' extends E ? { posts: Collection<Post> } : unknown)") {
		t.Errorf("a reverse expansion should keep the Collection envelope:\n%s", src)
	}
}

// The envelope itself lives in the runtime now, once per output directory
// rather than once per module (#110). The property is unchanged — Page extends
// Collection rather than restating it — only its address is.
func TestTSPageEnvelopeExtendsCollection(t *testing.T) {
	src := generateTS(t, tsFixture())["runtime.gen.ts"]
	if !contains(src, "export interface Page<T> extends Collection<T> {") {
		t.Errorf("the page envelope should extend the collection rather than restate it:\n%s", src)
	}
}

func TestTSTransportFollowsTheExposedOperations(t *testing.T) {
	src := generateTS(t, tsFixture())["client.gen.ts"]

	for _, want := range []string{
		"export function listPosts<S extends PostColumn = PostColumn, E extends PostExpand = never>(",
		"path: '/posts', query: encodeListQuery(params)",
		"export function getPost<E extends PostExpand = never>(",
		"export function createPost(request: Transport, body: PostCreate",
		"export function updatePost(request: Transport, id: string | number, body: PostPatch",
		"export function deletePost(request: Transport, id: string | number",
	} {
		if !contains(src, want) {
			t.Errorf("transport missing %q:\n%s", want, src)
		}
	}
	// orgs expose read and list only, so nothing that writes one is emitted.
	for _, forbidden := range []string{"function createOrg", "function updateOrg", "function deleteOrg"} {
		if contains(src, forbidden) {
			t.Errorf("an unexposed operation should not be reachable: %s", forbidden)
		}
	}
	// The item endpoint declares no ?select, so the params type does not offer
	// one — a client that sends it gets a 400 from a server that rejects
	// unknown query parameters.
	get := section(t, src, "export interface PostGetParams<E extends PostExpand = never> {", "\n}")
	if contains(get, "select") {
		t.Errorf("the item endpoint has no ?select:\n%s", get)
	}
}

// TestTSWriteResultExcludesNeedsColumns is #188: a create or update cannot
// answer a Needs column — mutate.go has no per-request bind for it — so before
// this test's fix the row type still declared it NotNull and create/update
// were typed as returning that same row type. The lie compiled, because
// nothing about a wrong-but-well-shaped type fails tsc.
//
// computedFixture, from computed_test.go, is exactly this shape: is_starred
// carries Needs("viewer") and NotNull, is_overdue carries neither.
func TestTSWriteResultExcludesNeedsColumns(t *testing.T) {
	src := generateTS(t, computedFixture())["client.gen.ts"]

	// The read type still promises both — a read has a bind to resolve
	// is_starred with, so it can serve what it declares.
	row := section(t, src, "export interface Project {", "\n}")
	for _, want := range []string{"is_overdue", "is_starred"} {
		if !contains(row, want) {
			t.Errorf("read row type is missing %q:\n%s", want, row)
		}
	}

	// The write-result type exists because the table has a Needs column, and
	// it drops only that column — is_overdue has no bind problem and stays.
	if want := "export type ProjectWriteResult = Omit<Project, 'is_starred'>;"; !contains(src, want) {
		t.Errorf("write-result type missing or wrong, want %q:\n%s", want, src)
	}

	// create and update return the narrowed type, not the row type a read
	// returns.
	for _, want := range []string{
		"export function createProject(request: Transport, body: ProjectCreate, signal?: AbortSignal): Promise<ProjectWriteResult> {",
		"export function updateProject(request: Transport, id: string | number, body: ProjectPatch, signal?: AbortSignal): Promise<ProjectWriteResult> {",
	} {
		if !contains(src, want) {
			t.Errorf("write transport missing %q:\n%s", want, src)
		}
	}

	// get and list are reads: they still resolve against the full row type,
	// narrowed only by ?select — is_starred is reachable there, unlike from a
	// write.
	get := section(t, src, "export function getProject", "\n}")
	if !contains(get, "ProjectRow<ProjectColumn>") {
		t.Errorf("get should still return the row type narrowed by selection:\n%s", get)
	}
	if contains(get, "WriteResult") {
		t.Errorf("a read must not be typed as a write result:\n%s", get)
	}
}

func TestTSKeysAreDerivedFromTheTable(t *testing.T) {
	src := generateTS(t, tsFixture())["client.gen.ts"]

	for _, want := range []string{
		"export const postKeys = {",
		"all: () => ['posts'] as const,",
		"list: (params: unknown = {}) => ['posts', 'list', params] as const,",
		"detail: (id: string | number, params: unknown = {}) => ['posts', 'detail', String(id), params] as const,",
		// The table-keyed index is what makes a change-feed event mechanical:
		// one list, so a subscriber and a mutation handler cannot disagree.
		"export const keysByTable = {",
		"posts: postKeys,",
	} {
		if !contains(src, want) {
			t.Errorf("key factory missing %q:\n%s", want, src)
		}
	}
}

func TestTSQueriesAreTheOnlyFileThatNeedsTanStack(t *testing.T) {
	files := generateTS(t, tsFixture())
	client, queries := files["client.gen.ts"], files["queries.gen.ts"]

	// The client imports its own runtime and nothing else. That is the claim
	// worth holding: no framework, no bundler assumption, no pub package — a
	// sibling generated file is not a dependency (#110).
	for _, line := range strings.Split(client, "\n") {
		if !strings.HasPrefix(line, "import ") {
			continue
		}
		if !strings.Contains(line, "'./runtime.gen.ts'") {
			t.Errorf("the client imports something other than its runtime: %s", line)
		}
	}
	// And the runtime, which is what the client imports, imports nothing at all.
	if strings.Contains(files["runtime.gen.ts"], "import ") {
		t.Errorf("the runtime file should import nothing:\n%s", files["runtime.gen.ts"])
	}
	for _, want := range []string{
		"import { infiniteQueryOptions, mutationOptions, queryOptions } from '@tanstack/react-query';",
		"export function postQueries(request: Transport) {",
		"queryKey: postKeys.list(params),",
		"getNextPageParam: (last) => last.next_cursor,",
		// page and cursor are two answers to where a page starts, so the
		// infinite factory owns both rather than letting a caller send one.
		"infinite: <S extends PostColumn = PostColumn, E extends PostExpand = never>(params: Omit<PostListParams<S, E>, 'page' | 'cursor'> = {}) =>",
	} {
		if !contains(queries, want) {
			t.Errorf("queries missing %q:\n%s", want, queries)
		}
	}
}

// tsCode is the emitted TypeScript with its comments removed, for assertions
// about what the generator emits rather than about what it says.
func tsCode(src string) string {
	for {
		start := strings.Index(src, "/*")
		if start < 0 {
			break
		}
		end := strings.Index(src[start:], "*/")
		if end < 0 {
			break
		}
		src = src[:start] + src[start+end+2:]
	}
	var out []string
	for _, line := range strings.Split(src, "\n") {
		if strings.HasPrefix(strings.TrimSpace(line), "//") {
			continue
		}
		out = append(out, line)
	}
	return strings.Join(out, "\n")
}

// The mutation layer's whole claim is that it stops at mutationFn. A generated
// onSuccess would be a guess about which views an application keeps, and a
// guess is what gets copied out and edited (ADR-0028).
func TestTSMutationsCarryNoPolicy(t *testing.T) {
	queries := generateTS(t, tsFixture())["queries.gen.ts"]

	for _, want := range []string{
		"export function postMutations(request: Transport) {",
		"create: mutationOptions({ mutationFn: (body: PostCreate) => createPost(request, body), }),",
		// One variables object rather than two arguments, because mutate takes
		// exactly one.
		"update: mutationOptions({ mutationFn: ({ id, body }: { id: string | number; body: PostPatch }) => updatePost(request, id, body), }),",
		"delete: mutationOptions({ mutationFn: (id: string | number) => deletePost(request, id), }),",
	} {
		if !contains(queries, want) {
			t.Errorf("queries missing %q:\n%s", want, queries)
		}
	}

	// The refusal, stated as the absence it is. mutationKey is on this list
	// too: a key shape is expensive once anything consumes it, and nothing
	// here needs one. Comments are stripped first, because the doc comment
	// names onSuccess on purpose — showing the caller where their policy goes
	// is the point, and asserting against prose would forbid saying so.
	code := tsCode(queries)
	for _, unwanted := range []string{"onSuccess", "onError", "onSettled", "onMutate", "mutationKey", "invalidateQueries"} {
		if strings.Contains(code, unwanted) {
			t.Errorf("the mutation layer emitted %q, which is policy it cannot derive:\n%s", unwanted, queries)
		}
	}

	// orgs is read-only, so it has read options and no write options at all.
	if !strings.Contains(queries, "export function orgQueries(") {
		t.Error("the read-only resource lost its query factory")
	}
	if strings.Contains(queries, "orgMutations") {
		t.Errorf("a read-only resource acquired a mutations factory:\n%s", queries)
	}
}

// A declared verb is a write whose route the schema knows (ADR-0043), so
// leaving it out would make it the one mutation still hand-written.
func TestTSActionsReachTheMutationLayer(t *testing.T) {
	queries := generateTS(t, actionFixture())["queries.gen.ts"]

	for _, want := range []string{
		// An item verb with a body: both, in one variables object.
		"complete: mutationOptions({ mutationFn: ({ id, body }: { id: string | number; body: CompleteTaskInput }) => completeTask(request, id, body), }),",
		// An item verb without one: the id is the variables.
		"archive: mutationOptions({ mutationFn: (id: string | number) => archiveTask(request, id), }),",
		// A collection verb with neither: mutate() takes nothing.
		"purgeArchived: mutationOptions({ mutationFn: () => purgeArchivedTask(request), }),",
	} {
		if !contains(queries, want) {
			t.Errorf("queries missing %q:\n%s", want, queries)
		}
	}
}

// The TanStack import is computed from the body rather than fixed, because
// `noUnusedLocals` turns a name this file does not use into a build failure in
// the consumer's project — the same reason the client computes its runtime
// import (#110).
func TestTSTanStackImportNamesOnlyWhatIsUsed(t *testing.T) {
	readOnly := schema.NewRegistry()
	readOnly.Table("orgs",
		schema.UUIDv7("id").PrimaryKey(),
		schema.Text("name").Sortable(),
	).Expose(schema.REST{Ops: schema.OpRead | schema.OpList})

	queries := generateTS(t, readOnly)["queries.gen.ts"]
	if !strings.Contains(queries, "import { infiniteQueryOptions, queryOptions } from '@tanstack/react-query';") {
		t.Errorf("a read-only schema should import neither more nor less than it calls:\n%s", queries)
	}

	// And the other direction: a resource that only writes imports neither the
	// read helpers nor the key factory, which nothing in the file would name.
	writeOnly := schema.NewRegistry()
	writeOnly.Table("events",
		schema.UUIDv7("id").PrimaryKey(),
		schema.Text("kind"),
	).Expose(schema.REST{Ops: schema.OpCreate})

	queries = generateTS(t, writeOnly)["queries.gen.ts"]
	if !strings.Contains(queries, "import { mutationOptions } from '@tanstack/react-query';") {
		t.Errorf("a write-only schema should import only mutationOptions:\n%s", queries)
	}
	for _, unwanted := range []string{"eventKeys", "queryOptions", "eventQueries"} {
		if strings.Contains(queries, unwanted) {
			t.Errorf("a write-only resource pulled in %q, which nothing in the file uses:\n%s", unwanted, queries)
		}
	}
}

// No TSDir means no TypeScript, which is the right default for a project that
// has no TypeScript consumer.
func TestNoTypeScriptUnlessAsked(t *testing.T) {
	dir := t.TempDir()
	files, err := codegen.Generate(codegen.Options{Registry: tsFixture(), Dir: dir, Package: "gen"})
	if err != nil {
		t.Fatal(err)
	}
	for _, f := range files {
		if filepath.Ext(f) == ".ts" {
			t.Errorf("TypeScript was emitted without TSDir: %s", f)
		}
	}
}

// A schema with no REST surface has no client to generate, and a file of empty
// factories is worse than no file.
func TestNoQueriesFileWhenNothingIsExposed(t *testing.T) {
	r := schema.NewRegistry()
	r.Table("orgs", schema.UUIDv7("id").PrimaryKey(), schema.Text("name"))

	files := generateTS(t, r)
	if _, ok := files["queries.gen.ts"]; ok {
		t.Error("an unexposed schema should not get a TanStack file")
	}
	// The row types are still worth having: a table can be read from Go and
	// still be a shape the frontend has to name.
	if !contains(files["client.gen.ts"], "export interface Org {") {
		t.Error("row types should be emitted even with nothing exposed")
	}
}

// The TypeScript is part of the committed output, so the staleness gate has to
// see it — otherwise the client silently describes a schema the server no
// longer has.
func TestCheckSeesTheTypeScript(t *testing.T) {
	dir := t.TempDir()
	opts := codegen.Options{Registry: tsFixture(), Dir: dir, Package: "gen", TSDir: "web/api"}
	if _, err := codegen.Generate(opts); err != nil {
		t.Fatal(err)
	}
	if stale, err := codegen.Check(opts); err != nil || len(stale) > 0 {
		t.Fatalf("freshly generated output should be current: %v %v", stale, err)
	}

	path := filepath.Join(dir, "web", "api", "client.gen.ts")
	if err := os.WriteFile(path, []byte("// edited by hand\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	stale, err := codegen.Check(opts)
	if err != nil {
		t.Fatal(err)
	}
	if len(stale) != 1 || !strings.Contains(stale[0], "client.gen.ts") {
		t.Errorf("an edited client should be reported stale, got %v", stale)
	}
}

// section returns the emitted text between two markers, so an assertion about
// one declaration cannot be satisfied by a match somewhere else in the file.
func section(t *testing.T, src, from, to string) string {
	t.Helper()
	start := strings.Index(src, from)
	if start < 0 {
		t.Fatalf("%q not found in:\n%s", from, src)
	}
	rest := src[start:]
	end := strings.Index(rest, to)
	if end < 0 {
		t.Fatalf("%q not found after %q", to, from)
	}
	return rest[:end+len(to)]
}

func oneToOneTSFixture() *schema.Registry {
	r := schema.NewRegistry()
	users := r.Table("users", schema.UUIDv7("id").PrimaryKey())
	r.Table("profiles",
		schema.UUIDv7("id").PrimaryKey(),
		schema.Ref("user", users).Unique().
			Expandable().Inverse("profile").InverseExpandable(),
	)
	return r
}

func TestTSOneToOneInverseIsNullableObjectNotCollection(t *testing.T) {
	files := generateTS(t, oneToOneTSFixture())
	client := files["client.gen.ts"]
	if !contains(client, `profile?: Profile | null;`) {
		t.Errorf("one-to-one inverse should type as Profile | null, got:\n%s", client)
	}
	if contains(client, "profile?: Collection<Profile>") {
		t.Errorf("one-to-one inverse must not use the Collection<T> envelope:\n%s", client)
	}
}

// Guard-proven-both-ways companion — ordinary inverse relations keep their
// existing Collection<T> shape.
func TestTSNonUniqueInverseStillUsesCollection(t *testing.T) {
	files := generateTS(t, tsFixture())
	client := files["client.gen.ts"]
	if !contains(client, "Collection<Post>") {
		t.Errorf("non-unique inverse should still use Collection<Post>, got:\n%s", client)
	}
}

// A capped collection's row-interface doc comment used to split across two
// adjacent `/** */` blocks, of which TS tooling only surfaces the second on
// hover — silently dropping "Filled in by `expand`" for every ordinary
// collection relation. It has to be one block.
func TestTSCollectionDocCommentIsOneBlock(t *testing.T) {
	files := generateTS(t, tsFixture())
	client := files["client.gen.ts"]
	if !contains(client, "/** Filled in by `expand: ['posts']`, absent otherwise. Capped at 50 rows. */") {
		t.Errorf("collection relation's doc comment should be one merged block, got:\n%s", client)
	}
	if contains(client, "/** Filled in by `expand: ['posts']`, absent otherwise. */\n  /** Capped at 50 rows. */") {
		t.Errorf("collection relation's doc comment should not split into two adjacent blocks:\n%s", client)
	}
}

// The subscriber is the other half of the key factory: a change carries a
// table and a row key ([ADR-0012]), and this is the code that turns that pair
// into the queries to refetch rather than leaving every consumer to write the
// mapping by hand.
func TestTSSubscriberResolvesAChangeToItsKeys(t *testing.T) {
	src := generateTS(t, tsFixture())["client.gen.ts"]

	for _, want := range []string{
		"export interface TableChange {",
		"export function isTableName(table: string): table is TableName {",
		"export function changeKeys(event: ChangeEvent): readonly (readonly unknown[])[] {",
		"export function subscribeChanges(",
		// The precision the derivation exists for: one row's detail, not the
		// table's. Invalidating `all` would throw away every other row on the
		// screen for a change to one of them.
		"      : [postKeys.lists(), postKeys.infinites(), postKeys.detail(key)],",
		// A keyless event is the shape a publisher that could not attribute a
		// delete to one row produces, and it means "the table changed".
		"      ? [postKeys.all()]",
		// The prefix factory the derivation needs, which is also the sibling
		// `infinite` had been missing.
		"infinites: () => ['posts', 'infinite'] as const,",
	} {
		if !contains(src, want) {
			t.Errorf("the subscriber is missing %q:\n%s", want, src)
		}
	}
}

// A singleton has no collection and no row to address, so the same derivation
// would name three factories it does not have. It gets its own key instead —
// the one thing it has.
func TestTSSubscriberHasNoListKeysForASingleton(t *testing.T) {
	src := generateTS(t, singletonFixture())["client.gen.ts"]

	if want := "  billing_subscriptions: () => [billingSubscriptionKeys.all()],"; !contains(src, want) {
		t.Errorf("the singleton's invalidation is missing %q:\n%s", want, src)
	}
	for _, forbidden := range []string{"billingSubscriptionKeys.lists()", "billingSubscriptionKeys.detail("} {
		if contains(src, forbidden) {
			t.Errorf("the singleton's invalidation names %q, which its key factory does not offer:\n%s", forbidden, src)
		}
	}
}

// The split the runtime file exists for, applied to the stream: the wire
// format and the EventSource wiring depend on no schema, so two modules share
// one copy and one ChangeEvent rather than each declaring its own.
func TestTSStreamWiringIsInTheRuntime(t *testing.T) {
	files := generateTS(t, tsFixture())
	runtime, client := files["runtime.gen.ts"], files["client.gen.ts"]

	for _, want := range []string{
		"export interface ChangeEvent {",
		"export interface ResetEvent {",
		"export type ChangeOp = 'create' | 'update' | 'delete';",
		"export function subscribeEvents(",
		"export interface EventStream {",
	} {
		if !contains(runtime, want) {
			t.Errorf("the runtime is missing %q:\n%s", want, runtime)
		}
	}

	// The runtime is derived from nothing schema-specific, and the stream is
	// where that is easiest to break: an event names a table, and a table is
	// exactly what this file must not know about.
	if contains(runtime, "posts") {
		t.Errorf("the runtime names a table, so two schemas would not render the same bytes:\n%s", runtime)
	}

	// And the client reaches it by import rather than by declaring a second
	// copy, which the import list computes from what the body actually uses.
	if !contains(client, "subscribeEvents") {
		t.Errorf("the client does not use the runtime's subscriber:\n%s", client)
	}
	if contains(client, "export function subscribeEvents(") {
		t.Errorf("the client declares its own subscriber rather than importing one:\n%s", client)
	}
}
