package codegen_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/mind-vm/sqlb/codegen"
	"github.com/mind-vm/sqlb/schema"
)

// wiringFixture is a named module with a migration history and one exposed
// resource — the shape a real consumer's <mod>data package is in.
func wiringFixture() *schema.Registry {
	r := schema.NewModule("store")
	r.Table("notes",
		schema.UUIDv7("id").PrimaryKey(),
		schema.Text("title").Searchable().Sortable(),
	).Expose(schema.REST{Path: "/notes", Ops: schema.CRUD | schema.OpList})
	return r
}

func wiringOpts(dir string, r *schema.Registry) codegen.Options {
	return codegen.Options{
		Registry: r, Dir: dir, Package: "store",
		ClientImportPath: "example.com/app/cli/client",
		WiringMigrations: codegen.WiringSet{
			Type:     "github.com/mind-vm/sqlb/example/fxapp/fxkit.MigrationSet",
			Group:    "fxkit.migrations",
			EmbedDir: "migrations",
		},
		WiringOperations: codegen.WiringSet{
			Type:  "github.com/mind-vm/sqlb/example/fxapp/fxkit.OperationSet",
			Group: "fxkit.operations",
		},
	}
}

// TestWiringEmitsBothContributions is the golden-shape assertion: an
// fx.Provide(fx.Annotate(...)) per configured WiringSet, joining the group
// named in config, with the host's own type referenced by the exact string
// configured — nothing sqlb invented.
func TestWiringEmitsBothContributions(t *testing.T) {
	dir := t.TempDir()
	opts := wiringOpts(dir, wiringFixture())
	if _, err := codegen.Generate(opts); err != nil {
		t.Fatalf("Generate: %v", err)
	}
	b, err := os.ReadFile(filepath.Join(dir, "wiring_gen.go"))
	if err != nil {
		t.Fatalf("reading wiring_gen.go: %v", err)
	}
	got := string(b)

	for _, want := range []string{
		"// Code generated by github.com/mind-vm/sqlb. DO NOT EDIT.",
		"package store",
		`"github.com/mind-vm/sqlb/example/fxapp/fxkit"`,
		`"go.uber.org/fx"`,
		"//go:embed migrations/*.sql",
		"var wiringMigrationsFS embed.FS",
		"var FxModule = fx.Options(",
		"func() fxkit.MigrationSet {",
		"return fxkit.MigrationSet{",
		`Module: "store",`,
		"FS:     wiringMigrationsFS,",
		`Dir:    "migrations",`,
		"fx.ResultTags(`group:\"fxkit.migrations\"`)",
		"func(db *sqlb.DB) fxkit.OperationSet {",
		"return fxkit.OperationSet{",
		`Module:   "store",`,
		"Register: func(api huma.API) error { return Register(api, db) },",
		"fx.ResultTags(`group:\"fxkit.operations\"`)",
	} {
		if !contains(got, want) {
			t.Errorf("wiring_gen.go missing %q:\n%s", want, got)
		}
	}

	// Nothing of sqlb's own beyond what the generated package already
	// depends on — this is the deps-check property, checked at the source
	// level rather than by building a second module: every import is either
	// the host's configured type, fx, huma (needed by Register's own
	// signature) or sqlb itself.
	for _, imp := range []string{
		`"embed"`,
		`"github.com/danielgtaylor/huma/v2"`,
		`"github.com/mind-vm/sqlb"`,
		`"github.com/mind-vm/sqlb/example/fxapp/fxkit"`,
		`"go.uber.org/fx"`,
	} {
		if !strings.Contains(got, imp) {
			t.Errorf("expected import %s, got:\n%s", imp, got)
		}
	}
	if strings.Contains(got, "sqlbfx") {
		t.Errorf("the generated file references sqlbfx, which is exactly the runtime dependency this design avoids:\n%s", got)
	}
}

// TestWiringSkipsOperationsWithNoRESTSurface mirrors RestFile's own rule: an
// operations WiringSet with nothing to mount is silently omitted rather than
// emitting a call to a Register function that does not exist.
func TestWiringSkipsOperationsWithNoRESTSurface(t *testing.T) {
	r := schema.NewModule("jobs")
	r.Table("jobs", schema.UUIDv7("id").PrimaryKey(), schema.Text("state"))

	dir := t.TempDir()
	opts := wiringOpts(dir, r)
	if _, err := codegen.Generate(opts); err != nil {
		t.Fatalf("Generate: %v", err)
	}
	b, err := os.ReadFile(filepath.Join(dir, "wiring_gen.go"))
	if err != nil {
		t.Fatalf("reading wiring_gen.go: %v", err)
	}
	got := string(b)
	if strings.Contains(got, "OperationSet") {
		t.Errorf("no resource is exposed, so no operations contribution should be emitted:\n%s", got)
	}
	if !strings.Contains(got, "MigrationSet") {
		t.Errorf("the migrations contribution should still be emitted:\n%s", got)
	}
}

// TestWiringEmitsNothingWithNoWiringSetConfigured is the opt-in gate: setting
// WiringDir alone, with both WiringSets at their zero value, writes no file —
// the same shape SkillDir uses for its own opt-in.
func TestWiringEmitsNothingWithNoWiringSetConfigured(t *testing.T) {
	dir := t.TempDir()
	if _, err := codegen.Generate(codegen.Options{
		Registry: wiringFixture(), Dir: dir, Package: "store",
		ClientImportPath: "example.com/app/cli/client",
		WiringDir:        "wiring",
	}); err != nil {
		t.Fatalf("Generate: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, "wiring", "wiring_gen.go")); !os.IsNotExist(err) {
		t.Errorf("a wiring file appeared with no WiringSet configured (err=%v)", err)
	}
}

// TestWiringRequiresNameForAnUnnamedRegistry is the second gap the issue
// names: a schema.NewRegistry() registry can be genuinely unnamed on purpose,
// and generation must refuse rather than emit an unnamed contributor — the
// same posture SkillName's own validation takes.
func TestWiringRequiresNameForAnUnnamedRegistry(t *testing.T) {
	r := schema.NewRegistry()
	r.Table("notifications", schema.UUIDv7("id").PrimaryKey(), schema.Text("body")).
		Expose(schema.REST{Ops: schema.OpList})

	_, err := codegen.Generate(codegen.Options{
		Registry: r, Dir: t.TempDir(), Package: "notifications",
		WiringOperations: codegen.WiringSet{
			Type: "github.com/mind-vm/sqlb/example/fxapp/fxkit.OperationSet", Group: "fxkit.operations",
		},
	})
	if err == nil {
		t.Fatal("expected an error: the registry is unnamed and WiringOperations.Name was not set")
	}
	if !strings.Contains(err.Error(), "WiringOperations.Name") {
		t.Errorf("the error does not name the option to fix: %v", err)
	}

	// Naming it explicitly is exactly the escape hatch — "druschba-notifications"
	// in the issue's own example, a name the table itself does not carry.
	_, err = codegen.Generate(codegen.Options{
		Registry: r, Dir: t.TempDir(), Package: "notifications",
		WiringOperations: codegen.WiringSet{
			Type: "github.com/mind-vm/sqlb/example/fxapp/fxkit.OperationSet", Group: "fxkit.operations",
			Name: "druschba-notifications",
		},
	})
	if err != nil {
		t.Errorf("an explicit Name should be accepted for an unnamed registry: %v", err)
	}
}

// TestWiringRejectsActionsAndQueries is the honest scope limit: Register
// needs hand-written Actions/Queries funcs when the schema declares either,
// and this emitter has no way to supply them, so it refuses rather than
// generating a call that fails to compile.
func TestWiringRejectsActionsAndQueries(t *testing.T) {
	r := schema.NewModule("store")
	tbl := r.Table("notes", schema.UUIDv7("id").PrimaryKey(), schema.Text("title"))
	tbl.Expose(schema.REST{Ops: schema.OpList | schema.OpRead}).
		AddAction(schema.Action{Name: "archive", Writes: []string{"title"}})

	_, err := codegen.Generate(codegen.Options{
		Registry: r, Dir: t.TempDir(), Package: "store",
		WiringOperations: codegen.WiringSet{
			Type: "github.com/mind-vm/sqlb/example/fxapp/fxkit.OperationSet", Group: "fxkit.operations",
		},
	})
	if err == nil {
		t.Fatal("expected an error: the schema declares an action, which Register needs a hand-written func for")
	}
	if !strings.Contains(err.Error(), "actions") {
		t.Errorf("the error does not explain the limit: %v", err)
	}
}

// TestWiringValidatesEmbedDirPlacement checks the structural rules: EmbedDir
// is required on WiringMigrations and refused on WiringOperations, because it
// is the field that marks which contribution a WiringSet is.
func TestWiringValidatesEmbedDirPlacement(t *testing.T) {
	base := func() codegen.Options {
		return codegen.Options{Registry: wiringFixture(), Dir: t.TempDir(), Package: "store"}
	}

	t.Run("migrations without EmbedDir", func(t *testing.T) {
		opts := base()
		opts.WiringMigrations = codegen.WiringSet{
			Type: "github.com/mind-vm/sqlb/example/fxapp/fxkit.MigrationSet", Group: "fxkit.migrations",
		}
		if _, err := codegen.Generate(opts); err == nil || !strings.Contains(err.Error(), "EmbedDir") {
			t.Errorf("expected an EmbedDir error, got %v", err)
		}
	})

	t.Run("operations with EmbedDir set", func(t *testing.T) {
		opts := base()
		opts.WiringOperations = codegen.WiringSet{
			Type: "github.com/mind-vm/sqlb/example/fxapp/fxkit.OperationSet", Group: "fxkit.operations",
			EmbedDir: "migrations",
		}
		if _, err := codegen.Generate(opts); err == nil || !strings.Contains(err.Error(), "WiringOperations.EmbedDir") {
			t.Errorf("expected a WiringOperations.EmbedDir error, got %v", err)
		}
	})

	t.Run("missing Group", func(t *testing.T) {
		opts := base()
		opts.WiringOperations = codegen.WiringSet{
			Type: "github.com/mind-vm/sqlb/example/fxapp/fxkit.OperationSet",
		}
		if _, err := codegen.Generate(opts); err == nil || !strings.Contains(err.Error(), "Group") {
			t.Errorf("expected a Group error, got %v", err)
		}
	})

	t.Run("Type is not fully qualified", func(t *testing.T) {
		opts := base()
		opts.WiringOperations = codegen.WiringSet{Type: "OperationSet", Group: "fxkit.operations"}
		if _, err := codegen.Generate(opts); err == nil || !strings.Contains(err.Error(), "Type") {
			t.Errorf("expected a Type error, got %v", err)
		}
	})
}

// TestTwoModulesWiringDoesNotCollide is #142's guard, transplanted: two
// registries each generating into their own Options.Dir must not step on one
// another's wiring file, which — unlike SkillDir — is not even a shared
// directory by default, so this is really asserting that nothing was wired to
// make it one.
func TestTwoModulesWiringDoesNotCollide(t *testing.T) {
	notes := schema.NewModule("notes")
	notes.Table("notes", schema.UUIDv7("id").PrimaryKey(), schema.Text("title")).
		Expose(schema.REST{Path: "/notes", Ops: schema.OpList})

	tasks := schema.NewModule("tasks")
	tasks.Table("tasks", schema.UUIDv7("id").PrimaryKey(), schema.Text("title")).
		Expose(schema.REST{Path: "/tasks", Ops: schema.OpList})

	root := t.TempDir()
	optsFor := func(r *schema.Registry, name string) codegen.Options {
		o := wiringOpts(filepath.Join(root, name), r)
		o.WiringOperations.Type = "" // migrations only, keep the fixture simple
		return o
	}

	for _, o := range []codegen.Options{optsFor(notes, "notes"), optsFor(tasks, "tasks")} {
		if _, err := codegen.Generate(o); err != nil {
			t.Fatalf("Generate: %v", err)
		}
	}

	notesWiring := readFile(t, filepath.Join(root, "notes", "wiring_gen.go"))
	tasksWiring := readFile(t, filepath.Join(root, "tasks", "wiring_gen.go"))
	if !contains(notesWiring, `Module: "notes",`) {
		t.Errorf("notes wiring does not name itself:\n%s", notesWiring)
	}
	if !contains(tasksWiring, `Module: "tasks",`) {
		t.Errorf("tasks wiring does not name itself:\n%s", tasksWiring)
	}
	if notesWiring == tasksWiring {
		t.Error("two distinct modules produced byte-identical wiring, which cannot be right")
	}

	// And both checks are clean, which is the real assertion: nothing about
	// generating one disturbed the other.
	for _, o := range []codegen.Options{optsFor(notes, "notes"), optsFor(tasks, "tasks")} {
		stale, err := codegen.Check(o)
		if err != nil {
			t.Fatalf("Check: %v", err)
		}
		if len(stale) != 0 {
			t.Errorf("a freshly generated tree is not current: %v", stale)
		}
	}
}

// TestCheckCatchesDriftedWiring is the drift gate, exercised the way
// TestCheckCatchesADriftedSkill exercises the skill's.
func TestCheckCatchesDriftedWiring(t *testing.T) {
	dir := t.TempDir()
	opts := wiringOpts(dir, wiringFixture())
	if _, err := codegen.Generate(opts); err != nil {
		t.Fatalf("Generate: %v", err)
	}
	name := filepath.Join(dir, "wiring_gen.go")

	stale, err := codegen.Check(opts)
	if err != nil {
		t.Fatalf("Check: %v", err)
	}
	if len(stale) != 0 {
		t.Fatalf("a freshly generated tree is not current: %v", stale)
	}

	if err := os.WriteFile(name, []byte("package store\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	stale, err = codegen.Check(opts)
	if err != nil {
		t.Fatalf("Check after editing: %v", err)
	}
	var found bool
	for _, s := range stale {
		if strings.Contains(s, "wiring_gen.go") {
			found = true
		}
	}
	if !found {
		t.Errorf("check did not report the edited wiring file as stale, got %v", stale)
	}
}

// TestWiringIsDeterministic guards the same property TestSkillIsDeterministic
// does: Check compares byte for byte, so any nondeterminism makes the gate
// fail at random rather than on a real edit.
func TestWiringIsDeterministic(t *testing.T) {
	render := func() string {
		dir := t.TempDir()
		opts := wiringOpts(dir, wiringFixture())
		if _, err := codegen.Generate(opts); err != nil {
			t.Fatalf("Generate: %v", err)
		}
		return readFile(t, filepath.Join(dir, "wiring_gen.go"))
	}
	first := render()
	for range 5 {
		if next := render(); next != first {
			t.Fatalf("two renders of one schema differ:\n%s\n---\n%s", first, next)
		}
	}
}

// TestWiringDirIsModuleLocalByDefault asserts the property the issue and
// CLAUDE.md both call out by name: with WiringDir unset, the file lands
// directly in Options.Dir rather than defaulting to some shared location.
func TestWiringDirIsModuleLocalByDefault(t *testing.T) {
	dir := t.TempDir()
	opts := wiringOpts(dir, wiringFixture())
	if _, err := codegen.Generate(opts); err != nil {
		t.Fatalf("Generate: %v", err)
	}
	if _, err := os.Stat(filepath.Join(dir, "wiring_gen.go")); err != nil {
		t.Errorf("expected wiring_gen.go directly in Dir with WiringDir unset: %v", err)
	}
}
