// Code generated by github.com/mind-vm/sqlb. DO NOT EDIT.

package vault

import "time"

// Secret a secret whose payload only Go may write; see store.go.
type Secret struct {
	ID         string    `db:"id" json:"id" sqlb:"type:uuid,pk,default,filter,readonly"`
	OwnerKind  string    `db:"owner_kind" json:"owner_kind" sqlb:"type:text,filter"`
	OwnerID    string    `db:"owner_id" json:"owner_id" sqlb:"type:uuid,filter"`
	Ciphertext []byte    `db:"ciphertext" json:"-" sqlb:"type:bytea,hidden"`
	Nonce      []byte    `db:"nonce" json:"-" sqlb:"type:bytea,hidden"`
	KeyVersion int32     `db:"key_version" json:"-" sqlb:"type:int,hidden"`
	CreatedAt  time.Time `db:"created_at" json:"created_at" sqlb:"type:timestamptz,default,sort,readonly"`
	UpdatedAt  time.Time `db:"updated_at" json:"updated_at" sqlb:"type:timestamptz,default,sort,readonly"`
}

// TableName is the table Secret maps to.
func (Secret) TableName() string { return "secrets" }
