package migrate_test

import (
	"fmt"

	"github.com/mind-vm/sqlb/migrate"
	"github.com/mind-vm/sqlb/schema"
)

// Diff compares the schema a database currently has against the one the code
// declares, and returns the changes between them. It is a pure function over two
// registries: nothing is read from a database and nothing is applied.
func ExampleDiff() {
	current := schema.NewRegistry()
	current.Table("posts",
		schema.UUIDv7("id").PrimaryKey(),
		schema.Text("title"),
	)

	// The same table after someone added a column to the schema file.
	target := schema.NewRegistry()
	target.Table("posts",
		schema.UUIDv7("id").PrimaryKey(),
		schema.Text("title"),
		schema.BigInt("view_count").Default(schema.Value(0)),
	)

	changes, err := migrate.Diff(current, target)
	if err != nil {
		panic(err)
	}
	for _, c := range changes {
		fmt.Println(c.Up)
		fmt.Println(c.Down)
	}
	// Output:
	// ALTER TABLE "posts" ADD COLUMN "view_count" bigint NOT NULL DEFAULT 0;
	// ALTER TABLE "posts" DROP COLUMN "view_count";
}

// A change that can lose data is marked Destructive and carries the reason.
// Rendering emits it commented out, so applying it is a deliberate act rather
// than something a generated file does on your behalf.
func ExampleDiff_destructive() {
	current := schema.NewRegistry()
	current.Table("posts",
		schema.UUIDv7("id").PrimaryKey(),
		schema.Text("title"),
		schema.Text("legacy_slug"),
	)

	target := schema.NewRegistry()
	target.Table("posts",
		schema.UUIDv7("id").PrimaryKey(),
		schema.Text("title"),
	)

	changes, err := migrate.Diff(current, target)
	if err != nil {
		panic(err)
	}
	for _, c := range changes {
		fmt.Println(c.Up)
		fmt.Println("destructive:", c.Destructive)
		fmt.Println("reason:", c.Reason)
	}
	// Output:
	// ALTER TABLE "posts" DROP COLUMN "legacy_slug";
	// destructive: true
	// reason: dropping posts.legacy_slug deletes its contents. The Down restores the column but not the values
}

// A rename is declared, never inferred: a drop plus an add is indistinguishable
// from a rename when only the before and after states are known, and guessing
// wrong destroys data. RenamedFrom is the declaration, and it is needed for
// exactly one release.
func ExampleDiff_rename() {
	current := schema.NewRegistry()
	current.Table("authors",
		schema.UUIDv7("id").PrimaryKey(),
		schema.Text("email"),
	)

	target := schema.NewRegistry()
	target.Table("authors",
		schema.UUIDv7("id").PrimaryKey(),
		schema.Text("email_address").RenamedFrom("email"),
	)

	changes, err := migrate.Diff(current, target)
	if err != nil {
		panic(err)
	}
	for _, c := range changes {
		fmt.Println(c.Up)
	}
	// Output:
	// ALTER TABLE "authors" RENAME COLUMN "email" TO "email_address";
}

// Render turns a migration into the files a runner expects. sqlb does not apply
// migrations and does not track which have run: your existing runner does that,
// and replacing a working one is a far larger ask than adopting a generator.
func ExampleRender() {
	m := migrate.Migration{
		Version: "20260727120000",
		Name:    "add_view_count",
		Changes: []migrate.Change{{
			Comment: "posts.view_count",
			Up:      `ALTER TABLE "posts" ADD COLUMN "view_count" bigint NOT NULL DEFAULT 0;`,
			Down:    `ALTER TABLE "posts" DROP COLUMN "view_count";`,
		}},
	}

	files, err := migrate.Render(m, migrate.Options{Format: migrate.Goose})
	if err != nil {
		panic(err)
	}
	for name, body := range files {
		fmt.Println("--", name)
		fmt.Println(body)
	}
	// Output:
	// -- 20260727120000_add_view_count.sql
	// -- Generated by sqlb. Review before applying.
	//
	// -- +goose Up
	// -- posts.view_count
	// ALTER TABLE "posts" ADD COLUMN "view_count" bigint NOT NULL DEFAULT 0;
	//
	// -- +goose Down
	// ALTER TABLE "posts" DROP COLUMN "view_count";
}
