package migrate_test

import (
	"strings"
	"testing"

	"github.com/mind-vm/sqlb/migrate"
	"github.com/mind-vm/sqlb/schema"
)

func diffOf(t *testing.T, current, target *schema.Registry) []migrate.Change {
	t.Helper()
	changes, err := migrate.Diff(current, target)
	if err != nil {
		t.Fatalf("Diff: %v", err)
	}
	return changes
}

func upOf(changes []migrate.Change) string {
	var b strings.Builder
	for _, c := range changes {
		b.WriteString(c.Up)
		b.WriteString("\n")
	}
	return b.String()
}

// A serial is rendered as its own type name and an identity as a clause, which
// is how Postgres spells them — and in a CREATE TABLE the serial is what makes
// the sequence exist at all.
func TestAutoColumnDDL(t *testing.T) {
	r := schema.NewRegistry()
	r.Table("audit_log",
		schema.BigSerial("id").PrimaryKey(),
		schema.SmallSerial("bucket"),
		schema.Serial("n"),
		schema.Text("action"),
	)
	r.Table("steps",
		schema.BigInt("seq").Identity().PrimaryKey(),
		schema.Int("attempt").IdentityAlways(),
	)

	up := upOf(diffOf(t, nil, r))
	for _, want := range []string{
		`"id" bigserial NOT NULL`,
		`"bucket" smallserial NOT NULL`,
		`"n" serial NOT NULL`,
		`"seq" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY`,
		`"attempt" integer NOT NULL GENERATED ALWAYS AS IDENTITY`,
	} {
		if !strings.Contains(up, want) {
			t.Errorf("DDL missing %s:\n%s", want, up)
		}
	}
	// No DEFAULT beside either: the sequence is the default, and Postgres
	// refuses a column carrying both.
	if strings.Contains(up, "DEFAULT nextval") {
		t.Errorf("a declared serial rendered a nextval default, which names a sequence nothing creates:\n%s", up)
	}
}

// The storage type stays the storage type. `bigserial` is a macro for a bigint
// and a sequence, not a type — so a schema diffed against itself has nothing to
// say, where a serial leaking into the type function would propose changing
// bigint to bigserial forever.
func TestSerialIsNotAType(t *testing.T) {
	r := schema.NewRegistry()
	r.Table("audit_log", schema.BigSerial("id").PrimaryKey(), schema.Text("action"))
	if changes := diffOf(t, r, r); len(changes) != 0 {
		t.Errorf("a serial schema diffed against itself proposes %d change(s):\n%s", len(changes), upOf(changes))
	}
}

// A column added to a live table: `ALTER TABLE … ADD COLUMN … bigserial` makes
// Postgres create the sequence too, so the add needs nothing the create did not.
func TestSerialColumnAdded(t *testing.T) {
	before := schema.NewRegistry()
	before.Table("audit_log", schema.UUIDv7("id").PrimaryKey())
	after := schema.NewRegistry()
	after.Table("audit_log", schema.UUIDv7("id").PrimaryKey(), schema.BigSerial("n"))

	up := upOf(diffOf(t, before, after))
	if !strings.Contains(up, `ADD COLUMN "n" bigserial`) {
		t.Errorf("DDL does not add the column as a serial:\n%s", up)
	}
}

// A column that starts or stops being supplied by a sequence. The two spellings
// are not symmetric and the asymmetry is Postgres's: an identity is an attribute
// of the column, a serial is three objects wearing one name.
func TestAutoTransitions(t *testing.T) {
	plain := func() *schema.Field { return schema.BigInt("id") }
	for _, tc := range []struct {
		name     string
		from, to *schema.Field
		want     []string
		hazard   string
	}{
		{
			name: "to identity", from: plain(), to: schema.BigInt("id").Identity(),
			want:   []string{`ADD GENERATED BY DEFAULT AS IDENTITY`},
			hazard: "RESTART WITH",
		},
		{
			name: "from identity", from: schema.BigInt("id").Identity(), to: plain(),
			want: []string{`DROP IDENTITY`},
		},
		{
			name: "by default to always", from: schema.BigInt("id").Identity(), to: schema.BigInt("id").IdentityAlways(),
			want: []string{`DROP IDENTITY`, `ADD GENERATED ALWAYS AS IDENTITY`},
		},
		{
			name: "to serial", from: plain(), to: schema.BigInt("id").Serial(),
			// Three objects: the sequence, the default that draws from it, and
			// the ownership that ties the two to the column.
			want:   []string{`CREATE SEQUENCE "t_id_seq" OWNED BY "t"."id"`, `SET DEFAULT nextval('t_id_seq')`},
			hazard: "setval",
		},
		{
			name: "from serial", from: schema.BigInt("id").Serial(), to: plain(),
			want:   []string{`DROP DEFAULT`},
			hazard: "left behind rather than dropped",
		},
		{
			name: "serial to identity", from: schema.BigInt("id").Serial(), to: schema.BigInt("id").Identity(),
			want: []string{`DROP DEFAULT`, `ADD GENERATED BY DEFAULT AS IDENTITY`},
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			before := schema.NewRegistry()
			before.Table("t", tc.from.PrimaryKey(), schema.Text("x"))
			after := schema.NewRegistry()
			after.Table("t", tc.to.PrimaryKey(), schema.Text("x"))

			changes := diffOf(t, before, after)
			up := upOf(changes)
			for _, want := range tc.want {
				if !strings.Contains(up, want) {
					t.Errorf("DDL missing %s:\n%s", want, up)
				}
			}
			// A type change would rewrite the table, and nothing about this is
			// a type change — both sides are bigint.
			if strings.Contains(up, "TYPE bigint") {
				t.Errorf("a change of auto-ness proposed a type change:\n%s", up)
			}
			if tc.hazard == "" {
				return
			}
			// Setting the sequence past the rows already there is the step
			// nothing here can generate — the count is not in the schema — and
			// getting it wrong is a duplicate key on the next insert rather
			// than a slow migration.
			var found bool
			for _, c := range changes {
				if strings.Contains(c.Hazard, tc.hazard) {
					found = true
				}
			}
			if !found {
				t.Errorf("no change carries a hazard mentioning %q; the sequence would start at 1 "+
					"on a table that already has rows", tc.hazard)
			}
		})
	}
}

// Every transition reverses. A migration that cannot be rolled back is one
// nobody applies on a Friday.
func TestAutoTransitionsReverse(t *testing.T) {
	for _, tc := range []struct {
		name     string
		from, to *schema.Field
	}{
		{"to identity", schema.BigInt("id"), schema.BigInt("id").Identity()},
		{"to serial", schema.BigInt("id"), schema.BigInt("id").Serial()},
		{"serial to identity", schema.BigInt("id").Serial(), schema.BigInt("id").Identity()},
	} {
		t.Run(tc.name, func(t *testing.T) {
			before := schema.NewRegistry()
			before.Table("t", tc.from.PrimaryKey())
			after := schema.NewRegistry()
			after.Table("t", tc.to.PrimaryKey())
			for _, c := range diffOf(t, before, after) {
				if strings.TrimSpace(c.Down) == "" {
					t.Errorf("%q has no Down", c.Comment)
				}
			}
		})
	}
}
