// Code generated by github.com/mind-vm/sqlb. DO NOT EDIT.

package tasks

import (
	"time"

	"github.com/mind-vm/sqlb"
)

type commentColumns struct {
	ID          sqlb.Col[string]
	WorkspaceID sqlb.Col[string]
	TaskID      sqlb.Col[string]
	AuthorID    sqlb.Col[string]
	Body        sqlb.TextCol[string]
	CreatedAt   sqlb.Col[time.Time]
	UpdatedAt   sqlb.Col[time.Time]
	DeletedAt   sqlb.Col[time.Time]
}

// CommentCols are the typed columns of comments.
var CommentCols = commentColumns{
	ID:          sqlb.Typed[string]("id"),
	WorkspaceID: sqlb.Typed[string]("workspace_id"),
	TaskID:      sqlb.Typed[string]("task_id"),
	AuthorID:    sqlb.Typed[string]("author_id"),
	Body:        sqlb.TextColumn[string]("body"),
	CreatedAt:   sqlb.Typed[time.Time]("created_at"),
	UpdatedAt:   sqlb.Typed[time.Time]("updated_at"),
	DeletedAt:   sqlb.Typed[time.Time]("deleted_at"),
}

// CommentUpdate is a typed update statement for comments.
type CommentUpdate struct {
	stmt *sqlb.Update[Comment]
}

// UpdateComment starts a typed update.
func UpdateComment() *CommentUpdate {
	return &CommentUpdate{stmt: sqlb.UpdateRows[Comment]()}
}

// SetWorkspaceID sets workspace_id.
func (u *CommentUpdate) SetWorkspaceID(v string) *CommentUpdate {
	u.stmt.Set("workspace_id", v)
	return u
}

// SetTaskID sets task_id.
func (u *CommentUpdate) SetTaskID(v string) *CommentUpdate {
	u.stmt.Set("task_id", v)
	return u
}

// SetAuthorID sets author_id.
func (u *CommentUpdate) SetAuthorID(v string) *CommentUpdate {
	u.stmt.Set("author_id", v)
	return u
}

// SetBody sets body.
func (u *CommentUpdate) SetBody(v string) *CommentUpdate {
	u.stmt.Set("body", v)
	return u
}

// SetCreatedAt sets created_at.
func (u *CommentUpdate) SetCreatedAt(v time.Time) *CommentUpdate {
	u.stmt.Set("created_at", v)
	return u
}

// SetUpdatedAt sets updated_at.
func (u *CommentUpdate) SetUpdatedAt(v time.Time) *CommentUpdate {
	u.stmt.Set("updated_at", v)
	return u
}

// SetDeletedAt sets deleted_at.
func (u *CommentUpdate) SetDeletedAt(v *time.Time) *CommentUpdate {
	u.stmt.Set("deleted_at", v)
	return u
}

// Where narrows the affected rows.
func (u *CommentUpdate) Where(preds ...sqlb.Pred) *CommentUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *CommentUpdate) Stmt() *sqlb.Update[Comment] { return u.stmt }

type listColumns struct {
	ID          sqlb.Col[string]
	WorkspaceID sqlb.Col[string]
	Name        sqlb.TextCol[string]
	Description sqlb.TextCol[string]
	Color       sqlb.TextCol[string]
	Position    sqlb.Col[int32]
	Archived    sqlb.Col[bool]
	CreatedAt   sqlb.Col[time.Time]
	UpdatedAt   sqlb.Col[time.Time]
	DeletedAt   sqlb.Col[time.Time]
}

// ListCols are the typed columns of lists.
var ListCols = listColumns{
	ID:          sqlb.Typed[string]("id"),
	WorkspaceID: sqlb.Typed[string]("workspace_id"),
	Name:        sqlb.TextColumn[string]("name"),
	Description: sqlb.TextColumn[string]("description"),
	Color:       sqlb.TextColumn[string]("color"),
	Position:    sqlb.Typed[int32]("position"),
	Archived:    sqlb.Typed[bool]("archived"),
	CreatedAt:   sqlb.Typed[time.Time]("created_at"),
	UpdatedAt:   sqlb.Typed[time.Time]("updated_at"),
	DeletedAt:   sqlb.Typed[time.Time]("deleted_at"),
}

// ListUpdate is a typed update statement for lists.
type ListUpdate struct {
	stmt *sqlb.Update[List]
}

// UpdateList starts a typed update.
func UpdateList() *ListUpdate {
	return &ListUpdate{stmt: sqlb.UpdateRows[List]()}
}

// SetWorkspaceID sets workspace_id.
func (u *ListUpdate) SetWorkspaceID(v string) *ListUpdate {
	u.stmt.Set("workspace_id", v)
	return u
}

// SetName sets name.
func (u *ListUpdate) SetName(v string) *ListUpdate {
	u.stmt.Set("name", v)
	return u
}

// SetDescription sets description.
func (u *ListUpdate) SetDescription(v string) *ListUpdate {
	u.stmt.Set("description", v)
	return u
}

// SetColor sets color.
func (u *ListUpdate) SetColor(v string) *ListUpdate {
	u.stmt.Set("color", v)
	return u
}

// SetPosition sets position.
func (u *ListUpdate) SetPosition(v int32) *ListUpdate {
	u.stmt.Set("position", v)
	return u
}

// SetArchived sets archived.
func (u *ListUpdate) SetArchived(v bool) *ListUpdate {
	u.stmt.Set("archived", v)
	return u
}

// SetCreatedAt sets created_at.
func (u *ListUpdate) SetCreatedAt(v time.Time) *ListUpdate {
	u.stmt.Set("created_at", v)
	return u
}

// SetUpdatedAt sets updated_at.
func (u *ListUpdate) SetUpdatedAt(v time.Time) *ListUpdate {
	u.stmt.Set("updated_at", v)
	return u
}

// SetDeletedAt sets deleted_at.
func (u *ListUpdate) SetDeletedAt(v *time.Time) *ListUpdate {
	u.stmt.Set("deleted_at", v)
	return u
}

// Where narrows the affected rows.
func (u *ListUpdate) Where(preds ...sqlb.Pred) *ListUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *ListUpdate) Stmt() *sqlb.Update[List] { return u.stmt }

type membershipColumns struct {
	ID          sqlb.Col[string]
	WorkspaceID sqlb.Col[string]
	UserID      sqlb.Col[string]
	Role        sqlb.Col[MembershipRole]
	CreatedAt   sqlb.Col[time.Time]
	UpdatedAt   sqlb.Col[time.Time]
}

// MembershipCols are the typed columns of memberships.
var MembershipCols = membershipColumns{
	ID:          sqlb.Typed[string]("id"),
	WorkspaceID: sqlb.Typed[string]("workspace_id"),
	UserID:      sqlb.Typed[string]("user_id"),
	Role:        sqlb.Typed[MembershipRole]("role"),
	CreatedAt:   sqlb.Typed[time.Time]("created_at"),
	UpdatedAt:   sqlb.Typed[time.Time]("updated_at"),
}

// MembershipUpdate is a typed update statement for memberships.
type MembershipUpdate struct {
	stmt *sqlb.Update[Membership]
}

// UpdateMembership starts a typed update.
func UpdateMembership() *MembershipUpdate {
	return &MembershipUpdate{stmt: sqlb.UpdateRows[Membership]()}
}

// SetWorkspaceID sets workspace_id.
func (u *MembershipUpdate) SetWorkspaceID(v string) *MembershipUpdate {
	u.stmt.Set("workspace_id", v)
	return u
}

// SetUserID sets user_id.
func (u *MembershipUpdate) SetUserID(v string) *MembershipUpdate {
	u.stmt.Set("user_id", v)
	return u
}

// SetRole sets role.
func (u *MembershipUpdate) SetRole(v MembershipRole) *MembershipUpdate {
	u.stmt.Set("role", v)
	return u
}

// SetCreatedAt sets created_at.
func (u *MembershipUpdate) SetCreatedAt(v time.Time) *MembershipUpdate {
	u.stmt.Set("created_at", v)
	return u
}

// SetUpdatedAt sets updated_at.
func (u *MembershipUpdate) SetUpdatedAt(v time.Time) *MembershipUpdate {
	u.stmt.Set("updated_at", v)
	return u
}

// Where narrows the affected rows.
func (u *MembershipUpdate) Where(preds ...sqlb.Pred) *MembershipUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *MembershipUpdate) Stmt() *sqlb.Update[Membership] { return u.stmt }

type profileColumns struct {
	ID        sqlb.Col[string]
	UserID    sqlb.Col[string]
	Bio       sqlb.TextCol[string]
	CreatedAt sqlb.Col[time.Time]
	UpdatedAt sqlb.Col[time.Time]
}

// ProfileCols are the typed columns of profiles.
var ProfileCols = profileColumns{
	ID:        sqlb.Typed[string]("id"),
	UserID:    sqlb.Typed[string]("user_id"),
	Bio:       sqlb.TextColumn[string]("bio"),
	CreatedAt: sqlb.Typed[time.Time]("created_at"),
	UpdatedAt: sqlb.Typed[time.Time]("updated_at"),
}

// ProfileUpdate is a typed update statement for profiles.
type ProfileUpdate struct {
	stmt *sqlb.Update[Profile]
}

// UpdateProfile starts a typed update.
func UpdateProfile() *ProfileUpdate {
	return &ProfileUpdate{stmt: sqlb.UpdateRows[Profile]()}
}

// SetUserID sets user_id.
func (u *ProfileUpdate) SetUserID(v string) *ProfileUpdate {
	u.stmt.Set("user_id", v)
	return u
}

// SetBio sets bio.
func (u *ProfileUpdate) SetBio(v *string) *ProfileUpdate {
	u.stmt.Set("bio", v)
	return u
}

// SetCreatedAt sets created_at.
func (u *ProfileUpdate) SetCreatedAt(v time.Time) *ProfileUpdate {
	u.stmt.Set("created_at", v)
	return u
}

// SetUpdatedAt sets updated_at.
func (u *ProfileUpdate) SetUpdatedAt(v time.Time) *ProfileUpdate {
	u.stmt.Set("updated_at", v)
	return u
}

// Where narrows the affected rows.
func (u *ProfileUpdate) Where(preds ...sqlb.Pred) *ProfileUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *ProfileUpdate) Stmt() *sqlb.Update[Profile] { return u.stmt }

type taskColumns struct {
	ID           sqlb.Col[string]
	WorkspaceID  sqlb.Col[string]
	ListID       sqlb.Col[string]
	AssigneeID   sqlb.Col[string]
	AuthorID     sqlb.Col[string]
	Title        sqlb.TextCol[string]
	Description  sqlb.TextCol[string]
	Labels       sqlb.ArrayCol[string]
	Status       sqlb.Col[TaskStatus]
	Priority     sqlb.Col[TaskPriority]
	DueAt        sqlb.Col[time.Time]
	CompletedAt  sqlb.Col[time.Time]
	Position     sqlb.Col[int32]
	CommentCount sqlb.Col[int32]
	CreatedAt    sqlb.Col[time.Time]
	UpdatedAt    sqlb.Col[time.Time]
	DeletedAt    sqlb.Col[time.Time]
}

// TaskCols are the typed columns of tasks.
var TaskCols = taskColumns{
	ID:           sqlb.Typed[string]("id"),
	WorkspaceID:  sqlb.Typed[string]("workspace_id"),
	ListID:       sqlb.Typed[string]("list_id"),
	AssigneeID:   sqlb.Typed[string]("assignee_id"),
	AuthorID:     sqlb.Typed[string]("author_id"),
	Title:        sqlb.TextColumn[string]("title"),
	Description:  sqlb.TextColumn[string]("description"),
	Labels:       sqlb.ArrayColumn[string]("labels"),
	Status:       sqlb.Typed[TaskStatus]("status"),
	Priority:     sqlb.Typed[TaskPriority]("priority"),
	DueAt:        sqlb.Typed[time.Time]("due_at"),
	CompletedAt:  sqlb.Typed[time.Time]("completed_at"),
	Position:     sqlb.Typed[int32]("position"),
	CommentCount: sqlb.Typed[int32]("comment_count"),
	CreatedAt:    sqlb.Typed[time.Time]("created_at"),
	UpdatedAt:    sqlb.Typed[time.Time]("updated_at"),
	DeletedAt:    sqlb.Typed[time.Time]("deleted_at"),
}

// TaskUpdate is a typed update statement for tasks.
type TaskUpdate struct {
	stmt *sqlb.Update[Task]
}

// UpdateTask starts a typed update.
func UpdateTask() *TaskUpdate {
	return &TaskUpdate{stmt: sqlb.UpdateRows[Task]()}
}

// SetWorkspaceID sets workspace_id.
func (u *TaskUpdate) SetWorkspaceID(v string) *TaskUpdate {
	u.stmt.Set("workspace_id", v)
	return u
}

// SetListID sets list_id.
func (u *TaskUpdate) SetListID(v string) *TaskUpdate {
	u.stmt.Set("list_id", v)
	return u
}

// SetAssigneeID sets assignee_id.
func (u *TaskUpdate) SetAssigneeID(v *string) *TaskUpdate {
	u.stmt.Set("assignee_id", v)
	return u
}

// SetAuthorID sets author_id.
func (u *TaskUpdate) SetAuthorID(v string) *TaskUpdate {
	u.stmt.Set("author_id", v)
	return u
}

// SetTitle sets title.
func (u *TaskUpdate) SetTitle(v string) *TaskUpdate {
	u.stmt.Set("title", v)
	return u
}

// SetDescription sets description.
func (u *TaskUpdate) SetDescription(v string) *TaskUpdate {
	u.stmt.Set("description", v)
	return u
}

// SetLabels sets labels.
func (u *TaskUpdate) SetLabels(v []string) *TaskUpdate {
	u.stmt.Set("labels", v)
	return u
}

// SetStatus sets status.
func (u *TaskUpdate) SetStatus(v TaskStatus) *TaskUpdate {
	u.stmt.Set("status", v)
	return u
}

// SetPriority sets priority.
func (u *TaskUpdate) SetPriority(v TaskPriority) *TaskUpdate {
	u.stmt.Set("priority", v)
	return u
}

// SetDueAt sets due_at.
func (u *TaskUpdate) SetDueAt(v *time.Time) *TaskUpdate {
	u.stmt.Set("due_at", v)
	return u
}

// SetCompletedAt sets completed_at.
func (u *TaskUpdate) SetCompletedAt(v *time.Time) *TaskUpdate {
	u.stmt.Set("completed_at", v)
	return u
}

// SetPosition sets position.
func (u *TaskUpdate) SetPosition(v int32) *TaskUpdate {
	u.stmt.Set("position", v)
	return u
}

// SetCommentCount sets comment_count.
func (u *TaskUpdate) SetCommentCount(v int32) *TaskUpdate {
	u.stmt.Set("comment_count", v)
	return u
}

// SetCreatedAt sets created_at.
func (u *TaskUpdate) SetCreatedAt(v time.Time) *TaskUpdate {
	u.stmt.Set("created_at", v)
	return u
}

// SetUpdatedAt sets updated_at.
func (u *TaskUpdate) SetUpdatedAt(v time.Time) *TaskUpdate {
	u.stmt.Set("updated_at", v)
	return u
}

// SetDeletedAt sets deleted_at.
func (u *TaskUpdate) SetDeletedAt(v *time.Time) *TaskUpdate {
	u.stmt.Set("deleted_at", v)
	return u
}

// Where narrows the affected rows.
func (u *TaskUpdate) Where(preds ...sqlb.Pred) *TaskUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *TaskUpdate) Stmt() *sqlb.Update[Task] { return u.stmt }

type userColumns struct {
	ID        sqlb.Col[string]
	Email     sqlb.TextCol[string]
	Name      sqlb.TextCol[string]
	CreatedAt sqlb.Col[time.Time]
	UpdatedAt sqlb.Col[time.Time]
}

// UserCols are the typed columns of users.
// Hidden columns are omitted: a predicate against one should not compile.
// Omitted here: password_hash.
// Declaring LookupKey beside Hidden returns one to this facade, for the column
// whose own value is how the row is found. It stays off the wire either way.
var UserCols = userColumns{
	ID:        sqlb.Typed[string]("id"),
	Email:     sqlb.TextColumn[string]("email"),
	Name:      sqlb.TextColumn[string]("name"),
	CreatedAt: sqlb.Typed[time.Time]("created_at"),
	UpdatedAt: sqlb.Typed[time.Time]("updated_at"),
}

// UserUpdate is a typed update statement for users.
type UserUpdate struct {
	stmt *sqlb.Update[User]
}

// UpdateUser starts a typed update.
func UpdateUser() *UserUpdate {
	return &UserUpdate{stmt: sqlb.UpdateRows[User]()}
}

// SetEmail sets email.
func (u *UserUpdate) SetEmail(v string) *UserUpdate {
	u.stmt.Set("email", v)
	return u
}

// SetName sets name.
func (u *UserUpdate) SetName(v string) *UserUpdate {
	u.stmt.Set("name", v)
	return u
}

// SetPasswordHash sets password_hash.
func (u *UserUpdate) SetPasswordHash(v string) *UserUpdate {
	u.stmt.Set("password_hash", v)
	return u
}

// SetCreatedAt sets created_at.
func (u *UserUpdate) SetCreatedAt(v time.Time) *UserUpdate {
	u.stmt.Set("created_at", v)
	return u
}

// SetUpdatedAt sets updated_at.
func (u *UserUpdate) SetUpdatedAt(v time.Time) *UserUpdate {
	u.stmt.Set("updated_at", v)
	return u
}

// Where narrows the affected rows.
func (u *UserUpdate) Where(preds ...sqlb.Pred) *UserUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *UserUpdate) Stmt() *sqlb.Update[User] { return u.stmt }

type workspaceColumns struct {
	ID        sqlb.Col[string]
	Name      sqlb.TextCol[string]
	Slug      sqlb.TextCol[string]
	CreatedAt sqlb.Col[time.Time]
	UpdatedAt sqlb.Col[time.Time]
}

// WorkspaceCols are the typed columns of workspaces.
var WorkspaceCols = workspaceColumns{
	ID:        sqlb.Typed[string]("id"),
	Name:      sqlb.TextColumn[string]("name"),
	Slug:      sqlb.TextColumn[string]("slug"),
	CreatedAt: sqlb.Typed[time.Time]("created_at"),
	UpdatedAt: sqlb.Typed[time.Time]("updated_at"),
}

// WorkspaceUpdate is a typed update statement for workspaces.
type WorkspaceUpdate struct {
	stmt *sqlb.Update[Workspace]
}

// UpdateWorkspace starts a typed update.
func UpdateWorkspace() *WorkspaceUpdate {
	return &WorkspaceUpdate{stmt: sqlb.UpdateRows[Workspace]()}
}

// SetName sets name.
func (u *WorkspaceUpdate) SetName(v string) *WorkspaceUpdate {
	u.stmt.Set("name", v)
	return u
}

// SetSlug sets slug.
func (u *WorkspaceUpdate) SetSlug(v string) *WorkspaceUpdate {
	u.stmt.Set("slug", v)
	return u
}

// SetCreatedAt sets created_at.
func (u *WorkspaceUpdate) SetCreatedAt(v time.Time) *WorkspaceUpdate {
	u.stmt.Set("created_at", v)
	return u
}

// SetUpdatedAt sets updated_at.
func (u *WorkspaceUpdate) SetUpdatedAt(v time.Time) *WorkspaceUpdate {
	u.stmt.Set("updated_at", v)
	return u
}

// Where narrows the affected rows.
func (u *WorkspaceUpdate) Where(preds ...sqlb.Pred) *WorkspaceUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *WorkspaceUpdate) Stmt() *sqlb.Update[Workspace] { return u.stmt }
