// Code generated by github.com/mind-vm/sqlb. DO NOT EDIT.

package tasks

import (
	"context"
	"encoding/json"
	"errors"
	"time"

	"github.com/danielgtaylor/huma/v2"
	"github.com/mind-vm/sqlb"
	"github.com/mind-vm/sqlb/rest"
)

// CommentCreate is the request body for creating a Comment.
//
// Read-only columns are absent: the database or a BeforeCreate hook owns them.
// A column with a default is optional, so leaving it out means the database
// supplies the value rather than the zero value overwriting it.
type CommentCreate struct {
	TaskID string `json:"task_id"`
	Body   string `json:"body"`
}

// Row builds the row to insert. It satisfies rest.CreateBody.
func (c CommentCreate) Row() (*Comment, error) {
	row := &Comment{}
	row.TaskID = c.TaskID
	row.Body = c.Body
	return row, nil
}

// ListCreate is the request body for creating a List.
//
// Read-only columns are absent: the database or a BeforeCreate hook owns them.
// A column with a default is optional, so leaving it out means the database
// supplies the value rather than the zero value overwriting it.
type ListCreate struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Color       *string `json:"color,omitempty"`
	Position    *int32  `json:"position,omitempty"`
	Archived    *bool   `json:"archived,omitempty"`
}

// Row builds the row to insert. It satisfies rest.CreateBody.
func (c ListCreate) Row() (*List, error) {
	row := &List{}
	row.Name = c.Name
	row.Description = c.Description
	if c.Color != nil {
		row.Color = *c.Color
	}
	if c.Position != nil {
		row.Position = *c.Position
	}
	if c.Archived != nil {
		row.Archived = *c.Archived
	}
	return row, nil
}

// Explicit names the columns this request carried, so that a sent zero value
// is written rather than being read as "absent, use the default". It satisfies
// rest.CreateExplicit.
func (c ListCreate) Explicit() []string {
	var cols []string
	if c.Color != nil {
		cols = append(cols, "color")
	}
	if c.Position != nil {
		cols = append(cols, "position")
	}
	if c.Archived != nil {
		cols = append(cols, "archived")
	}
	return cols
}

// ListPatch is the request body for patching a List.
//
// Every field is a pointer and every field is optional, so a request writes
// only the columns it names. Immutable columns are absent: they are settable
// once, at create.
type ListPatch struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Color       *string `json:"color,omitempty"`
	Position    *int32  `json:"position,omitempty"`
	Archived    *bool   `json:"archived,omitempty"`

	// present records which properties the request body actually carried.
	present map[string]bool
}

// UnmarshalJSON decodes the body and remembers which properties were present.
//
// Without this a nil pointer would be ambiguous: `{}` and `{"name": null}` decode
// identically, but the first must change nothing and the second must write NULL.
func (u *ListPatch) UnmarshalJSON(data []byte) error {
	type plain ListPatch
	if err := json.Unmarshal(data, (*plain)(u)); err != nil {
		return err
	}
	var keys map[string]json.RawMessage
	if err := json.Unmarshal(data, &keys); err != nil {
		return err
	}
	u.present = make(map[string]bool, len(keys))
	for k := range keys {
		u.present[k] = true
	}
	return nil
}

// Changes reports the columns the request named. It satisfies rest.UpdateBody.
func (u ListPatch) Changes() (map[string]any, error) {
	out := make(map[string]any, len(u.present))
	if u.present["name"] {
		if u.Name == nil {
			return nil, errors.New("name is not nullable and cannot be set to null")
		}
		out["name"] = *u.Name
	}
	if u.present["description"] {
		if u.Description == nil {
			return nil, errors.New("description is not nullable and cannot be set to null")
		}
		out["description"] = *u.Description
	}
	if u.present["color"] {
		if u.Color == nil {
			return nil, errors.New("color is not nullable and cannot be set to null")
		}
		out["color"] = *u.Color
	}
	if u.present["position"] {
		if u.Position == nil {
			return nil, errors.New("position is not nullable and cannot be set to null")
		}
		out["position"] = *u.Position
	}
	if u.present["archived"] {
		if u.Archived == nil {
			return nil, errors.New("archived is not nullable and cannot be set to null")
		}
		out["archived"] = *u.Archived
	}
	return out, nil
}

// MembershipCreate is the request body for creating a Membership.
//
// Read-only columns are absent: the database or a BeforeCreate hook owns them.
// A column with a default is optional, so leaving it out means the database
// supplies the value rather than the zero value overwriting it.
type MembershipCreate struct {
	UserID string          `json:"user_id"`
	Role   *MembershipRole `json:"role,omitempty" enum:"owner,admin,member"`
}

// Row builds the row to insert. It satisfies rest.CreateBody.
func (c MembershipCreate) Row() (*Membership, error) {
	row := &Membership{}
	row.UserID = c.UserID
	if c.Role != nil {
		row.Role = *c.Role
	}
	return row, nil
}

// Explicit names the columns this request carried, so that a sent zero value
// is written rather than being read as "absent, use the default". It satisfies
// rest.CreateExplicit.
func (c MembershipCreate) Explicit() []string {
	var cols []string
	if c.Role != nil {
		cols = append(cols, "role")
	}
	return cols
}

// ProfileCreate is the request body for creating a Profile.
//
// Read-only columns are absent: the database or a BeforeCreate hook owns them.
// A column with a default is optional, so leaving it out means the database
// supplies the value rather than the zero value overwriting it.
type ProfileCreate struct {
	UserID string  `json:"user_id"`
	Bio    *string `json:"bio,omitempty"`
}

// Row builds the row to insert. It satisfies rest.CreateBody.
func (c ProfileCreate) Row() (*Profile, error) {
	row := &Profile{}
	row.UserID = c.UserID
	row.Bio = c.Bio
	return row, nil
}

// TaskCreate is the request body for creating a Task.
//
// Read-only columns are absent: the database or a BeforeCreate hook owns them.
// A column with a default is optional, so leaving it out means the database
// supplies the value rather than the zero value overwriting it.
type TaskCreate struct {
	ListID      string        `json:"list_id"`
	AssigneeID  *string       `json:"assignee_id,omitempty"`
	Title       string        `json:"title"`
	Description string        `json:"description"`
	Labels      *[]string     `json:"labels,omitempty"` // Free-form labels. Filter with has, hasany or hasall.
	Status      *TaskStatus   `json:"status,omitempty" enum:"todo,in_progress,blocked,done"`
	Priority    *TaskPriority `json:"priority,omitempty" enum:"low,medium,high,urgent"`
	DueAt       *time.Time    `json:"due_at,omitempty"`
	Position    *int32        `json:"position,omitempty"`
}

// Row builds the row to insert. It satisfies rest.CreateBody.
func (c TaskCreate) Row() (*Task, error) {
	row := &Task{}
	row.ListID = c.ListID
	row.AssigneeID = c.AssigneeID
	row.Title = c.Title
	row.Description = c.Description
	if c.Labels != nil {
		row.Labels = *c.Labels
	}
	if c.Status != nil {
		row.Status = *c.Status
	}
	if c.Priority != nil {
		row.Priority = *c.Priority
	}
	row.DueAt = c.DueAt
	if c.Position != nil {
		row.Position = *c.Position
	}
	return row, nil
}

// Explicit names the columns this request carried, so that a sent zero value
// is written rather than being read as "absent, use the default". It satisfies
// rest.CreateExplicit.
func (c TaskCreate) Explicit() []string {
	var cols []string
	if c.Labels != nil {
		cols = append(cols, "labels")
	}
	if c.Status != nil {
		cols = append(cols, "status")
	}
	if c.Priority != nil {
		cols = append(cols, "priority")
	}
	if c.Position != nil {
		cols = append(cols, "position")
	}
	return cols
}

// TaskPatch is the request body for patching a Task.
//
// Every field is a pointer and every field is optional, so a request writes
// only the columns it names. Immutable columns are absent: they are settable
// once, at create.
type TaskPatch struct {
	ListID      *string       `json:"list_id,omitempty"`
	AssigneeID  *string       `json:"assignee_id,omitempty"`
	Title       *string       `json:"title,omitempty"`
	Description *string       `json:"description,omitempty"`
	Labels      *[]string     `json:"labels,omitempty"` // Free-form labels. Filter with has, hasany or hasall.
	Status      *TaskStatus   `json:"status,omitempty" enum:"todo,in_progress,blocked,done"`
	Priority    *TaskPriority `json:"priority,omitempty" enum:"low,medium,high,urgent"`
	DueAt       *time.Time    `json:"due_at,omitempty"`
	Position    *int32        `json:"position,omitempty"`

	// present records which properties the request body actually carried.
	present map[string]bool
}

// UnmarshalJSON decodes the body and remembers which properties were present.
//
// Without this a nil pointer would be ambiguous: `{}` and `{"list_id": null}` decode
// identically, but the first must change nothing and the second must write NULL.
func (u *TaskPatch) UnmarshalJSON(data []byte) error {
	type plain TaskPatch
	if err := json.Unmarshal(data, (*plain)(u)); err != nil {
		return err
	}
	var keys map[string]json.RawMessage
	if err := json.Unmarshal(data, &keys); err != nil {
		return err
	}
	u.present = make(map[string]bool, len(keys))
	for k := range keys {
		u.present[k] = true
	}
	return nil
}

// Changes reports the columns the request named. It satisfies rest.UpdateBody.
func (u TaskPatch) Changes() (map[string]any, error) {
	out := make(map[string]any, len(u.present))
	if u.present["list_id"] {
		if u.ListID == nil {
			return nil, errors.New("list_id is not nullable and cannot be set to null")
		}
		out["list_id"] = *u.ListID
	}
	if u.present["assignee_id"] {
		out["assignee_id"] = u.AssigneeID
	}
	if u.present["title"] {
		if u.Title == nil {
			return nil, errors.New("title is not nullable and cannot be set to null")
		}
		out["title"] = *u.Title
	}
	if u.present["description"] {
		if u.Description == nil {
			return nil, errors.New("description is not nullable and cannot be set to null")
		}
		out["description"] = *u.Description
	}
	if u.present["labels"] {
		if u.Labels == nil {
			return nil, errors.New("labels is not nullable and cannot be set to null")
		}
		out["labels"] = *u.Labels
	}
	if u.present["status"] {
		if u.Status == nil {
			return nil, errors.New("status is not nullable and cannot be set to null")
		}
		out["status"] = *u.Status
	}
	if u.present["priority"] {
		if u.Priority == nil {
			return nil, errors.New("priority is not nullable and cannot be set to null")
		}
		out["priority"] = *u.Priority
	}
	if u.present["due_at"] {
		out["due_at"] = u.DueAt
	}
	if u.present["position"] {
		if u.Position == nil {
			return nil, errors.New("position is not nullable and cannot be set to null")
		}
		out["position"] = *u.Position
	}
	return out, nil
}

// CompleteTaskInput is the request body for /tasks/{id}/complete.
//
// A property with a default or one that may be null is a pointer, so that
// leaving it out is distinguishable from sending its zero value.
type CompleteTaskInput struct {
	Note *string `json:"note,omitempty"` // Recorded as a comment on the task, in the same transaction.
}

// Actions carries the domain funcs the declared actions call.
//
// Each field is the verb of one action, and the envelope around it —
// the id, the scoped fetch, the transaction, the write set and the
// response — is generated. What the func does is the application's.
//
// A field left nil is refused when Register mounts the resource, not by
// the request that would have called it.
type Actions struct {
	// CompleteTask runs POST /tasks/{id}/complete.
	//
	// Marks the task done and stamps its completion time. A task that is already done is refused with a 409.
	//
	// The envelope persists `status` and `completed_at` off this row afterwards, and nothing
	// else — which bounds the envelope and not the func: the transaction
	// is yours through sqlb.TxFrom, and statements issued there take
	// their own locks, in an order this code owns.
	//
	// Declared reach beyond that row: `comments`. Nothing checks it; it is
	// what the route tells `sqlb impact`, the OpenAPI document and the
	// CLI's --help, so a change here belongs in the schema.
	CompleteTask func(context.Context, *Task, CompleteTaskInput) error
}

// Register mounts every exposed resource on api.
//
// The handlers are rest.Resource, instantiated per model. Registration is
// generic rather than reflective because query hooks are keyed by type: a
// BeforeQuery hook registered on a model applies to its REST reads too, which
// is how tenant scoping stops being something each handler must remember.
//
// The schema declares actions, so this takes the funcs that run inside
// their envelopes. That parameter is the compiler's half of the bargain:
// an action added to the schema fails the build here rather than serving a
// route nobody wired.
func Register(api huma.API, db sqlb.Executor, actions Actions) error {
	if err := rest.Resource[Comment, CommentCreate, rest.None[Comment]](api, db, rest.Options{
		Path:            "/comments",
		Name:            "comment",
		Tag:             "comments",
		Ops:             rest.OpCreate | rest.OpRead | rest.OpList,
		Description:     "A comment on a task.",
		DefaultPageSize: 50,
		MaxPageSize:     100,
	}); err != nil {
		return err
	}
	if err := rest.Resource[List, ListCreate, ListPatch](api, db, rest.Options{
		Path:            "/lists",
		Name:            "list",
		Tag:             "lists",
		Ops:             rest.OpCreate | rest.OpRead | rest.OpUpdate | rest.OpList,
		Description:     "A named list of tasks within a workspace.",
		DefaultPageSize: 25,
		MaxPageSize:     100,
		Expandable:      []string{"tasks"},
	}); err != nil {
		return err
	}
	if err := rest.Resource[Membership, MembershipCreate, rest.None[Membership]](api, db, rest.Options{
		Path:            "/memberships",
		Name:            "membership",
		Tag:             "memberships",
		Ops:             rest.OpCreate | rest.OpRead | rest.OpDelete | rest.OpList,
		Description:     "A user's membership of a workspace, and their role in it.",
		DefaultPageSize: 25,
		MaxPageSize:     100,
	}); err != nil {
		return err
	}
	if err := rest.Resource[Profile, ProfileCreate, rest.None[Profile]](api, db, rest.Options{
		Path:        "/profiles",
		Name:        "profile",
		Tag:         "profiles",
		Ops:         rest.OpCreate,
		Description: "A user's extended profile. One-to-one with users: user_id is unique.",
	}); err != nil {
		return err
	}
	tasksOptions := rest.Options{
		Path:            "/tasks",
		Name:            "task",
		Tag:             "tasks",
		Ops:             rest.OpCreate | rest.OpRead | rest.OpUpdate | rest.OpList,
		Description:     "A unit of work, belonging to one list.",
		DefaultPageSize: 20,
		MaxPageSize:     100,
		MaxFilters:      12,
		Expandable:      []string{"list"},
	}
	if err := rest.Resource[Task, TaskCreate, TaskPatch](api, db, tasksOptions); err != nil {
		return err
	}
	if err := rest.Action[Task, CompleteTaskInput](api, db, tasksOptions, rest.ActionSpec{
		Name:        "complete",
		Path:        "/tasks/{id}/complete",
		Field:       "CompleteTask",
		Summary:     "Complete a task",
		Description: "Marks the task done and stamps its completion time. A task that is already done is refused with a 409.",
		Writes:      []string{"status", "completed_at"},
		Touches:     []string{"comments"},
		HasBody:     true,
	}, actions.CompleteTask); err != nil {
		return err
	}
	if err := rest.Resource[User, rest.None[User], rest.None[User]](api, db, rest.Options{
		Path:        "/users",
		Name:        "user",
		Tag:         "users",
		Ops:         rest.OpRead | rest.OpList,
		MaxPageSize: 100,
		Expandable:  []string{"profile"},
	}); err != nil {
		return err
	}
	if err := rest.Resource[Workspace, rest.None[Workspace], rest.None[Workspace]](api, db, rest.Options{
		Path:        "/workspaces",
		Name:        "workspace",
		Tag:         "workspaces",
		Ops:         rest.OpRead | rest.OpList,
		Description: "A tenant. Lists, tasks and comments all belong to exactly one.",
	}); err != nil {
		return err
	}
	return nil
}
