// Code generated by github.com/mind-vm/sqlb. DO NOT EDIT.

package tasks

import (
	"context"
	"fmt"

	"github.com/mind-vm/sqlb"
)

// Scopes carries the funcs that answer which tenant a caller is in.
//
// One field per scope column this schema declares, typed as that column is,
// so the compiler demands the exact signature and a scope column added to the
// schema is a build error at the call site rather than a table that silently
// confines nothing. A field left nil is refused by RegisterScopes, not by the
// request that would have gone unconfined.
type Scopes struct {
	// WorkspaceID answers which workspace the caller is in. It confines comments, lists, memberships and tasks.
	//
	// Returning an error refuses the statement, which is what a caller with no
	// tenant should get: a read answers nothing rather than everything.
	WorkspaceID func(context.Context) (string, error)
}

// RegisterScopes registers the confining hooks this schema's Scoped columns
// declare: a predicate on every read, update and delete, and a stamp on every
// create.
//
// name is the releasable scope name. A handle derived with
// DB.WithoutScope(name) is released from the predicates below — an admin
// surface that reads across tenants is the case — and is *not* released from
// the create stamp, which cannot be released at all: releasing a predicate
// shows one more row and releasing a stamp writes a row belonging to nobody.
//
// Registering these satisfies the obligation rest.Resource checks, so a
// resource over a scoped model mounts once this has been called and refuses
// to until it has.
//
// It is generated, so it is yours: delete the file and write the hooks by
// hand the day this shape stops fitting.
//
// It does not cover users and workspaces, which declare a scope on their own primary key
// without naming it. What confines such a table is particular to it — an
// identity, a membership subquery — and is not the `column = value` written
// below, so those keep their hand-written hooks and still owe them. Naming
// the scope on the column is how one opts in.
func RegisterScopes(reg *sqlb.Registry, name string, s Scopes) error {
	if s.WorkspaceID == nil {
		return fmt.Errorf("%s: Scopes.WorkspaceID is nil, and workspace_id confines comments, lists, memberships and tasks", name)
	}

	// comments
	sqlb.On[Comment](reg).Scope(name).
		BeforeQuery(func(ctx context.Context, q *sqlb.Builder[Comment]) error {
			v, err := s.WorkspaceID(ctx)
			if err != nil {
				return err
			}
			q.Where(sqlb.F("workspace_id").Eq(v))
			return nil
		}).
		BeforeUpdate(func(ctx context.Context, u *sqlb.Update[Comment]) error {
			v, err := s.WorkspaceID(ctx)
			if err != nil {
				return err
			}
			u.Where(sqlb.F("workspace_id").Eq(v))
			return nil
		}).
		BeforeDelete(func(ctx context.Context, d *sqlb.Delete[Comment]) error {
			v, err := s.WorkspaceID(ctx)
			if err != nil {
				return err
			}
			d.Where(sqlb.F("workspace_id").Eq(v))
			return nil
		})
	sqlb.On[Comment](reg).BeforeCreate(func(ctx context.Context, row *Comment) error {
		v, err := s.WorkspaceID(ctx)
		if err != nil {
			return err
		}
		row.WorkspaceID = v
		return nil
	})

	// lists
	sqlb.On[List](reg).Scope(name).
		BeforeQuery(func(ctx context.Context, q *sqlb.Builder[List]) error {
			v, err := s.WorkspaceID(ctx)
			if err != nil {
				return err
			}
			q.Where(sqlb.F("workspace_id").Eq(v))
			return nil
		}).
		BeforeUpdate(func(ctx context.Context, u *sqlb.Update[List]) error {
			v, err := s.WorkspaceID(ctx)
			if err != nil {
				return err
			}
			u.Where(sqlb.F("workspace_id").Eq(v))
			return nil
		}).
		BeforeDelete(func(ctx context.Context, d *sqlb.Delete[List]) error {
			v, err := s.WorkspaceID(ctx)
			if err != nil {
				return err
			}
			d.Where(sqlb.F("workspace_id").Eq(v))
			return nil
		})
	sqlb.On[List](reg).BeforeCreate(func(ctx context.Context, row *List) error {
		v, err := s.WorkspaceID(ctx)
		if err != nil {
			return err
		}
		row.WorkspaceID = v
		return nil
	})

	// memberships
	sqlb.On[Membership](reg).Scope(name).
		BeforeQuery(func(ctx context.Context, q *sqlb.Builder[Membership]) error {
			v, err := s.WorkspaceID(ctx)
			if err != nil {
				return err
			}
			q.Where(sqlb.F("workspace_id").Eq(v))
			return nil
		}).
		BeforeUpdate(func(ctx context.Context, u *sqlb.Update[Membership]) error {
			v, err := s.WorkspaceID(ctx)
			if err != nil {
				return err
			}
			u.Where(sqlb.F("workspace_id").Eq(v))
			return nil
		}).
		BeforeDelete(func(ctx context.Context, d *sqlb.Delete[Membership]) error {
			v, err := s.WorkspaceID(ctx)
			if err != nil {
				return err
			}
			d.Where(sqlb.F("workspace_id").Eq(v))
			return nil
		})
	sqlb.On[Membership](reg).BeforeCreate(func(ctx context.Context, row *Membership) error {
		v, err := s.WorkspaceID(ctx)
		if err != nil {
			return err
		}
		row.WorkspaceID = v
		return nil
	})

	// tasks
	sqlb.On[Task](reg).Scope(name).
		BeforeQuery(func(ctx context.Context, q *sqlb.Builder[Task]) error {
			v, err := s.WorkspaceID(ctx)
			if err != nil {
				return err
			}
			q.Where(sqlb.F("workspace_id").Eq(v))
			return nil
		}).
		BeforeUpdate(func(ctx context.Context, u *sqlb.Update[Task]) error {
			v, err := s.WorkspaceID(ctx)
			if err != nil {
				return err
			}
			u.Where(sqlb.F("workspace_id").Eq(v))
			return nil
		}).
		BeforeDelete(func(ctx context.Context, d *sqlb.Delete[Task]) error {
			v, err := s.WorkspaceID(ctx)
			if err != nil {
				return err
			}
			d.Where(sqlb.F("workspace_id").Eq(v))
			return nil
		})
	sqlb.On[Task](reg).BeforeCreate(func(ctx context.Context, row *Task) error {
		v, err := s.WorkspaceID(ctx)
		if err != nil {
			return err
		}
		row.WorkspaceID = v
		return nil
	})

	return nil
}
