package pgtest

import (
	"context"
	"testing"

	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/mind-vm/sqlb"
	"github.com/mind-vm/sqlb/introspect"
	"github.com/mind-vm/sqlb/migrate"
	"github.com/mind-vm/sqlb/schema"
)

// The construct that blocked a module, then a platform: no auto-incrementing
// integer key was expressible at all, so a table with one — and, because a
// drift gate is per registry, every module holding it — stayed outside the gate
// (issue #132).
//
// The DDL layer is unit-tested. What needs a database is whether Postgres
// accepts what it renders and whether the sequence actually supplies values,
// which is the half a string assertion cannot reach.
func autoSchema() *schema.Registry {
	r := schema.NewRegistry()
	// The two tables from the report, in the shapes they had there: an
	// append-only log keyed by a bigserial, and a step table whose serial is
	// the total order rather than the name of anything.
	r.Table("audit_log",
		schema.BigSerial("id").PrimaryKey(),
		schema.Text("action"),
		schema.Timestamp("occurred_at").Default(schema.Now()),
	)
	r.Table("coprocess_steps",
		schema.BigInt("seq").Identity().PrimaryKey(),
		schema.UUID("session_id"),
		schema.Int("attempt").IdentityAlways(),
		schema.SmallSerial("bucket"),
	).Index("session_id", "seq")
	return r
}

// The DDL applies, and the sequences supply values — including for the index
// that covers the serial, which is the cascade the report named: one
// undeclarable column took out a table *and* an index that had nothing wrong
// with it.
func TestAutoColumnsApplyAndCount(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	db := freshDB(t)
	applyRegistry(t, db, autoSchema())

	mustExec(t, db, `INSERT INTO audit_log (action) VALUES ('created'), ('updated'), ('deleted')`)
	var ids []int64
	rows, err := db.Query(ctx, `SELECT id FROM audit_log ORDER BY id`)
	if err != nil {
		t.Fatal(err)
	}
	defer rows.Close()
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			t.Fatal(err)
		}
		ids = append(ids, id)
	}
	if err := rows.Err(); err != nil {
		t.Fatal(err)
	}
	// Monotonic and dense from 1 — which is what the construct is *for* in the
	// schemas that reported it: the id is the tiebreak that makes
	// `ORDER BY occurred_at DESC, id DESC` a total order.
	if len(ids) != 3 || ids[0] != 1 || ids[1] != 2 || ids[2] != 3 {
		t.Errorf("the sequence did not supply the ids: %v", ids)
	}

	// GENERATED BY DEFAULT still lets an insert name the column, which is the
	// whole difference from ALWAYS and the reason a backfill can keep its ids.
	mustExec(t, db, `INSERT INTO coprocess_steps (seq, session_id) VALUES (99, gen_random_uuid())`)
	if _, err := db.Exec(ctx,
		`INSERT INTO coprocess_steps (session_id, attempt) VALUES (gen_random_uuid(), 5)`); err == nil {
		t.Error("an INSERT named a GENERATED ALWAYS column and Postgres accepted it, " +
			"so the two identity spellings are rendering the same")
	}
	// And the index over the serial exists, rather than having fallen with it.
	var n int
	if err := db.QueryRow(ctx,
		`SELECT count(*) FROM pg_indexes WHERE tablename = 'coprocess_steps' AND indexdef LIKE '%seq%'`).Scan(&n); err != nil {
		t.Fatal(err)
	}
	if n == 0 {
		t.Error("the index covering the serial column was not created")
	}
}

// The round trip: what Postgres stores comes back as the same declaration, in
// both spellings, so a drift gate over a table with one of these is quiet.
func TestAutoColumnsRoundTrip(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	db := freshDB(t)
	declared := autoSchema()
	applyRegistry(t, db, declared)

	back, rep, err := introspect.Registry(ctx, sqlb.New(db), introspect.Options{})
	if err != nil {
		t.Fatalf("introspect: %v", err)
	}
	if !rep.Empty() {
		t.Fatalf("an auto-incrementing key is declarable and should not be reported:\n%s", rep)
	}

	for _, tc := range []struct {
		table, column string
		want          schema.Auto
	}{
		{"audit_log", "id", schema.AutoSerial},
		{"coprocess_steps", "seq", schema.AutoIdentity},
		{"coprocess_steps", "attempt", schema.AutoIdentityAlways},
		{"coprocess_steps", "bucket", schema.AutoSerial},
	} {
		d := back.Get(tc.table).Field(tc.column).Desc()
		if d.Auto != tc.want {
			t.Errorf("%s.%s: Auto = %q, want %q", tc.table, tc.column, d.Auto, tc.want)
		}
		// The nextval a serial carries must not come back as a default too, or
		// the next rendering binds to a sequence nothing creates.
		if d.Default != nil {
			t.Errorf("%s.%s came back carrying a default: %+v", tc.table, tc.column, d.Default)
		}
	}

	forward, err := migrate.Diff(declared, back)
	if err != nil {
		t.Fatalf("Diff: %v", err)
	}
	backward, err := migrate.Diff(back, declared)
	if err != nil {
		t.Fatalf("Diff: %v", err)
	}
	if len(forward) != 0 || len(backward) != 0 {
		t.Errorf("an auto-incrementing key does not survive the round trip:\n%s%s",
			renderChanges("declared → read", forward), renderChanges("read → declared", backward))
	}
}

// A serial reached by ALTER rather than by CREATE TABLE, which is the only
// path that has to assemble the three objects by hand. Postgres has no
// `ALTER COLUMN … TYPE bigserial`, so this is where getting it wrong shows up.
func TestColumnBecomesAndStopsBeingASerial(t *testing.T) {
	t.Parallel()
	ctx := context.Background()
	db := freshDB(t)

	plain := schema.NewRegistry()
	plain.Table("counters", schema.BigInt("id").PrimaryKey(), schema.Text("name"))
	applyRegistry(t, db, plain)
	mustExec(t, db, `INSERT INTO counters (id, name) VALUES (1, 'first')`)

	serial := schema.NewRegistry()
	serial.Table("counters", schema.BigSerial("id").PrimaryKey(), schema.Text("name"))
	applyDiff(t, db, plain, serial)

	// The sequence starts at 1 and the table already holds a 1 — which is the
	// hazard the change carries, and the reason it is named rather than
	// silently patched with a scan nothing here can size.
	mustExec(t, db, `SELECT setval('counters_id_seq', (SELECT max(id) FROM counters))`)
	mustExec(t, db, `INSERT INTO counters (name) VALUES ('second')`)
	var id int64
	if err := db.QueryRow(ctx, `SELECT id FROM counters WHERE name = 'second'`).Scan(&id); err != nil {
		t.Fatal(err)
	}
	if id != 2 {
		t.Errorf("id = %d, want 2: the column is not drawing from its sequence", id)
	}

	// And back. The column keeps its values; only the default goes.
	applyDiff(t, db, serial, plain)
	var def *string
	if err := db.QueryRow(ctx,
		`SELECT column_default FROM information_schema.columns
		 WHERE table_name = 'counters' AND column_name = 'id'`).Scan(&def); err != nil {
		t.Fatal(err)
	}
	if def != nil {
		t.Errorf("the column still draws from a sequence: %q", *def)
	}
}

// applyDiff migrates a live database from one registry to another, failing on
// the first statement Postgres refuses. applyRegistry is the same thing from
// empty; this is the ALTER path, which is where a serial has to be assembled
// rather than spelled.
func applyDiff(t *testing.T, db *pgxpool.Pool, from, to *schema.Registry) {
	t.Helper()
	changes, err := migrate.Diff(from, to)
	if err != nil {
		t.Fatalf("Diff: %v", err)
	}
	for _, c := range changes {
		if _, err := db.Exec(context.Background(), c.Up); err != nil {
			t.Fatalf("Postgres refused %q: %v", c.Up, err)
		}
	}
}
