// Code generated by github.com/jryannel/sqlb. DO NOT EDIT.
//
// The typed client for this schema: row views, request bodies, the typed
// filter vocabulary, the URL encoder, one function per exposed operation, and
// a cursor pager for lists that load as they are scrolled.
//
// It imports nothing — not dart:io, not a pub package. The transport is
// injected, because the base URL, the auth header, token refresh and what a
// 401 does are the application's and are not derivable from a schema. That is
// the same seam the server takes by mounting onto a router the application
// built.
//
// Property names are lowerCamelCase and the wire spelling is carried beside
// them, because snake_case members would fail the lowerCamelCase lint in every
// file that touched them. Nothing is lost: Dart has to decode a response
// explicitly either way, so the mapping costs a string constant rather than a
// runtime layer.
//
// ADR-0031.

// ignore_for_file: unused_element
import 'runtime.gen.dart';
export 'runtime.gen.dart';

/// The shared behaviour of every generated row: the decoded response object it
/// wraps, and equality over it.
///
/// A row is a view rather than a copy. Columns are decoded on access, so a
/// list of two hundred rows whose screen reads three columns decodes three
/// columns, and a projection is representable at all — which it would not be
/// if the constructor required every field.
abstract class Row {
  /// Wraps one decoded response object.
  Row.fromJson(this._json);

  final Map<String, dynamic> _json;
  final Map<String, Object?> _cache = {};

  /// The decoded response object, exactly as it arrived.
  ///
  /// Useful for a local cache: what came back can be stored and handed to
  /// fromJson later without a second encoding step.
  Map<String, dynamic> toJson() => _json;

  /// Whether the response carried [column] at all, which is a different
  /// question from whether its value was null.
  bool _present(String column) => _json.containsKey(column);

  Object? _memo(String key, Object? Function() build) {
    if (_cache.containsKey(key)) return _cache[key];
    final value = build();
    _cache[key] = value;
    return value;
  }

  /// Reads a column, or reports that the request did not return it.
  ///
  /// Absence is checked with containsKey rather than by testing for null,
  /// because a nullable column returned as null and one that was never
  /// selected are different facts and only one of them is a mistake.
  Object? _read(String column, {required bool nullable}) {
    if (!_json.containsKey(column)) {
      throw MissingColumn('$runtimeType', column);
    }
    final value = _json[column];
    if (value == null && !nullable) {
      throw MissingColumn('$runtimeType', column);
    }
    return value;
  }

  String _str(String column) => _read(column, nullable: false)! as String;

  String? _strOrNull(String column) => _read(column, nullable: true) as String?;

  int _int(String column) => (_read(column, nullable: false)! as num).toInt();

  int? _intOrNull(String column) =>
      (_read(column, nullable: true) as num?)?.toInt();

  double _double(String column) =>
      (_read(column, nullable: false)! as num).toDouble();

  double? _doubleOrNull(String column) =>
      (_read(column, nullable: true) as num?)?.toDouble();

  bool _bool(String column) => _read(column, nullable: false)! as bool;

  bool? _boolOrNull(String column) => _read(column, nullable: true) as bool?;

  DateTime _time(String column) => DateTime.parse(_str(column));

  DateTime? _timeOrNull(String column) {
    final value = _strOrNull(column);
    return value == null ? null : DateTime.parse(value);
  }

  /// Reads an array column, decoding each element with the decoder its scalar
  /// form uses. A NULL column and an empty array are different values, which is
  /// why the nullable form returns null rather than an empty list.
  List<T> _list<T>(String column, T Function(Object) decode) {
    final value = _read(column, nullable: false)! as List;
    return value.map((e) => decode(e as Object)).toList(growable: false);
  }

  List<T>? _listOrNull<T>(String column, T Function(Object) decode) {
    final value = _read(column, nullable: true) as List?;
    if (value == null) return null;
    return value.map((e) => decode(e as Object)).toList(growable: false);
  }

  List<T> _enumList<T>(String column, T? Function(String) byWire) =>
      _list(column, (e) => _asEnum(byWire, e));

  List<T>? _enumListOrNull<T>(String column, T? Function(String) byWire) =>
      _listOrNull(column, (e) => _asEnum(byWire, e));

  Object _any(String column) => _read(column, nullable: false)!;

  Object? _anyOrNull(String column) => _read(column, nullable: true);

  /// Reads an enum column. The type argument names itself in the error, so a
  /// value the schema has since grown is reported as what it is.
  T _enum<T>(String column, T? Function(String) byWire) {
    final value = _str(column);
    return byWire(value) ?? (throw UnknownEnumValue('$T', value));
  }

  T? _enumOrNull<T>(String column, T? Function(String) byWire) {
    final value = _strOrNull(column);
    if (value == null) return null;
    return byWire(value) ?? (throw UnknownEnumValue('$T', value));
  }

  /// Reads a forward expansion: one row, or null when it was not expanded.
  T? _one<T>(String relation, T Function(Map<String, dynamic>) make) =>
      _memo(relation, () {
            final value = _json[relation];
            return value == null ? null : make(value as Map<String, dynamic>);
          })
          as T?;

  /// Reads a reverse expansion: a capped collection, or null when it was not
  /// expanded.
  Collection<T>? _many<T>(
    String relation,
    T Function(Map<String, dynamic>) make,
  ) =>
      _memo(relation, () {
            final value = _json[relation];
            if (value == null) return null;
            return Collection<T>.fromJson(value as Map<String, dynamic>, make);
          })
          as Collection<T>?;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Row &&
          other.runtimeType == runtimeType &&
          _jsonEquals(_json, other._json);

  @override
  int get hashCode => Object.hash(runtimeType, _jsonHash(_json));

  @override
  String toString() => '$runtimeType($_json)';
}

/// Operators every column type accepts.
///
/// Setting more than one conjoins them: the server reads a repeated parameter
/// as AND, so a condition object is a conjunction over one column.
class Cond<T extends Object> {
  /// Builds a condition. Every operator is optional; the unset ones are not
  /// sent.
  const Cond({
    this.eq,
    this.ne,
    this.gt,
    this.gte,
    this.lt,
    this.lte,
    this.isIn,
    this.notIn,
    this.between,
  });

  /// Equal to.
  final T? eq;

  /// Not equal to.
  final T? ne;

  /// Greater than.
  final T? gt;

  /// Greater than or equal to.
  final T? gte;

  /// Less than.
  final T? lt;

  /// Less than or equal to.
  final T? lte;

  /// One of. Named isIn because in is a Dart keyword.
  final List<T>? isIn;

  /// None of.
  final List<T>? notIn;

  /// Between two bounds, inclusive.
  final (T, T)? between;

  void _encode(_Query out, String column) => _comparison(
    out,
    column,
    eq: eq,
    ne: ne,
    gt: gt,
    gte: gte,
    lt: lt,
    lte: lte,
    isIn: isIn,
    notIn: notIn,
    between: between,
  );
}

/// The operators an array column accepts: containment, and whole-array
/// equality.
///
/// The ordering operators and the substring one are absent, because the server
/// refuses them on an array — array ordering is not a thing an API should
/// offer, and a substring is a text operation. There is no [contains] here for
/// the same reason: the name belongs to text, and one name meaning two things
/// depending on the column is the ambiguity this client exists to remove.
class ArrayCond<T extends Object> {
  /// Builds a condition. Every operator is optional; the unset ones are not
  /// sent.
  const ArrayCond({
    this.eq,
    this.ne,
    this.has,
    this.hasAny,
    this.hasAll,
    this.notHas,
    this.notHasAny,
    this.notHasAll,
  });

  /// The whole array, compared element by element.
  final List<T>? eq;

  /// Not equal to the whole array.
  final List<T>? ne;

  /// The array contains this element.
  final T? has;

  /// The array shares at least one element with these.
  final List<T>? hasAny;

  /// The array contains all of these.
  final List<T>? hasAll;

  /// The array does not contain this element.
  final T? notHas;

  /// The array shares no element with these.
  final List<T>? notHasAny;

  /// The array is missing at least one of these.
  final List<T>? notHasAll;

  void _encode(_Query out, String column) => _containment(
    out,
    column,
    eq: eq,
    ne: ne,
    has: has,
    hasAny: hasAny,
    hasAll: hasAll,
    notHas: notHas,
    notHasAny: notHasAny,
    notHasAll: notHasAll,
  );
}

/// An array column that may be NULL: the containment operators, plus the null
/// tests. A NULL array and an empty one are different values, so both tests
/// mean something here.
class NullableArrayCond<T extends Object> {
  /// Builds a condition. Every operator is optional.
  const NullableArrayCond({
    this.eq,
    this.ne,
    this.has,
    this.hasAny,
    this.hasAll,
    this.notHas,
    this.notHasAny,
    this.notHasAll,
    this.isNull,
    this.notNull,
  });

  /// The whole array, compared element by element.
  final List<T>? eq;

  /// Not equal to the whole array.
  final List<T>? ne;

  /// The array contains this element.
  final T? has;

  /// The array shares at least one element with these.
  final List<T>? hasAny;

  /// The array contains all of these.
  final List<T>? hasAll;

  /// The array does not contain this element.
  ///
  /// This is a negation, not a complement: a row whose column is NULL matches
  /// neither [has] nor [notHas]. Pass [isNull] beside it to include those rows.
  final T? notHas;

  /// The array shares no element with these.
  final List<T>? notHasAny;

  /// The array is missing at least one of these.
  final List<T>? notHasAll;

  /// The column is NULL, which is not the same as holding no elements.
  final bool? isNull;

  /// The column is not NULL.
  final bool? notNull;

  void _encode(_Query out, String column) {
    _containment(
      out,
      column,
      eq: eq,
      ne: ne,
      has: has,
      hasAny: hasAny,
      hasAll: hasAll,
      notHas: notHas,
      notHasAny: notHasAny,
      notHasAll: notHasAll,
    );
    _nullChecks(out, column, isNull: isNull, notNull: notNull);
  }
}

/// The operators a nullable column accepts: the comparisons, plus the null
/// tests that only mean something when a column can be null.
class NullableCond<T extends Object> {
  /// Builds a condition. Every operator is optional.
  const NullableCond({
    this.eq,
    this.ne,
    this.gt,
    this.gte,
    this.lt,
    this.lte,
    this.isIn,
    this.notIn,
    this.between,
    this.isNull,
    this.notNull,
  });

  /// Equal to.
  final T? eq;

  /// Not equal to.
  final T? ne;

  /// Greater than.
  final T? gt;

  /// Greater than or equal to.
  final T? gte;

  /// Less than.
  final T? lt;

  /// Less than or equal to.
  final T? lte;

  /// One of.
  final List<T>? isIn;

  /// None of.
  final List<T>? notIn;

  /// Between two bounds, inclusive.
  final (T, T)? between;

  /// IS NULL, when true.
  final bool? isNull;

  /// IS NOT NULL, when true.
  final bool? notNull;

  void _encode(_Query out, String column) {
    _comparison(
      out,
      column,
      eq: eq,
      ne: ne,
      gt: gt,
      gte: gte,
      lt: lt,
      lte: lte,
      isIn: isIn,
      notIn: notIn,
      between: between,
    );
    _nullChecks(out, column, isNull: isNull, notNull: notNull);
  }
}

/// The operators a text column accepts: the comparisons, plus the pattern
/// matches the server refuses on anything else.
class TextCond {
  /// Builds a condition. Every operator is optional.
  const TextCond({
    this.eq,
    this.ne,
    this.gt,
    this.gte,
    this.lt,
    this.lte,
    this.isIn,
    this.notIn,
    this.between,
    this.like,
    this.ilike,
    this.contains,
    this.startsWith,
    this.endsWith,
  });

  /// Equal to.
  final String? eq;

  /// Not equal to.
  final String? ne;

  /// Greater than.
  final String? gt;

  /// Greater than or equal to.
  final String? gte;

  /// Less than.
  final String? lt;

  /// Less than or equal to.
  final String? lte;

  /// One of.
  final List<String>? isIn;

  /// None of.
  final List<String>? notIn;

  /// Between two bounds, inclusive.
  final (String, String)? between;

  /// SQL LIKE, with the caller's own wildcards.
  final String? like;

  /// Case-insensitive LIKE.
  final String? ilike;

  /// Case-insensitive substring. The value is escaped, so a search for 50%
  /// matches that literal string rather than everything.
  final String? contains;

  /// Case-insensitive prefix.
  final String? startsWith;

  /// Case-insensitive suffix.
  final String? endsWith;

  void _encode(_Query out, String column) {
    _comparison(
      out,
      column,
      eq: eq,
      ne: ne,
      gt: gt,
      gte: gte,
      lt: lt,
      lte: lte,
      isIn: isIn,
      notIn: notIn,
      between: between,
    );
    _patterns(
      out,
      column,
      like: like,
      ilike: ilike,
      contains: contains,
      startsWith: startsWith,
      endsWith: endsWith,
    );
  }
}

/// The operators a nullable text column accepts: everything.
class NullableTextCond {
  /// Builds a condition. Every operator is optional.
  const NullableTextCond({
    this.eq,
    this.ne,
    this.gt,
    this.gte,
    this.lt,
    this.lte,
    this.isIn,
    this.notIn,
    this.between,
    this.like,
    this.ilike,
    this.contains,
    this.startsWith,
    this.endsWith,
    this.isNull,
    this.notNull,
  });

  /// Equal to.
  final String? eq;

  /// Not equal to.
  final String? ne;

  /// Greater than.
  final String? gt;

  /// Greater than or equal to.
  final String? gte;

  /// Less than.
  final String? lt;

  /// Less than or equal to.
  final String? lte;

  /// One of.
  final List<String>? isIn;

  /// None of.
  final List<String>? notIn;

  /// Between two bounds, inclusive.
  final (String, String)? between;

  /// SQL LIKE, with the caller's own wildcards.
  final String? like;

  /// Case-insensitive LIKE.
  final String? ilike;

  /// Case-insensitive substring, escaped.
  final String? contains;

  /// Case-insensitive prefix.
  final String? startsWith;

  /// Case-insensitive suffix.
  final String? endsWith;

  /// IS NULL, when true.
  final bool? isNull;

  /// IS NOT NULL, when true.
  final bool? notNull;

  void _encode(_Query out, String column) {
    _comparison(
      out,
      column,
      eq: eq,
      ne: ne,
      gt: gt,
      gte: gte,
      lt: lt,
      lte: lte,
      isIn: isIn,
      notIn: notIn,
      between: between,
    );
    _patterns(
      out,
      column,
      like: like,
      ilike: ilike,
      contains: contains,
      startsWith: startsWith,
      endsWith: endsWith,
    );
    _nullChecks(out, column, isNull: isNull, notNull: notNull);
  }
}

bool _jsonEquals(Object? a, Object? b) {
  if (identical(a, b)) return true;
  if (a is Map && b is Map) {
    if (a.length != b.length) return false;
    for (final key in a.keys) {
      if (!b.containsKey(key) || !_jsonEquals(a[key], b[key])) return false;
    }
    return true;
  }
  if (a is List && b is List) {
    if (a.length != b.length) return false;
    for (var i = 0; i < a.length; i++) {
      if (!_jsonEquals(a[i], b[i])) return false;
    }
    return true;
  }
  return a == b;
}

int _jsonHash(Object? value) {
  if (value is Map) {
    // Exclusive-or, so that the hash does not depend on key order — which a
    // decoded JSON object does not promise.
    var hash = 0;
    value.forEach((key, item) {
      hash ^= Object.hash(key, _jsonHash(item));
    });
    return hash;
  }
  if (value is List) return Object.hashAll(value.map(_jsonHash));
  return value.hashCode;
}

// --------------------------------------------------------------------- encoding

/// The JSON form of a value a request body carries.
Object? _wire(Object? value) {
  if (value is WireValue) return value.wire;
  if (value is DateTime) return value.toUtc().toIso8601String();
  // An array column carries a list, whose elements need the same treatment —
  // an enum array is a list of WireValue, and JSON has no spelling for one.
  if (value is List) return value.map(_wire).toList(growable: false);
  return value;
}

void _comparison(
  _Query out,
  String column, {
  Object? eq,
  Object? ne,
  Object? gt,
  Object? gte,
  Object? lt,
  Object? lte,
  List<Object?>? isIn,
  List<Object?>? notIn,
  (Object?, Object?)? between,
}) {
  if (eq != null) out.add(column, 'eq.${_scalar(eq)}');
  if (ne != null) out.add(column, 'ne.${_scalar(ne)}');
  if (gt != null) out.add(column, 'gt.${_scalar(gt)}');
  if (gte != null) out.add(column, 'gte.${_scalar(gte)}');
  if (lt != null) out.add(column, 'lt.${_scalar(lt)}');
  if (lte != null) out.add(column, 'lte.${_scalar(lte)}');
  if (isIn != null) out.add(column, 'in.${isIn.map(_member).join(',')}');
  if (notIn != null) out.add(column, 'nin.${notIn.map(_member).join(',')}');
  if (between != null) {
    out.add(column, 'between.${_member(between.$1)},${_member(between.$2)}');
  }
}

/// Decoders for one element of an array column. They take the value already
/// pulled out of the JSON list, which is what makes them shareable between the
/// nullable and non-nullable readers.
String _asStr(Object v) => v as String;

/// Decodes one element of an enum array, naming the type in the error so a
/// value the schema has since grown is reported as what it is.
T _asEnum<T>(T? Function(String) byWire, Object v) {
  final value = v as String;
  return byWire(value) ?? (throw UnknownEnumValue('$T', value));
}

/// The negated forms are negations, not complements: a row whose column is null
/// matches neither [has] nor [notHas]. Pass isNull beside one to include those
/// rows.
void _containment(
  _Query out,
  String column, {
  List<Object?>? eq,
  List<Object?>? ne,
  Object? has,
  List<Object?>? hasAny,
  List<Object?>? hasAll,
  Object? notHas,
  List<Object?>? notHasAny,
  List<Object?>? notHasAll,
}) {
  if (eq != null) out.add(column, 'eq.${eq.map(_member).join(',')}');
  if (ne != null) out.add(column, 'ne.${ne.map(_member).join(',')}');
  if (has != null) out.add(column, 'has.${_scalar(has)}');
  if (hasAny != null) {
    out.add(column, 'hasany.${hasAny.map(_member).join(',')}');
  }
  if (hasAll != null) {
    out.add(column, 'hasall.${hasAll.map(_member).join(',')}');
  }
  if (notHas != null) out.add(column, 'nhas.${_scalar(notHas)}');
  if (notHasAny != null) {
    out.add(column, 'nhasany.${notHasAny.map(_member).join(',')}');
  }
  if (notHasAll != null) {
    out.add(column, 'nhasall.${notHasAll.map(_member).join(',')}');
  }
}

void _patterns(
  _Query out,
  String column, {
  String? like,
  String? ilike,
  String? contains,
  String? startsWith,
  String? endsWith,
}) {
  if (like != null) out.add(column, 'like.$like');
  if (ilike != null) out.add(column, 'ilike.$ilike');
  if (contains != null) out.add(column, 'contains.$contains');
  if (startsWith != null) out.add(column, 'startswith.$startsWith');
  if (endsWith != null) out.add(column, 'endswith.$endsWith');
}

void _nullChecks(_Query out, String column, {bool? isNull, bool? notNull}) {
  if (isNull ?? false) out.add(column, 'isnull');
  if (notNull ?? false) out.add(column, 'notnull');
}

/// Accumulates query parameters, keeping repeats — which is how the grammar
/// conjoins two conditions on one column.
class _Query {
  final List<MapEntry<String, String>> _pairs = [];

  void add(String key, String value) => _pairs.add(MapEntry(key, value));

  void set(String key, String value) {
    _pairs.removeWhere((pair) => pair.key == key);
    add(key, value);
  }

  /// The encoded query string, sorted so that the same parameters always
  /// produce the same string — which is what makes a URL comparable in a test
  /// and cacheable by a proxy.
  ///
  /// The sort is stable, since List.sort is not: repeats of one key keep the
  /// order they were added in.
  String build() {
    final indexed = _pairs.indexed.toList()
      ..sort((a, b) {
        final byKey = a.$2.key.compareTo(b.$2.key);
        return byKey != 0 ? byKey : a.$1.compareTo(b.$1);
      });
    return indexed
        .map(
          (entry) =>
              '${Uri.encodeQueryComponent(entry.$2.key)}='
              '${Uri.encodeQueryComponent(entry.$2.value)}',
        )
        .join('&');
  }
}

String _itemPath(String collection, Object id) =>
    '$collection/${Uri.encodeComponent('$id')}';

// ------------------------------------------------------------------ transport

// One constructor per verb, so that a generated call is a single short line
// rather than a five-line argument list. They exist for the reader, not for the
// compiler.

ApiRequest _get(String path, String query, Object? cancel) =>
    ApiRequest(method: 'GET', path: path, query: query, cancel: cancel);

ApiRequest _post(String path, Object? body, Object? cancel) =>
    ApiRequest(method: 'POST', path: path, body: body, cancel: cancel);

ApiRequest _patch(String path, Object? body, Object? cancel) =>
    ApiRequest(method: 'PATCH', path: path, body: body, cancel: cancel);

ApiRequest _delete(String path, Object? cancel) =>
    ApiRequest(method: 'DELETE', path: path, cancel: cancel);

Page<T> _page<T>(Object? json, T Function(Map<String, dynamic>) make) =>
    Page<T>.fromJson(json! as Map<String, dynamic>, make);

T _row<T>(Object? json, T Function(Map<String, dynamic>) make) =>
    make(json! as Map<String, dynamic>);

/// One value in the filter grammar: an enum by its wire spelling, a timestamp
/// as RFC 3339 UTC, everything else as it prints.
String _scalar(Object? value) {
  if (value is WireValue) return value.wire;
  if (value is DateTime) return value.toUtc().toIso8601String();
  return '$value';
}

/// A member of a comma-separated list is quoted when it carries a comma or a
/// quote, which is how the server's parser reads it back whole.
String _member(Object? value) {
  final text = _scalar(value);
  if (!text.contains(',') && !text.contains('"')) return text;
  return '"${text.replaceAll('"', '\\"')}"';
}

// ------------------------------------------------------------------- comments

/// A comment on a task.
///
/// Reading a column the request did not return throws MissingColumn rather
/// than yielding null, so a projection that dropped a column is reported
/// where it is used instead of somewhere further out.
class Comment extends Row {
  /// Wraps one decoded response object. Columns are read on access.
  Comment.fromJson(super.json) : super.fromJson();

  /// The table this row came from.
  static const String table = 'comments';

  /// The comments.id column.
  String get id => _str('id');

  /// The comments.workspace_id column.
  String get workspaceId => _str('workspace_id');

  /// The comments.task_id column.
  String get taskId => _str('task_id');

  /// The comments.author_id column.
  String get authorId => _str('author_id');

  /// The comments.body column.
  String get body => _str('body');

  /// The comments.created_at column.
  DateTime get createdAt => _time('created_at');

  /// The comments.updated_at column.
  DateTime get updatedAt => _time('updated_at');

  /// The comments.deleted_at column.
  DateTime? get deletedAt => _timeOrNull('deleted_at');

  /// Whether the request that produced this row returned [column].
  bool has(CommentColumn column) => _present(column.wire);
}

/// The request body for creating a Comment.
///
/// Read-only columns are absent: the database or a BeforeCreate hook owns
/// them. A column with a default is optional, and leaving one out means the
/// database supplies the value.
class CommentCreate {
  /// Builds a request body. A property with no default here is one the
  /// database has none for.
  const CommentCreate({required this.taskId, required this.body});

  /// The comments.task_id column.
  final String taskId;

  /// The comments.body column.
  final String body;

  /// The JSON body. Absent properties are the ones left unset.
  Map<String, dynamic> toJson() => {
    'task_id': _wire(taskId),
    'body': _wire(body),
  };
}

// ---------------------------------------------------------------------- lists

/// A named list of tasks within a workspace.
///
/// Reading a column the request did not return throws MissingColumn rather
/// than yielding null, so a projection that dropped a column is reported
/// where it is used instead of somewhere further out.
class ListRow extends Row {
  /// Wraps one decoded response object. Columns are read on access.
  ListRow.fromJson(super.json) : super.fromJson();

  /// The table this row came from.
  static const String table = 'lists';

  /// The lists.id column.
  String get id => _str('id');

  /// The lists.workspace_id column.
  String get workspaceId => _str('workspace_id');

  /// The lists.name column.
  String get name => _str('name');

  /// The lists.description column.
  String get description => _str('description');

  /// The lists.color column.
  String get color => _str('color');

  /// The lists.position column.
  int get position => _int('position');

  /// The lists.archived column.
  bool get archived => _bool('archived');

  /// The lists.created_at column.
  DateTime get createdAt => _time('created_at');

  /// The lists.updated_at column.
  DateTime get updatedAt => _time('updated_at');

  /// The lists.deleted_at column.
  DateTime? get deletedAt => _timeOrNull('deleted_at');

  /// Filled in by expand: [ListExpand.tasks], null otherwise. Capped at 20 rows;
  /// Collection.hasMore reports truncation.
  Collection<Task>? get tasks => _many('tasks', Task.fromJson);

  /// Whether the request that produced this row returned [column].
  bool has(ListColumn column) => _present(column.wire);
}

/// The request body for creating a List.
///
/// Read-only columns are absent: the database or a BeforeCreate hook owns
/// them. A column with a default is optional, and leaving one out means the
/// database supplies the value.
class ListCreate {
  /// Builds a request body. A property with no default here is one the
  /// database has none for.
  const ListCreate({
    required this.name,
    required this.description,
    this.color,
    this.position,
    this.archived,
  });

  /// The lists.name column.
  final String name;

  /// The lists.description column.
  final String description;

  /// The lists.color column.
  final String? color;

  /// The lists.position column.
  final int? position;

  /// The lists.archived column.
  final bool? archived;

  /// The JSON body. Absent properties are the ones left unset.
  Map<String, dynamic> toJson() => {
    'name': _wire(name),
    'description': _wire(description),
    if (color != null) 'color': _wire(color),
    if (position != null) 'position': _wire(position),
    if (archived != null) 'archived': _wire(archived),
  };
}

/// The request body for patching a List.
///
/// One method per writable column, so a patch carries exactly the columns it
/// named:
///
/// ```dart
/// final patch = ListPatch()..name(value);
/// ```
///
/// A method taking a nullable value writes NULL when passed null; a column
/// left unmentioned is not written at all. That distinction cannot be read off
/// a field, which is why these are methods and not a constructor.
class ListPatch {
  final Map<String, dynamic> _changes = {};

  /// Writes lists.name.
  void name(String value) => _changes['name'] = _wire(value);

  /// Writes lists.description.
  void description(String value) => _changes['description'] = _wire(value);

  /// Writes lists.color.
  void color(String value) => _changes['color'] = _wire(value);

  /// Writes lists.position.
  void position(int value) => _changes['position'] = _wire(value);

  /// Writes lists.archived.
  void archived(bool value) => _changes['archived'] = _wire(value);

  /// Whether the patch would write nothing, which the server answers 400 to.
  bool get isEmpty => _changes.isEmpty;

  /// The JSON body: the columns this patch named, and no others.
  Map<String, dynamic> toJson() => Map<String, dynamic>.of(_changes);
}

// ---------------------------------------------------------------- memberships

/// The memberships.role column's value set.
enum MembershipRole implements WireValue {
  /// The value owner.
  owner('owner'),

  /// The value admin.
  admin('admin'),

  /// The value member.
  member('member');

  const MembershipRole(this.wire);

  @override
  final String wire;

  /// The member [wire] names, or null when the server sent a value this
  /// client does not have — a value set that grew since it was generated.
  static MembershipRole? byWire(String wire) {
    for (final value in values) {
      if (value.wire == wire) return value;
    }
    return null;
  }
}

/// A user's membership of a workspace, and their role in it.
///
/// Reading a column the request did not return throws MissingColumn rather
/// than yielding null, so a projection that dropped a column is reported
/// where it is used instead of somewhere further out.
class Membership extends Row {
  /// Wraps one decoded response object. Columns are read on access.
  Membership.fromJson(super.json) : super.fromJson();

  /// The table this row came from.
  static const String table = 'memberships';

  /// The memberships.id column.
  String get id => _str('id');

  /// The memberships.workspace_id column.
  String get workspaceId => _str('workspace_id');

  /// The memberships.user_id column.
  String get userId => _str('user_id');

  /// The memberships.role column.
  MembershipRole get role => _enum('role', MembershipRole.byWire);

  /// The memberships.created_at column.
  DateTime get createdAt => _time('created_at');

  /// The memberships.updated_at column.
  DateTime get updatedAt => _time('updated_at');

  /// Whether the request that produced this row returned [column].
  bool has(MembershipColumn column) => _present(column.wire);
}

/// The request body for creating a Membership.
///
/// Read-only columns are absent: the database or a BeforeCreate hook owns
/// them. A column with a default is optional, and leaving one out means the
/// database supplies the value.
class MembershipCreate {
  /// Builds a request body. A property with no default here is one the
  /// database has none for.
  const MembershipCreate({required this.userId, this.role});

  /// The memberships.user_id column.
  final String userId;

  /// The memberships.role column.
  final MembershipRole? role;

  /// The JSON body. Absent properties are the ones left unset.
  Map<String, dynamic> toJson() => {
    'user_id': _wire(userId),
    if (role != null) 'role': _wire(role),
  };
}

// ------------------------------------------------------------------- profiles

/// A user's extended profile. One-to-one with users: user_id is unique.
///
/// Reading a column the request did not return throws MissingColumn rather
/// than yielding null, so a projection that dropped a column is reported
/// where it is used instead of somewhere further out.
class Profile extends Row {
  /// Wraps one decoded response object. Columns are read on access.
  Profile.fromJson(super.json) : super.fromJson();

  /// The table this row came from.
  static const String table = 'profiles';

  /// The profiles.id column.
  String get id => _str('id');

  /// The profiles.user_id column.
  String get userId => _str('user_id');

  /// The profiles.bio column.
  String? get bio => _strOrNull('bio');

  /// The profiles.created_at column.
  DateTime get createdAt => _time('created_at');

  /// The profiles.updated_at column.
  DateTime get updatedAt => _time('updated_at');

  /// Whether the request that produced this row returned [column].
  bool has(ProfileColumn column) => _present(column.wire);
}

/// The request body for creating a Profile.
///
/// Read-only columns are absent: the database or a BeforeCreate hook owns
/// them. A column with a default is optional, and leaving one out means the
/// database supplies the value.
class ProfileCreate {
  /// Builds a request body. A property with no default here is one the
  /// database has none for.
  const ProfileCreate({required this.userId, this.bio});

  /// The profiles.user_id column.
  final String userId;

  /// The profiles.bio column.
  final String? bio;

  /// The JSON body. Absent properties are the ones left unset.
  Map<String, dynamic> toJson() => {
    'user_id': _wire(userId),
    if (bio != null) 'bio': _wire(bio),
  };
}

// ---------------------------------------------------------------------- tasks

/// The tasks.status column's value set.
enum TaskStatus implements WireValue {
  /// The value todo.
  todo('todo'),

  /// The value in_progress.
  inProgress('in_progress'),

  /// The value blocked.
  blocked('blocked'),

  /// The value done.
  done('done');

  const TaskStatus(this.wire);

  @override
  final String wire;

  /// The member [wire] names, or null when the server sent a value this
  /// client does not have — a value set that grew since it was generated.
  static TaskStatus? byWire(String wire) {
    for (final value in values) {
      if (value.wire == wire) return value;
    }
    return null;
  }
}

/// The tasks.priority column's value set.
enum TaskPriority implements WireValue {
  /// The value low.
  low('low'),

  /// The value medium.
  medium('medium'),

  /// The value high.
  high('high'),

  /// The value urgent.
  urgent('urgent');

  const TaskPriority(this.wire);

  @override
  final String wire;

  /// The member [wire] names, or null when the server sent a value this
  /// client does not have — a value set that grew since it was generated.
  static TaskPriority? byWire(String wire) {
    for (final value in values) {
      if (value.wire == wire) return value;
    }
    return null;
  }
}

/// A unit of work, belonging to one list.
///
/// Reading a column the request did not return throws MissingColumn rather
/// than yielding null, so a projection that dropped a column is reported
/// where it is used instead of somewhere further out.
class Task extends Row {
  /// Wraps one decoded response object. Columns are read on access.
  Task.fromJson(super.json) : super.fromJson();

  /// The table this row came from.
  static const String table = 'tasks';

  /// The tasks.id column.
  String get id => _str('id');

  /// The tasks.workspace_id column.
  String get workspaceId => _str('workspace_id');

  /// The tasks.list_id column.
  String get listId => _str('list_id');

  /// Filled in by expand: [TaskExpand.list], null otherwise.
  ListRow? get list => _one('list', ListRow.fromJson);

  /// The tasks.assignee_id column.
  String? get assigneeId => _strOrNull('assignee_id');

  /// The tasks.author_id column.
  String get authorId => _str('author_id');

  /// The tasks.title column.
  String get title => _str('title');

  /// The tasks.description column.
  String get description => _str('description');

  /// Free-form labels. Filter with has, hasany or hasall.
  List<String> get labels => _list('labels', _asStr);

  /// The tasks.status column.
  TaskStatus get status => _enum('status', TaskStatus.byWire);

  /// The tasks.priority column.
  TaskPriority get priority => _enum('priority', TaskPriority.byWire);

  /// The tasks.due_at column.
  DateTime? get dueAt => _timeOrNull('due_at');

  /// The tasks.completed_at column.
  DateTime? get completedAt => _timeOrNull('completed_at');

  /// The tasks.position column.
  int get position => _int('position');

  /// The tasks.comment_count column.
  int get commentCount => _int('comment_count');

  /// The tasks.created_at column.
  DateTime get createdAt => _time('created_at');

  /// The tasks.updated_at column.
  DateTime get updatedAt => _time('updated_at');

  /// The tasks.deleted_at column.
  DateTime? get deletedAt => _timeOrNull('deleted_at');

  /// Whether the request that produced this row returned [column].
  bool has(TaskColumn column) => _present(column.wire);
}

/// The request body for creating a Task.
///
/// Read-only columns are absent: the database or a BeforeCreate hook owns
/// them. A column with a default is optional, and leaving one out means the
/// database supplies the value.
class TaskCreate {
  /// Builds a request body. A property with no default here is one the
  /// database has none for.
  const TaskCreate({
    required this.listId,
    this.assigneeId,
    required this.title,
    required this.description,
    this.labels,
    this.status,
    this.priority,
    this.dueAt,
    this.position,
  });

  /// The tasks.list_id column.
  final String listId;

  /// The tasks.assignee_id column.
  final String? assigneeId;

  /// The tasks.title column.
  final String title;

  /// The tasks.description column.
  final String description;

  /// Free-form labels. Filter with has, hasany or hasall.
  final List<String>? labels;

  /// The tasks.status column.
  final TaskStatus? status;

  /// The tasks.priority column.
  final TaskPriority? priority;

  /// The tasks.due_at column.
  final DateTime? dueAt;

  /// The tasks.position column.
  final int? position;

  /// The JSON body. Absent properties are the ones left unset.
  Map<String, dynamic> toJson() => {
    'list_id': _wire(listId),
    if (assigneeId != null) 'assignee_id': _wire(assigneeId),
    'title': _wire(title),
    'description': _wire(description),
    if (labels != null) 'labels': _wire(labels),
    if (status != null) 'status': _wire(status),
    if (priority != null) 'priority': _wire(priority),
    if (dueAt != null) 'due_at': _wire(dueAt),
    if (position != null) 'position': _wire(position),
  };
}

/// The request body for patching a Task.
///
/// One method per writable column, so a patch carries exactly the columns it
/// named:
///
/// ```dart
/// final patch = TaskPatch()..listId(value);
/// ```
///
/// A method taking a nullable value writes NULL when passed null; a column
/// left unmentioned is not written at all. That distinction cannot be read off
/// a field, which is why these are methods and not a constructor.
class TaskPatch {
  final Map<String, dynamic> _changes = {};

  /// Writes tasks.list_id.
  void listId(String value) => _changes['list_id'] = _wire(value);

  /// Writes tasks.assignee_id. Passing null writes NULL.
  void assigneeId(String? value) => _changes['assignee_id'] = _wire(value);

  /// Writes tasks.title.
  void title(String value) => _changes['title'] = _wire(value);

  /// Writes tasks.description.
  void description(String value) => _changes['description'] = _wire(value);

  /// Free-form labels. Filter with has, hasany or hasall.
  ///
  /// Writes tasks.labels.
  void labels(List<String> value) => _changes['labels'] = _wire(value);

  /// Writes tasks.status.
  void status(TaskStatus value) => _changes['status'] = _wire(value);

  /// Writes tasks.priority.
  void priority(TaskPriority value) => _changes['priority'] = _wire(value);

  /// Writes tasks.due_at. Passing null writes NULL.
  void dueAt(DateTime? value) => _changes['due_at'] = _wire(value);

  /// Writes tasks.position.
  void position(int value) => _changes['position'] = _wire(value);

  /// Whether the patch would write nothing, which the server answers 400 to.
  bool get isEmpty => _changes.isEmpty;

  /// The JSON body: the columns this patch named, and no others.
  Map<String, dynamic> toJson() => Map<String, dynamic>.of(_changes);
}

/// The request body for POST /tasks/{id}/complete.
class CompleteTaskInput {
  /// Builds a request body. A property with no default here is one the
  /// action declares as required.
  const CompleteTaskInput({this.note});

  /// Recorded as a comment on the task, in the same transaction.
  final String? note;

  /// The JSON body. Absent properties are the ones left unset.
  Map<String, dynamic> toJson() => {if (note != null) 'note': _wire(note)};
}

// ---------------------------------------------------------------------- users

/// A row of users.
///
/// Reading a column the request did not return throws MissingColumn rather
/// than yielding null, so a projection that dropped a column is reported
/// where it is used instead of somewhere further out.
class User extends Row {
  /// Wraps one decoded response object. Columns are read on access.
  User.fromJson(super.json) : super.fromJson();

  /// The table this row came from.
  static const String table = 'users';

  /// The users.id column.
  String get id => _str('id');

  /// The users.email column.
  String get email => _str('email');

  /// The users.name column.
  String get name => _str('name');

  /// The users.created_at column.
  DateTime get createdAt => _time('created_at');

  /// The users.updated_at column.
  DateTime get updatedAt => _time('updated_at');

  /// Filled in by expand: [UserExpand.profile], null otherwise.
  Profile? get profile => _one('profile', Profile.fromJson);

  /// Whether the request that produced this row returned [column].
  bool has(UserColumn column) => _present(column.wire);
}

// ----------------------------------------------------------------- workspaces

/// A tenant. Lists, tasks and comments all belong to exactly one.
///
/// Reading a column the request did not return throws MissingColumn rather
/// than yielding null, so a projection that dropped a column is reported
/// where it is used instead of somewhere further out.
class Workspace extends Row {
  /// Wraps one decoded response object. Columns are read on access.
  Workspace.fromJson(super.json) : super.fromJson();

  /// The table this row came from.
  static const String table = 'workspaces';

  /// The workspaces.id column.
  String get id => _str('id');

  /// The workspaces.name column.
  String get name => _str('name');

  /// The workspaces.slug column.
  String get slug => _str('slug');

  /// The workspaces.created_at column.
  DateTime get createdAt => _time('created_at');

  /// The workspaces.updated_at column.
  DateTime get updatedAt => _time('updated_at');

  /// Whether the request that produced this row returned [column].
  bool has(WorkspaceColumn column) => _present(column.wire);
}

// ------------------------------------------------------------------ /comments

/// Columns [select] may name. The primary key is always returned.
enum CommentColumn implements WireValue {
  /// The comments.id column.
  id('id'),

  /// The comments.workspace_id column.
  workspaceId('workspace_id'),

  /// The comments.task_id column.
  taskId('task_id'),

  /// The comments.author_id column.
  authorId('author_id'),

  /// The comments.body column.
  body('body'),

  /// The comments.created_at column.
  createdAt('created_at'),

  /// The comments.updated_at column.
  updatedAt('updated_at'),

  /// The comments.deleted_at column.
  deletedAt('deleted_at');

  const CommentColumn(this.wire);

  @override
  final String wire;
}

/// Sortable columns. Take [asc] or [desc] to get a term [sort] accepts.
enum CommentSort implements WireValue {
  /// Order by comments.created_at.
  createdAt('created_at'),

  /// Order by comments.updated_at.
  updatedAt('updated_at');

  const CommentSort(this.wire);

  @override
  final String wire;

  /// Ascending.
  SortTerm get asc => SortTerm(wire);

  /// Descending.
  SortTerm get desc => SortTerm('-$wire');
}

/// Filter conditions, one property per filterable column.
///
/// The condition type is narrowed by the column: pattern operators exist only
/// on text, null tests only on a nullable column, and the value type is the
/// column's own — so a filter the server would answer 400 to does not compile.
class CommentWhere {
  /// Builds a filter. Every column is optional; naming two conjoins them.
  const CommentWhere({
    this.id,
    this.workspaceId,
    this.taskId,
    this.authorId,
    this.body,
  });

  /// Conditions on comments.id.
  final Cond<String>? id;

  /// Conditions on comments.workspace_id.
  final Cond<String>? workspaceId;

  /// Conditions on comments.task_id.
  final Cond<String>? taskId;

  /// Conditions on comments.author_id.
  final Cond<String>? authorId;

  /// Conditions on comments.body.
  final TextCond? body;

  void _encode(_Query out) {
    id?._encode(out, 'id');
    workspaceId?._encode(out, 'workspace_id');
    taskId?._encode(out, 'task_id');
    authorId?._encode(out, 'author_id');
    body?._encode(out, 'body');
  }
}

/// Parameters for GET /comments.
class CommentListParams {
  /// Builds a request. Every parameter is optional; the defaults are the
  /// server's.
  const CommentListParams({
    this.where,
    this.search,
    this.sort,
    this.select,
    this.page,
    this.perPage,
    this.cursor,
    this.countExact = false,
    this.params,
  });

  /// Filter conditions. Repeating a column conjoins its conditions.
  final CommentWhere? where;

  /// Case-insensitive substring match, fanned out over the searchable
  /// columns.
  final String? search;

  /// Ordering, most significant first.
  final List<SortTerm>? sort;

  /// Columns to return. Omitted columns are absent from the response, and
  /// reading one off the row throws MissingColumn. The primary key comes back
  /// whether or not it was asked for.
  final List<CommentColumn>? select;

  /// One-based page number. Prefer [cursor] for a deep walk.
  final int? page;

  /// Rows per page. The server caps this.
  final int? perPage;

  /// Resume after a nextCursor from a previous response. Cannot be combined
  /// with [page], and is only valid for the [sort] it was issued under.
  final String? cursor;

  /// Ask for a total row count, which costs the server a second query.
  final bool countExact;

  /// Parameters this vocabulary cannot express, appended verbatim. Reaching
  /// for it often means the typed layer is in the wrong place — ADR-0028 says
  /// so and names it as the signal to watch.
  final Map<String, List<String>>? params;

  /// The same parameters, resuming after [cursor].
  ///
  /// [page] is dropped: a page number and a cursor are two answers to where a
  /// page starts, and the server accepts only one of them.
  CommentListParams withCursor(String? cursor) => CommentListParams(
    where: where,
    search: search,
    sort: sort,
    select: select,
    perPage: perPage,
    cursor: cursor,
    countExact: countExact,
    params: params,
  );

  /// Encodes these parameters into the server's query grammar.
  String toQuery() {
    final out = _Query();
    where?._encode(out);
    if (search != null) out.set('search', search!);
    if (sort != null && sort!.isNotEmpty) {
      out.set('sort', sort!.map((term) => term.wire).join(','));
    }
    if (select != null && select!.isNotEmpty) {
      out.set('select', select!.map((column) => column.wire).join(','));
    }
    if (page != null) out.set('page', '$page');
    if (perPage != null) out.set('per_page', '$perPage');
    if (cursor != null) out.set('cursor', cursor!);
    if (countExact) out.set('count', 'exact');
    params?.forEach((key, values) {
      for (final value in values) {
        out.add(key, value);
      }
    });
    return out.build();
  }
}

/// Parameters for GET /comments/{id}.
///
/// There is no [select] here: the item endpoint rejects unknown query
/// parameters and does not declare one.
class CommentGetParams {
  /// Builds a request.
  const CommentGetParams();

  /// Always empty: this endpoint takes no parameters.
  String toQuery() => '';
}

/// GET /comments — the filtered, sorted, paged collection.
Future<Page<Comment>> listComments(
  Transport request, {
  CommentListParams params = const CommentListParams(),
  Object? cancel,
}) async {
  const path = '/comments';
  final json = await request(_get(path, params.toQuery(), cancel));
  return _page(json, Comment.fromJson);
}

/// GET /comments/{id} — one row by primary key.
Future<Comment> getComment(
  Transport request,
  Object id, {
  CommentGetParams params = const CommentGetParams(),
  Object? cancel,
}) async {
  final path = _itemPath('/comments', id);
  final json = await request(_get(path, params.toQuery(), cancel));
  return _row(json, Comment.fromJson);
}

/// POST /comments — create a row.
Future<Comment> createComment(
  Transport request,
  CommentCreate body, {
  Object? cancel,
}) async {
  const path = '/comments';
  final json = await request(_post(path, body.toJson(), cancel));
  return _row(json, Comment.fromJson);
}

/// A cursor walk over /comments, for a list that loads as it is scrolled.
///
/// [params] is the filter and ordering the whole walk runs under. Its [page]
/// and [cursor] are ignored: the pager owns where a page starts.
///
/// There is no cancel token, unlike the single-request functions. A walk is
/// many requests and a Dio CancelToken is one-shot, so cancelling to abandon
/// one page would poison every page after it.
CursorPager<Comment> commentPager(
  Transport request, {
  CommentListParams params = const CommentListParams(),
}) {
  return CursorPager<Comment>(
    (cursor) => listComments(request, params: params.withCursor(cursor)),
  );
}

// --------------------------------------------------------------------- /lists

/// Columns [select] may name. The primary key is always returned.
enum ListColumn implements WireValue {
  /// The lists.id column.
  id('id'),

  /// The lists.workspace_id column.
  workspaceId('workspace_id'),

  /// The lists.name column.
  name('name'),

  /// The lists.description column.
  description('description'),

  /// The lists.color column.
  color('color'),

  /// The lists.position column.
  position('position'),

  /// The lists.archived column.
  archived('archived'),

  /// The lists.created_at column.
  createdAt('created_at'),

  /// The lists.updated_at column.
  updatedAt('updated_at'),

  /// The lists.deleted_at column.
  deletedAt('deleted_at');

  const ListColumn(this.wire);

  @override
  final String wire;
}

/// Sortable columns. Take [asc] or [desc] to get a term [sort] accepts.
enum ListSort implements WireValue {
  /// Order by lists.name.
  name('name'),

  /// Order by lists.position.
  position('position'),

  /// Order by lists.archived.
  archived('archived'),

  /// Order by lists.created_at.
  createdAt('created_at'),

  /// Order by lists.updated_at.
  updatedAt('updated_at');

  const ListSort(this.wire);

  @override
  final String wire;

  /// Ascending.
  SortTerm get asc => SortTerm(wire);

  /// Descending.
  SortTerm get desc => SortTerm('-$wire');
}

/// Relations [expand] may name.
enum ListExpand implements WireValue {
  /// The tasks relation, a capped collection.
  tasks('tasks');

  const ListExpand(this.wire);

  @override
  final String wire;
}

/// Filter conditions, one property per filterable column.
///
/// The condition type is narrowed by the column: pattern operators exist only
/// on text, null tests only on a nullable column, and the value type is the
/// column's own — so a filter the server would answer 400 to does not compile.
class ListWhere {
  /// Builds a filter. Every column is optional; naming two conjoins them.
  const ListWhere({
    this.id,
    this.workspaceId,
    this.name,
    this.description,
    this.color,
    this.archived,
  });

  /// Conditions on lists.id.
  final Cond<String>? id;

  /// Conditions on lists.workspace_id.
  final Cond<String>? workspaceId;

  /// Conditions on lists.name.
  final TextCond? name;

  /// Conditions on lists.description.
  final TextCond? description;

  /// Conditions on lists.color.
  final TextCond? color;

  /// Conditions on lists.archived.
  final Cond<bool>? archived;

  void _encode(_Query out) {
    id?._encode(out, 'id');
    workspaceId?._encode(out, 'workspace_id');
    name?._encode(out, 'name');
    description?._encode(out, 'description');
    color?._encode(out, 'color');
    archived?._encode(out, 'archived');
  }
}

/// Parameters for GET /lists.
class ListListParams {
  /// Builds a request. Every parameter is optional; the defaults are the
  /// server's.
  const ListListParams({
    this.where,
    this.search,
    this.sort,
    this.select,
    this.expand,
    this.page,
    this.perPage,
    this.cursor,
    this.countExact = false,
    this.params,
  });

  /// Filter conditions. Repeating a column conjoins its conditions.
  final ListWhere? where;

  /// Case-insensitive substring match, fanned out over the searchable
  /// columns.
  final String? search;

  /// Ordering, most significant first.
  final List<SortTerm>? sort;

  /// Columns to return. Omitted columns are absent from the response, and
  /// reading one off the row throws MissingColumn. The primary key comes back
  /// whether or not it was asked for.
  final List<ListColumn>? select;

  /// Relations to pull in alongside each row.
  final List<ListExpand>? expand;

  /// One-based page number. Prefer [cursor] for a deep walk.
  final int? page;

  /// Rows per page. The server caps this.
  final int? perPage;

  /// Resume after a nextCursor from a previous response. Cannot be combined
  /// with [page], and is only valid for the [sort] it was issued under.
  final String? cursor;

  /// Ask for a total row count, which costs the server a second query.
  final bool countExact;

  /// Parameters this vocabulary cannot express, appended verbatim. Reaching
  /// for it often means the typed layer is in the wrong place — ADR-0028 says
  /// so and names it as the signal to watch.
  final Map<String, List<String>>? params;

  /// The same parameters, resuming after [cursor].
  ///
  /// [page] is dropped: a page number and a cursor are two answers to where a
  /// page starts, and the server accepts only one of them.
  ListListParams withCursor(String? cursor) => ListListParams(
    where: where,
    search: search,
    sort: sort,
    select: select,
    expand: expand,
    perPage: perPage,
    cursor: cursor,
    countExact: countExact,
    params: params,
  );

  /// Encodes these parameters into the server's query grammar.
  String toQuery() {
    final out = _Query();
    where?._encode(out);
    if (search != null) out.set('search', search!);
    if (sort != null && sort!.isNotEmpty) {
      out.set('sort', sort!.map((term) => term.wire).join(','));
    }
    if (select != null && select!.isNotEmpty) {
      out.set('select', select!.map((column) => column.wire).join(','));
    }
    if (expand != null && expand!.isNotEmpty) {
      out.set('expand', expand!.map((relation) => relation.wire).join(','));
    }
    if (page != null) out.set('page', '$page');
    if (perPage != null) out.set('per_page', '$perPage');
    if (cursor != null) out.set('cursor', cursor!);
    if (countExact) out.set('count', 'exact');
    params?.forEach((key, values) {
      for (final value in values) {
        out.add(key, value);
      }
    });
    return out.build();
  }
}

/// Parameters for GET /lists/{id}.
///
/// There is no [select] here: the item endpoint rejects unknown query
/// parameters and does not declare one.
class ListGetParams {
  /// Builds a request.
  const ListGetParams({this.expand});

  /// Relations to pull in alongside the row.
  final List<ListExpand>? expand;

  /// Encodes these parameters into the server's query grammar.
  String toQuery() {
    final out = _Query();
    if (expand != null && expand!.isNotEmpty) {
      out.set('expand', expand!.map((relation) => relation.wire).join(','));
    }
    return out.build();
  }
}

/// GET /lists — the filtered, sorted, paged collection.
Future<Page<ListRow>> listLists(
  Transport request, {
  ListListParams params = const ListListParams(),
  Object? cancel,
}) async {
  const path = '/lists';
  final json = await request(_get(path, params.toQuery(), cancel));
  return _page(json, ListRow.fromJson);
}

/// GET /lists/{id} — one row by primary key.
Future<ListRow> getList(
  Transport request,
  Object id, {
  ListGetParams params = const ListGetParams(),
  Object? cancel,
}) async {
  final path = _itemPath('/lists', id);
  final json = await request(_get(path, params.toQuery(), cancel));
  return _row(json, ListRow.fromJson);
}

/// POST /lists — create a row.
Future<ListRow> createList(
  Transport request,
  ListCreate body, {
  Object? cancel,
}) async {
  const path = '/lists';
  final json = await request(_post(path, body.toJson(), cancel));
  return _row(json, ListRow.fromJson);
}

/// PATCH /lists/{id} — write the columns the body named, and no others.
Future<ListRow> updateList(
  Transport request,
  Object id,
  ListPatch body, {
  Object? cancel,
}) async {
  final path = _itemPath('/lists', id);
  final json = await request(_patch(path, body.toJson(), cancel));
  return _row(json, ListRow.fromJson);
}

/// A cursor walk over /lists, for a list that loads as it is scrolled.
///
/// [params] is the filter and ordering the whole walk runs under. Its [page]
/// and [cursor] are ignored: the pager owns where a page starts.
///
/// There is no cancel token, unlike the single-request functions. A walk is
/// many requests and a Dio CancelToken is one-shot, so cancelling to abandon
/// one page would poison every page after it.
CursorPager<ListRow> listPager(
  Transport request, {
  ListListParams params = const ListListParams(),
}) {
  return CursorPager<ListRow>(
    (cursor) => listLists(request, params: params.withCursor(cursor)),
  );
}

// --------------------------------------------------------------- /memberships

/// Columns [select] may name. The primary key is always returned.
enum MembershipColumn implements WireValue {
  /// The memberships.id column.
  id('id'),

  /// The memberships.workspace_id column.
  workspaceId('workspace_id'),

  /// The memberships.user_id column.
  userId('user_id'),

  /// The memberships.role column.
  role('role'),

  /// The memberships.created_at column.
  createdAt('created_at'),

  /// The memberships.updated_at column.
  updatedAt('updated_at');

  const MembershipColumn(this.wire);

  @override
  final String wire;
}

/// Sortable columns. Take [asc] or [desc] to get a term [sort] accepts.
enum MembershipSort implements WireValue {
  /// Order by memberships.role.
  role('role'),

  /// Order by memberships.created_at.
  createdAt('created_at'),

  /// Order by memberships.updated_at.
  updatedAt('updated_at');

  const MembershipSort(this.wire);

  @override
  final String wire;

  /// Ascending.
  SortTerm get asc => SortTerm(wire);

  /// Descending.
  SortTerm get desc => SortTerm('-$wire');
}

/// Filter conditions, one property per filterable column.
///
/// The condition type is narrowed by the column: pattern operators exist only
/// on text, null tests only on a nullable column, and the value type is the
/// column's own — so a filter the server would answer 400 to does not compile.
class MembershipWhere {
  /// Builds a filter. Every column is optional; naming two conjoins them.
  const MembershipWhere({this.id, this.workspaceId, this.userId, this.role});

  /// Conditions on memberships.id.
  final Cond<String>? id;

  /// Conditions on memberships.workspace_id.
  final Cond<String>? workspaceId;

  /// Conditions on memberships.user_id.
  final Cond<String>? userId;

  /// Conditions on memberships.role.
  final Cond<MembershipRole>? role;

  void _encode(_Query out) {
    id?._encode(out, 'id');
    workspaceId?._encode(out, 'workspace_id');
    userId?._encode(out, 'user_id');
    role?._encode(out, 'role');
  }
}

/// Parameters for GET /memberships.
class MembershipListParams {
  /// Builds a request. Every parameter is optional; the defaults are the
  /// server's.
  const MembershipListParams({
    this.where,
    this.sort,
    this.select,
    this.page,
    this.perPage,
    this.cursor,
    this.countExact = false,
    this.params,
  });

  /// Filter conditions. Repeating a column conjoins its conditions.
  final MembershipWhere? where;

  /// Ordering, most significant first.
  final List<SortTerm>? sort;

  /// Columns to return. Omitted columns are absent from the response, and
  /// reading one off the row throws MissingColumn. The primary key comes back
  /// whether or not it was asked for.
  final List<MembershipColumn>? select;

  /// One-based page number. Prefer [cursor] for a deep walk.
  final int? page;

  /// Rows per page. The server caps this.
  final int? perPage;

  /// Resume after a nextCursor from a previous response. Cannot be combined
  /// with [page], and is only valid for the [sort] it was issued under.
  final String? cursor;

  /// Ask for a total row count, which costs the server a second query.
  final bool countExact;

  /// Parameters this vocabulary cannot express, appended verbatim. Reaching
  /// for it often means the typed layer is in the wrong place — ADR-0028 says
  /// so and names it as the signal to watch.
  final Map<String, List<String>>? params;

  /// The same parameters, resuming after [cursor].
  ///
  /// [page] is dropped: a page number and a cursor are two answers to where a
  /// page starts, and the server accepts only one of them.
  MembershipListParams withCursor(String? cursor) => MembershipListParams(
    where: where,
    sort: sort,
    select: select,
    perPage: perPage,
    cursor: cursor,
    countExact: countExact,
    params: params,
  );

  /// Encodes these parameters into the server's query grammar.
  String toQuery() {
    final out = _Query();
    where?._encode(out);
    if (sort != null && sort!.isNotEmpty) {
      out.set('sort', sort!.map((term) => term.wire).join(','));
    }
    if (select != null && select!.isNotEmpty) {
      out.set('select', select!.map((column) => column.wire).join(','));
    }
    if (page != null) out.set('page', '$page');
    if (perPage != null) out.set('per_page', '$perPage');
    if (cursor != null) out.set('cursor', cursor!);
    if (countExact) out.set('count', 'exact');
    params?.forEach((key, values) {
      for (final value in values) {
        out.add(key, value);
      }
    });
    return out.build();
  }
}

/// Parameters for GET /memberships/{id}.
///
/// There is no [select] here: the item endpoint rejects unknown query
/// parameters and does not declare one.
class MembershipGetParams {
  /// Builds a request.
  const MembershipGetParams();

  /// Always empty: this endpoint takes no parameters.
  String toQuery() => '';
}

/// GET /memberships — the filtered, sorted, paged collection.
Future<Page<Membership>> listMemberships(
  Transport request, {
  MembershipListParams params = const MembershipListParams(),
  Object? cancel,
}) async {
  const path = '/memberships';
  final json = await request(_get(path, params.toQuery(), cancel));
  return _page(json, Membership.fromJson);
}

/// GET /memberships/{id} — one row by primary key.
Future<Membership> getMembership(
  Transport request,
  Object id, {
  MembershipGetParams params = const MembershipGetParams(),
  Object? cancel,
}) async {
  final path = _itemPath('/memberships', id);
  final json = await request(_get(path, params.toQuery(), cancel));
  return _row(json, Membership.fromJson);
}

/// POST /memberships — create a row.
Future<Membership> createMembership(
  Transport request,
  MembershipCreate body, {
  Object? cancel,
}) async {
  const path = '/memberships';
  final json = await request(_post(path, body.toJson(), cancel));
  return _row(json, Membership.fromJson);
}

/// DELETE /memberships/{id}.
Future<void> deleteMembership(
  Transport request,
  Object id, {
  Object? cancel,
}) async {
  final path = _itemPath('/memberships', id);
  await request(_delete(path, cancel));
}

/// A cursor walk over /memberships, for a list that loads as it is scrolled.
///
/// [params] is the filter and ordering the whole walk runs under. Its [page]
/// and [cursor] are ignored: the pager owns where a page starts.
///
/// There is no cancel token, unlike the single-request functions. A walk is
/// many requests and a Dio CancelToken is one-shot, so cancelling to abandon
/// one page would poison every page after it.
CursorPager<Membership> membershipPager(
  Transport request, {
  MembershipListParams params = const MembershipListParams(),
}) {
  return CursorPager<Membership>(
    (cursor) => listMemberships(request, params: params.withCursor(cursor)),
  );
}

// ------------------------------------------------------------------ /profiles

/// Columns [select] may name. The primary key is always returned.
enum ProfileColumn implements WireValue {
  /// The profiles.id column.
  id('id'),

  /// The profiles.user_id column.
  userId('user_id'),

  /// The profiles.bio column.
  bio('bio'),

  /// The profiles.created_at column.
  createdAt('created_at'),

  /// The profiles.updated_at column.
  updatedAt('updated_at');

  const ProfileColumn(this.wire);

  @override
  final String wire;
}

/// Sortable columns. Take [asc] or [desc] to get a term [sort] accepts.
enum ProfileSort implements WireValue {
  /// Order by profiles.created_at.
  createdAt('created_at'),

  /// Order by profiles.updated_at.
  updatedAt('updated_at');

  const ProfileSort(this.wire);

  @override
  final String wire;

  /// Ascending.
  SortTerm get asc => SortTerm(wire);

  /// Descending.
  SortTerm get desc => SortTerm('-$wire');
}

/// Filter conditions, one property per filterable column.
///
/// The condition type is narrowed by the column: pattern operators exist only
/// on text, null tests only on a nullable column, and the value type is the
/// column's own — so a filter the server would answer 400 to does not compile.
class ProfileWhere {
  /// Builds a filter. Every column is optional; naming two conjoins them.
  const ProfileWhere({this.id});

  /// Conditions on profiles.id.
  final Cond<String>? id;

  void _encode(_Query out) {
    id?._encode(out, 'id');
  }
}

/// POST /profiles — create a row.
Future<Profile> createProfile(
  Transport request,
  ProfileCreate body, {
  Object? cancel,
}) async {
  const path = '/profiles';
  final json = await request(_post(path, body.toJson(), cancel));
  return _row(json, Profile.fromJson);
}

// --------------------------------------------------------------------- /tasks

/// Columns [select] may name. The primary key is always returned.
enum TaskColumn implements WireValue {
  /// The tasks.id column.
  id('id'),

  /// The tasks.workspace_id column.
  workspaceId('workspace_id'),

  /// The tasks.list_id column.
  listId('list_id'),

  /// The tasks.assignee_id column.
  assigneeId('assignee_id'),

  /// The tasks.author_id column.
  authorId('author_id'),

  /// The tasks.title column.
  title('title'),

  /// The tasks.description column.
  description('description'),

  /// The tasks.labels column.
  labels('labels'),

  /// The tasks.status column.
  status('status'),

  /// The tasks.priority column.
  priority('priority'),

  /// The tasks.due_at column.
  dueAt('due_at'),

  /// The tasks.completed_at column.
  completedAt('completed_at'),

  /// The tasks.position column.
  position('position'),

  /// The tasks.comment_count column.
  commentCount('comment_count'),

  /// The tasks.created_at column.
  createdAt('created_at'),

  /// The tasks.updated_at column.
  updatedAt('updated_at'),

  /// The tasks.deleted_at column.
  deletedAt('deleted_at');

  const TaskColumn(this.wire);

  @override
  final String wire;
}

/// Sortable columns. Take [asc] or [desc] to get a term [sort] accepts.
enum TaskSort implements WireValue {
  /// Order by tasks.title.
  title('title'),

  /// Order by tasks.status.
  status('status'),

  /// Order by tasks.priority.
  priority('priority'),

  /// Order by tasks.due_at.
  dueAt('due_at'),

  /// Order by tasks.completed_at.
  completedAt('completed_at'),

  /// Order by tasks.position.
  position('position'),

  /// Order by tasks.comment_count.
  commentCount('comment_count'),

  /// Order by tasks.created_at.
  createdAt('created_at'),

  /// Order by tasks.updated_at.
  updatedAt('updated_at');

  const TaskSort(this.wire);

  @override
  final String wire;

  /// Ascending.
  SortTerm get asc => SortTerm(wire);

  /// Descending.
  SortTerm get desc => SortTerm('-$wire');
}

/// Relations [expand] may name.
enum TaskExpand implements WireValue {
  /// The list relation, one row.
  list('list');

  const TaskExpand(this.wire);

  @override
  final String wire;
}

/// Filter conditions, one property per filterable column.
///
/// The condition type is narrowed by the column: pattern operators exist only
/// on text, null tests only on a nullable column, and the value type is the
/// column's own — so a filter the server would answer 400 to does not compile.
class TaskWhere {
  /// Builds a filter. Every column is optional; naming two conjoins them.
  const TaskWhere({
    this.id,
    this.workspaceId,
    this.listId,
    this.assigneeId,
    this.title,
    this.description,
    this.labels,
    this.status,
    this.priority,
    this.dueAt,
    this.completedAt,
    this.commentCount,
  });

  /// Conditions on tasks.id.
  final Cond<String>? id;

  /// Conditions on tasks.workspace_id.
  final Cond<String>? workspaceId;

  /// Conditions on tasks.list_id.
  final Cond<String>? listId;

  /// Conditions on tasks.assignee_id.
  final NullableCond<String>? assigneeId;

  /// Conditions on tasks.title.
  final TextCond? title;

  /// Conditions on tasks.description.
  final TextCond? description;

  /// Free-form labels. Filter with has, hasany or hasall.
  ///
  /// Conditions on tasks.labels.
  final ArrayCond<String>? labels;

  /// Conditions on tasks.status.
  final Cond<TaskStatus>? status;

  /// Conditions on tasks.priority.
  final Cond<TaskPriority>? priority;

  /// Conditions on tasks.due_at.
  final NullableCond<DateTime>? dueAt;

  /// Conditions on tasks.completed_at.
  final NullableCond<DateTime>? completedAt;

  /// Conditions on tasks.comment_count.
  final Cond<int>? commentCount;

  void _encode(_Query out) {
    id?._encode(out, 'id');
    workspaceId?._encode(out, 'workspace_id');
    listId?._encode(out, 'list_id');
    assigneeId?._encode(out, 'assignee_id');
    title?._encode(out, 'title');
    description?._encode(out, 'description');
    labels?._encode(out, 'labels');
    status?._encode(out, 'status');
    priority?._encode(out, 'priority');
    dueAt?._encode(out, 'due_at');
    completedAt?._encode(out, 'completed_at');
    commentCount?._encode(out, 'comment_count');
  }
}

/// Parameters for GET /tasks.
class TaskListParams {
  /// Builds a request. Every parameter is optional; the defaults are the
  /// server's.
  const TaskListParams({
    this.where,
    this.search,
    this.sort,
    this.select,
    this.expand,
    this.page,
    this.perPage,
    this.cursor,
    this.countExact = false,
    this.params,
  });

  /// Filter conditions. Repeating a column conjoins its conditions.
  final TaskWhere? where;

  /// Case-insensitive substring match, fanned out over the searchable
  /// columns.
  final String? search;

  /// Ordering, most significant first.
  final List<SortTerm>? sort;

  /// Columns to return. Omitted columns are absent from the response, and
  /// reading one off the row throws MissingColumn. The primary key comes back
  /// whether or not it was asked for.
  final List<TaskColumn>? select;

  /// Relations to pull in alongside each row.
  final List<TaskExpand>? expand;

  /// One-based page number. Prefer [cursor] for a deep walk.
  final int? page;

  /// Rows per page. The server caps this.
  final int? perPage;

  /// Resume after a nextCursor from a previous response. Cannot be combined
  /// with [page], and is only valid for the [sort] it was issued under.
  final String? cursor;

  /// Ask for a total row count, which costs the server a second query.
  final bool countExact;

  /// Parameters this vocabulary cannot express, appended verbatim. Reaching
  /// for it often means the typed layer is in the wrong place — ADR-0028 says
  /// so and names it as the signal to watch.
  final Map<String, List<String>>? params;

  /// The same parameters, resuming after [cursor].
  ///
  /// [page] is dropped: a page number and a cursor are two answers to where a
  /// page starts, and the server accepts only one of them.
  TaskListParams withCursor(String? cursor) => TaskListParams(
    where: where,
    search: search,
    sort: sort,
    select: select,
    expand: expand,
    perPage: perPage,
    cursor: cursor,
    countExact: countExact,
    params: params,
  );

  /// Encodes these parameters into the server's query grammar.
  String toQuery() {
    final out = _Query();
    where?._encode(out);
    if (search != null) out.set('search', search!);
    if (sort != null && sort!.isNotEmpty) {
      out.set('sort', sort!.map((term) => term.wire).join(','));
    }
    if (select != null && select!.isNotEmpty) {
      out.set('select', select!.map((column) => column.wire).join(','));
    }
    if (expand != null && expand!.isNotEmpty) {
      out.set('expand', expand!.map((relation) => relation.wire).join(','));
    }
    if (page != null) out.set('page', '$page');
    if (perPage != null) out.set('per_page', '$perPage');
    if (cursor != null) out.set('cursor', cursor!);
    if (countExact) out.set('count', 'exact');
    params?.forEach((key, values) {
      for (final value in values) {
        out.add(key, value);
      }
    });
    return out.build();
  }
}

/// Parameters for GET /tasks/{id}.
///
/// There is no [select] here: the item endpoint rejects unknown query
/// parameters and does not declare one.
class TaskGetParams {
  /// Builds a request.
  const TaskGetParams({this.expand});

  /// Relations to pull in alongside the row.
  final List<TaskExpand>? expand;

  /// Encodes these parameters into the server's query grammar.
  String toQuery() {
    final out = _Query();
    if (expand != null && expand!.isNotEmpty) {
      out.set('expand', expand!.map((relation) => relation.wire).join(','));
    }
    return out.build();
  }
}

/// GET /tasks — the filtered, sorted, paged collection.
Future<Page<Task>> listTasks(
  Transport request, {
  TaskListParams params = const TaskListParams(),
  Object? cancel,
}) async {
  const path = '/tasks';
  final json = await request(_get(path, params.toQuery(), cancel));
  return _page(json, Task.fromJson);
}

/// GET /tasks/{id} — one row by primary key.
Future<Task> getTask(
  Transport request,
  Object id, {
  TaskGetParams params = const TaskGetParams(),
  Object? cancel,
}) async {
  final path = _itemPath('/tasks', id);
  final json = await request(_get(path, params.toQuery(), cancel));
  return _row(json, Task.fromJson);
}

/// POST /tasks — create a row.
Future<Task> createTask(
  Transport request,
  TaskCreate body, {
  Object? cancel,
}) async {
  const path = '/tasks';
  final json = await request(_post(path, body.toJson(), cancel));
  return _row(json, Task.fromJson);
}

/// PATCH /tasks/{id} — write the columns the body named, and no others.
Future<Task> updateTask(
  Transport request,
  Object id,
  TaskPatch body, {
  Object? cancel,
}) async {
  final path = _itemPath('/tasks', id);
  final json = await request(_patch(path, body.toJson(), cancel));
  return _row(json, Task.fromJson);
}

/// POST /tasks/{id}/complete — complete a task.
Future<Task> completeTask(
  Transport request,
  Object id,
  CompleteTaskInput body, {
  Object? cancel,
}) async {
  final item = _itemPath('/tasks', id);
  final path = '$item/complete';
  final json = await request(_post(path, body.toJson(), cancel));
  return _row(json, Task.fromJson);
}

/// A cursor walk over /tasks, for a list that loads as it is scrolled.
///
/// [params] is the filter and ordering the whole walk runs under. Its [page]
/// and [cursor] are ignored: the pager owns where a page starts.
///
/// There is no cancel token, unlike the single-request functions. A walk is
/// many requests and a Dio CancelToken is one-shot, so cancelling to abandon
/// one page would poison every page after it.
CursorPager<Task> taskPager(
  Transport request, {
  TaskListParams params = const TaskListParams(),
}) {
  return CursorPager<Task>(
    (cursor) => listTasks(request, params: params.withCursor(cursor)),
  );
}

// --------------------------------------------------------------------- /users

/// Columns [select] may name. The primary key is always returned.
enum UserColumn implements WireValue {
  /// The users.id column.
  id('id'),

  /// The users.email column.
  email('email'),

  /// The users.name column.
  name('name'),

  /// The users.created_at column.
  createdAt('created_at'),

  /// The users.updated_at column.
  updatedAt('updated_at');

  const UserColumn(this.wire);

  @override
  final String wire;
}

/// Sortable columns. Take [asc] or [desc] to get a term [sort] accepts.
enum UserSort implements WireValue {
  /// Order by users.name.
  name('name'),

  /// Order by users.created_at.
  createdAt('created_at'),

  /// Order by users.updated_at.
  updatedAt('updated_at');

  const UserSort(this.wire);

  @override
  final String wire;

  /// Ascending.
  SortTerm get asc => SortTerm(wire);

  /// Descending.
  SortTerm get desc => SortTerm('-$wire');
}

/// Relations [expand] may name.
enum UserExpand implements WireValue {
  /// The profile relation, one row.
  profile('profile');

  const UserExpand(this.wire);

  @override
  final String wire;
}

/// Filter conditions, one property per filterable column.
///
/// The condition type is narrowed by the column: pattern operators exist only
/// on text, null tests only on a nullable column, and the value type is the
/// column's own — so a filter the server would answer 400 to does not compile.
class UserWhere {
  /// Builds a filter. Every column is optional; naming two conjoins them.
  const UserWhere({this.id, this.email, this.name});

  /// Conditions on users.id.
  final Cond<String>? id;

  /// Conditions on users.email.
  final TextCond? email;

  /// Conditions on users.name.
  final TextCond? name;

  void _encode(_Query out) {
    id?._encode(out, 'id');
    email?._encode(out, 'email');
    name?._encode(out, 'name');
  }
}

/// Parameters for GET /users.
class UserListParams {
  /// Builds a request. Every parameter is optional; the defaults are the
  /// server's.
  const UserListParams({
    this.where,
    this.search,
    this.sort,
    this.select,
    this.expand,
    this.page,
    this.perPage,
    this.cursor,
    this.countExact = false,
    this.params,
  });

  /// Filter conditions. Repeating a column conjoins its conditions.
  final UserWhere? where;

  /// Case-insensitive substring match, fanned out over the searchable
  /// columns.
  final String? search;

  /// Ordering, most significant first.
  final List<SortTerm>? sort;

  /// Columns to return. Omitted columns are absent from the response, and
  /// reading one off the row throws MissingColumn. The primary key comes back
  /// whether or not it was asked for.
  final List<UserColumn>? select;

  /// Relations to pull in alongside each row.
  final List<UserExpand>? expand;

  /// One-based page number. Prefer [cursor] for a deep walk.
  final int? page;

  /// Rows per page. The server caps this.
  final int? perPage;

  /// Resume after a nextCursor from a previous response. Cannot be combined
  /// with [page], and is only valid for the [sort] it was issued under.
  final String? cursor;

  /// Ask for a total row count, which costs the server a second query.
  final bool countExact;

  /// Parameters this vocabulary cannot express, appended verbatim. Reaching
  /// for it often means the typed layer is in the wrong place — ADR-0028 says
  /// so and names it as the signal to watch.
  final Map<String, List<String>>? params;

  /// The same parameters, resuming after [cursor].
  ///
  /// [page] is dropped: a page number and a cursor are two answers to where a
  /// page starts, and the server accepts only one of them.
  UserListParams withCursor(String? cursor) => UserListParams(
    where: where,
    search: search,
    sort: sort,
    select: select,
    expand: expand,
    perPage: perPage,
    cursor: cursor,
    countExact: countExact,
    params: params,
  );

  /// Encodes these parameters into the server's query grammar.
  String toQuery() {
    final out = _Query();
    where?._encode(out);
    if (search != null) out.set('search', search!);
    if (sort != null && sort!.isNotEmpty) {
      out.set('sort', sort!.map((term) => term.wire).join(','));
    }
    if (select != null && select!.isNotEmpty) {
      out.set('select', select!.map((column) => column.wire).join(','));
    }
    if (expand != null && expand!.isNotEmpty) {
      out.set('expand', expand!.map((relation) => relation.wire).join(','));
    }
    if (page != null) out.set('page', '$page');
    if (perPage != null) out.set('per_page', '$perPage');
    if (cursor != null) out.set('cursor', cursor!);
    if (countExact) out.set('count', 'exact');
    params?.forEach((key, values) {
      for (final value in values) {
        out.add(key, value);
      }
    });
    return out.build();
  }
}

/// Parameters for GET /users/{id}.
///
/// There is no [select] here: the item endpoint rejects unknown query
/// parameters and does not declare one.
class UserGetParams {
  /// Builds a request.
  const UserGetParams({this.expand});

  /// Relations to pull in alongside the row.
  final List<UserExpand>? expand;

  /// Encodes these parameters into the server's query grammar.
  String toQuery() {
    final out = _Query();
    if (expand != null && expand!.isNotEmpty) {
      out.set('expand', expand!.map((relation) => relation.wire).join(','));
    }
    return out.build();
  }
}

/// GET /users — the filtered, sorted, paged collection.
Future<Page<User>> listUsers(
  Transport request, {
  UserListParams params = const UserListParams(),
  Object? cancel,
}) async {
  const path = '/users';
  final json = await request(_get(path, params.toQuery(), cancel));
  return _page(json, User.fromJson);
}

/// GET /users/{id} — one row by primary key.
Future<User> getUser(
  Transport request,
  Object id, {
  UserGetParams params = const UserGetParams(),
  Object? cancel,
}) async {
  final path = _itemPath('/users', id);
  final json = await request(_get(path, params.toQuery(), cancel));
  return _row(json, User.fromJson);
}

/// A cursor walk over /users, for a list that loads as it is scrolled.
///
/// [params] is the filter and ordering the whole walk runs under. Its [page]
/// and [cursor] are ignored: the pager owns where a page starts.
///
/// There is no cancel token, unlike the single-request functions. A walk is
/// many requests and a Dio CancelToken is one-shot, so cancelling to abandon
/// one page would poison every page after it.
CursorPager<User> userPager(
  Transport request, {
  UserListParams params = const UserListParams(),
}) {
  return CursorPager<User>(
    (cursor) => listUsers(request, params: params.withCursor(cursor)),
  );
}

// ---------------------------------------------------------------- /workspaces

/// Columns [select] may name. The primary key is always returned.
enum WorkspaceColumn implements WireValue {
  /// The workspaces.id column.
  id('id'),

  /// The workspaces.name column.
  name('name'),

  /// The workspaces.slug column.
  slug('slug'),

  /// The workspaces.created_at column.
  createdAt('created_at'),

  /// The workspaces.updated_at column.
  updatedAt('updated_at');

  const WorkspaceColumn(this.wire);

  @override
  final String wire;
}

/// Sortable columns. Take [asc] or [desc] to get a term [sort] accepts.
enum WorkspaceSort implements WireValue {
  /// Order by workspaces.name.
  name('name'),

  /// Order by workspaces.created_at.
  createdAt('created_at'),

  /// Order by workspaces.updated_at.
  updatedAt('updated_at');

  const WorkspaceSort(this.wire);

  @override
  final String wire;

  /// Ascending.
  SortTerm get asc => SortTerm(wire);

  /// Descending.
  SortTerm get desc => SortTerm('-$wire');
}

/// Filter conditions, one property per filterable column.
///
/// The condition type is narrowed by the column: pattern operators exist only
/// on text, null tests only on a nullable column, and the value type is the
/// column's own — so a filter the server would answer 400 to does not compile.
class WorkspaceWhere {
  /// Builds a filter. Every column is optional; naming two conjoins them.
  const WorkspaceWhere({this.id, this.name, this.slug});

  /// Conditions on workspaces.id.
  final Cond<String>? id;

  /// Conditions on workspaces.name.
  final TextCond? name;

  /// Conditions on workspaces.slug.
  final TextCond? slug;

  void _encode(_Query out) {
    id?._encode(out, 'id');
    name?._encode(out, 'name');
    slug?._encode(out, 'slug');
  }
}

/// Parameters for GET /workspaces.
class WorkspaceListParams {
  /// Builds a request. Every parameter is optional; the defaults are the
  /// server's.
  const WorkspaceListParams({
    this.where,
    this.search,
    this.sort,
    this.select,
    this.page,
    this.perPage,
    this.cursor,
    this.countExact = false,
    this.params,
  });

  /// Filter conditions. Repeating a column conjoins its conditions.
  final WorkspaceWhere? where;

  /// Case-insensitive substring match, fanned out over the searchable
  /// columns.
  final String? search;

  /// Ordering, most significant first.
  final List<SortTerm>? sort;

  /// Columns to return. Omitted columns are absent from the response, and
  /// reading one off the row throws MissingColumn. The primary key comes back
  /// whether or not it was asked for.
  final List<WorkspaceColumn>? select;

  /// One-based page number. Prefer [cursor] for a deep walk.
  final int? page;

  /// Rows per page. The server caps this.
  final int? perPage;

  /// Resume after a nextCursor from a previous response. Cannot be combined
  /// with [page], and is only valid for the [sort] it was issued under.
  final String? cursor;

  /// Ask for a total row count, which costs the server a second query.
  final bool countExact;

  /// Parameters this vocabulary cannot express, appended verbatim. Reaching
  /// for it often means the typed layer is in the wrong place — ADR-0028 says
  /// so and names it as the signal to watch.
  final Map<String, List<String>>? params;

  /// The same parameters, resuming after [cursor].
  ///
  /// [page] is dropped: a page number and a cursor are two answers to where a
  /// page starts, and the server accepts only one of them.
  WorkspaceListParams withCursor(String? cursor) => WorkspaceListParams(
    where: where,
    search: search,
    sort: sort,
    select: select,
    perPage: perPage,
    cursor: cursor,
    countExact: countExact,
    params: params,
  );

  /// Encodes these parameters into the server's query grammar.
  String toQuery() {
    final out = _Query();
    where?._encode(out);
    if (search != null) out.set('search', search!);
    if (sort != null && sort!.isNotEmpty) {
      out.set('sort', sort!.map((term) => term.wire).join(','));
    }
    if (select != null && select!.isNotEmpty) {
      out.set('select', select!.map((column) => column.wire).join(','));
    }
    if (page != null) out.set('page', '$page');
    if (perPage != null) out.set('per_page', '$perPage');
    if (cursor != null) out.set('cursor', cursor!);
    if (countExact) out.set('count', 'exact');
    params?.forEach((key, values) {
      for (final value in values) {
        out.add(key, value);
      }
    });
    return out.build();
  }
}

/// Parameters for GET /workspaces/{id}.
///
/// There is no [select] here: the item endpoint rejects unknown query
/// parameters and does not declare one.
class WorkspaceGetParams {
  /// Builds a request.
  const WorkspaceGetParams();

  /// Always empty: this endpoint takes no parameters.
  String toQuery() => '';
}

/// GET /workspaces — the filtered, sorted, paged collection.
Future<Page<Workspace>> listWorkspaces(
  Transport request, {
  WorkspaceListParams params = const WorkspaceListParams(),
  Object? cancel,
}) async {
  const path = '/workspaces';
  final json = await request(_get(path, params.toQuery(), cancel));
  return _page(json, Workspace.fromJson);
}

/// GET /workspaces/{id} — one row by primary key.
Future<Workspace> getWorkspace(
  Transport request,
  Object id, {
  WorkspaceGetParams params = const WorkspaceGetParams(),
  Object? cancel,
}) async {
  final path = _itemPath('/workspaces', id);
  final json = await request(_get(path, params.toQuery(), cancel));
  return _row(json, Workspace.fromJson);
}

/// A cursor walk over /workspaces, for a list that loads as it is scrolled.
///
/// [params] is the filter and ordering the whole walk runs under. Its [page]
/// and [cursor] are ignored: the pager owns where a page starts.
///
/// There is no cancel token, unlike the single-request functions. A walk is
/// many requests and a Dio CancelToken is one-shot, so cancelling to abandon
/// one page would poison every page after it.
CursorPager<Workspace> workspacePager(
  Transport request, {
  WorkspaceListParams params = const WorkspaceListParams(),
}) {
  return CursorPager<Workspace>(
    (cursor) => listWorkspaces(request, params: params.withCursor(cursor)),
  );
}

// ---------------------------------------------------------------- change feed

/// The tables this client serves, for a subscriber that receives a table name
/// and a row key and has to decide what to refetch.
enum TableName implements WireValue {
  /// The comments table, served at /comments.
  comments('comments'),

  /// The lists table, served at /lists.
  lists('lists'),

  /// The memberships table, served at /memberships.
  memberships('memberships'),

  /// The profiles table, served at /profiles.
  profiles('profiles'),

  /// The tasks table, served at /tasks.
  tasks('tasks'),

  /// The users table, served at /users.
  users('users'),

  /// The workspaces table, served at /workspaces.
  workspaces('workspaces');

  const TableName(this.wire);

  @override
  final String wire;

  /// The member [wire] names, or null for a table this client does not serve.
  static TableName? byWire(String wire) {
    for (final value in values) {
      if (value.wire == wire) return value;
    }
    return null;
  }
}

/// One change to a table this client serves.
///
/// [ChangeFeed] yields events whose table is a string, because the runtime is
/// shared by every generated client and knows no tables. This is the narrowing
/// that turns one into a value a switch can be exhaustive over.
class TableChange {
  /// Wraps a change to [table]. [TableChange.from] is what reads one off the
  /// feed.
  const TableChange(this.table, this.key, this.op);

  /// The table that changed.
  final TableName table;

  /// The row's primary key, or empty when the whole table is invalidated.
  final String key;

  /// What happened, or null for an operation this client has no member for.
  final ChangeOp? op;

  /// Whether the change addresses the collection rather than one row, which is
  /// what an empty [key] means.
  bool get isCollection => key.isEmpty;

  /// Narrows [event] to the tables this client serves, or null for one it does
  /// not.
  ///
  /// A client generated from one module of a schema receives the other modules'
  /// events too, and nothing in it displays them.
  static TableChange? from(ChangeEvent event) {
    final table = TableName.byWire(event.table);
    return table == null ? null : TableChange(table, event.key, event.op);
  }
}
