// Code generated by github.com/jryannel/sqlb. DO NOT EDIT.

package attachments

import (
	"time"

	"github.com/jryannel/sqlb"
)

type attachmentColumns struct {
	ID          sqlb.Col[string]
	Key         sqlb.TextCol[string]
	Filename    sqlb.TextCol[string]
	ContentType sqlb.TextCol[string]
	Size        sqlb.Col[int64]
	Status      sqlb.Col[AttachmentStatus]
	CreatedAt   sqlb.Col[time.Time]
	UpdatedAt   sqlb.Col[time.Time]
}

// AttachmentCols are the typed columns of attachments.
var AttachmentCols = attachmentColumns{
	ID:          sqlb.Typed[string]("id"),
	Key:         sqlb.TextColumn[string]("key"),
	Filename:    sqlb.TextColumn[string]("filename"),
	ContentType: sqlb.TextColumn[string]("content_type"),
	Size:        sqlb.Typed[int64]("size"),
	Status:      sqlb.Typed[AttachmentStatus]("status"),
	CreatedAt:   sqlb.Typed[time.Time]("created_at"),
	UpdatedAt:   sqlb.Typed[time.Time]("updated_at"),
}

// AttachmentUpdate is a typed update statement for attachments.
type AttachmentUpdate struct {
	stmt *sqlb.Update[Attachment]
}

// UpdateAttachment starts a typed update.
func UpdateAttachment() *AttachmentUpdate {
	return &AttachmentUpdate{stmt: sqlb.UpdateRows[Attachment]()}
}

// SetKey sets key.
func (u *AttachmentUpdate) SetKey(v string) *AttachmentUpdate {
	u.stmt.Set("key", v)
	return u
}

// SetFilename sets filename.
func (u *AttachmentUpdate) SetFilename(v string) *AttachmentUpdate {
	u.stmt.Set("filename", v)
	return u
}

// SetContentType sets content_type.
func (u *AttachmentUpdate) SetContentType(v string) *AttachmentUpdate {
	u.stmt.Set("content_type", v)
	return u
}

// SetSize sets size.
func (u *AttachmentUpdate) SetSize(v int64) *AttachmentUpdate {
	u.stmt.Set("size", v)
	return u
}

// SetStatus sets status.
func (u *AttachmentUpdate) SetStatus(v AttachmentStatus) *AttachmentUpdate {
	u.stmt.Set("status", v)
	return u
}

// SetCreatedAt sets created_at.
func (u *AttachmentUpdate) SetCreatedAt(v time.Time) *AttachmentUpdate {
	u.stmt.Set("created_at", v)
	return u
}

// SetUpdatedAt sets updated_at.
func (u *AttachmentUpdate) SetUpdatedAt(v time.Time) *AttachmentUpdate {
	u.stmt.Set("updated_at", v)
	return u
}

// Where narrows the affected rows.
func (u *AttachmentUpdate) Where(preds ...sqlb.Pred) *AttachmentUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *AttachmentUpdate) Stmt() *sqlb.Update[Attachment] { return u.stmt }
