// Code generated by github.com/mind-vm/sqlb. DO NOT EDIT.

package attachments

import (
	"github.com/danielgtaylor/huma/v2"
	"github.com/mind-vm/sqlb"
	"github.com/mind-vm/sqlb/rest"
)

// Register mounts every exposed resource on api.
//
// The handlers are rest.Resource, instantiated per model. Registration is
// generic rather than reflective because query hooks are keyed by type: a
// BeforeQuery hook registered on a model applies to its REST reads too, which
// is how tenant scoping stops being something each handler must remember.
func Register(api huma.API, db sqlb.Executor) error {
	if err := rest.Resource[Attachment, rest.None[Attachment], rest.None[Attachment]](api, db, rest.Options{
		Path:        "/attachments",
		Name:        "attachment",
		Tag:         "attachments",
		Ops:         rest.OpRead | rest.OpDelete | rest.OpList,
		Description: "A file in object storage, and the row that says it is there.",
	}); err != nil {
		return err
	}
	return nil
}
