// Code generated by github.com/mind-vm/sqlb. DO NOT EDIT.

package internalschema

import (
	"time"

	"github.com/mind-vm/sqlb"
)

type internalWidgetColumns struct {
	ID        sqlb.Col[string]
	Name      sqlb.TextCol[string]
	Status    sqlb.TextCol[string]
	CreatedAt sqlb.Col[time.Time]
	UpdatedAt sqlb.Col[time.Time]
}

// InternalWidgetCols are the typed columns of internal_widgets.
var InternalWidgetCols = internalWidgetColumns{
	ID:        sqlb.Typed[string]("id"),
	Name:      sqlb.TextColumn[string]("name"),
	Status:    sqlb.TextColumn[string]("status"),
	CreatedAt: sqlb.Typed[time.Time]("created_at"),
	UpdatedAt: sqlb.Typed[time.Time]("updated_at"),
}

// InternalWidgetUpdate is a typed update statement for internal_widgets.
type InternalWidgetUpdate struct {
	stmt *sqlb.Update[InternalWidget]
}

// UpdateInternalWidget starts a typed update.
func UpdateInternalWidget() *InternalWidgetUpdate {
	return &InternalWidgetUpdate{stmt: sqlb.UpdateRows[InternalWidget]()}
}

// SetName sets name.
func (u *InternalWidgetUpdate) SetName(v string) *InternalWidgetUpdate {
	u.stmt.Set("name", v)
	return u
}

// SetStatus sets status.
func (u *InternalWidgetUpdate) SetStatus(v string) *InternalWidgetUpdate {
	u.stmt.Set("status", v)
	return u
}

// SetCreatedAt sets created_at.
func (u *InternalWidgetUpdate) SetCreatedAt(v time.Time) *InternalWidgetUpdate {
	u.stmt.Set("created_at", v)
	return u
}

// SetUpdatedAt sets updated_at.
func (u *InternalWidgetUpdate) SetUpdatedAt(v time.Time) *InternalWidgetUpdate {
	u.stmt.Set("updated_at", v)
	return u
}

// Where narrows the affected rows.
func (u *InternalWidgetUpdate) Where(preds ...sqlb.Pred) *InternalWidgetUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *InternalWidgetUpdate) Stmt() *sqlb.Update[InternalWidget] { return u.stmt }
