// Package internalschema is a schema package that lives under internal/, and
// exists so that the command is tested against one.
//
// It is a fixture, but it is a real package in a real module rather than a
// scaffolded temp directory, for the reason cmd/sqlb/main_test.go gives about
// the blog example: a fixture module proves only that the fixture compiled.
//
// What it guards is narrow and was a real hole. `sqlb generate` writes its
// driver to a temporary directory and compiles it against the target module; a
// driver outside the module cannot import a package under internal/, so this
// layout — which is the usual one for a repository whose modules are not part
// of its public surface — was refused outright with
//
//	use of internal package … not allowed
//
// Nothing else in this repository is under internal/, so nothing else would
// have caught it.
//
// It emits the models and the typed column facade into this directory, and
// nothing else. That is enough to prove the driver linked and the emitters ran;
// the manifest and the REST bodies would say the same thing about the mechanism
// and cost more to keep current. (The facade names the row struct, so the two
// are one artefact in practice — skipping the models leaves columns_gen.go
// referring to a type nobody emitted.)
package internalschema

//go:generate go run github.com/mind-vm/sqlb/cmd/sqlb generate .

import (
	"github.com/mind-vm/sqlb/codegen"
	"github.com/mind-vm/sqlb/schema"
)

// Widget is deliberately dull. The subject of the test is the import path this
// package sits at, not the table.
//
// The varchar with a literal default is not incidental either: it is the shape
// that used to survive introspection with its cast attached and diff forever
// (see introspect.stripCast), so declaring one here keeps an example of it in
// a package that is regenerated by CI.
var Widget = schema.Table("internal_widgets",
	schema.UUID("id").PrimaryKey().Default(schema.GenUUIDv4()),
	schema.Varchar("name", 200).Searchable().Sortable(),
	schema.Varchar("status", 20).Default(schema.Value("draft")).Filterable(),
	schema.Timestamps(),
)

// SqlbProject is the convention function the command looks for.
func SqlbProject() codegen.Project {
	return codegen.Project{
		Options: codegen.Options{
			Dir:     "internal/internalschema",
			Package: "internalschema",

			// Models and the column facade only; "-" skips an artefact.
			ManifestFile: "-",
			RestFile:     "-",
		},
	}
}
