// Code generated by github.com/mind-vm/sqlb. DO NOT EDIT.

package tasks2

import (
	"time"

	"github.com/mind-vm/sqlb"
)

type listColumns struct {
	ID        sqlb.Col[string]
	Name      sqlb.TextCol[string]
	CreatedAt sqlb.Col[time.Time]
	UpdatedAt sqlb.Col[time.Time]
}

// ListCols are the typed columns of lists.
var ListCols = listColumns{
	ID:        sqlb.Typed[string]("id"),
	Name:      sqlb.TextColumn[string]("name"),
	CreatedAt: sqlb.Typed[time.Time]("created_at"),
	UpdatedAt: sqlb.Typed[time.Time]("updated_at"),
}

// ListUpdate is a typed update statement for lists.
type ListUpdate struct {
	stmt *sqlb.Update[List]
}

// UpdateList starts a typed update.
func UpdateList() *ListUpdate {
	return &ListUpdate{stmt: sqlb.UpdateRows[List]()}
}

// SetName sets name.
func (u *ListUpdate) SetName(v string) *ListUpdate {
	u.stmt.Set("name", v)
	return u
}

// SetCreatedAt sets created_at.
func (u *ListUpdate) SetCreatedAt(v time.Time) *ListUpdate {
	u.stmt.Set("created_at", v)
	return u
}

// SetUpdatedAt sets updated_at.
func (u *ListUpdate) SetUpdatedAt(v time.Time) *ListUpdate {
	u.stmt.Set("updated_at", v)
	return u
}

// Where narrows the affected rows.
func (u *ListUpdate) Where(preds ...sqlb.Pred) *ListUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *ListUpdate) Stmt() *sqlb.Update[List] { return u.stmt }

type taskColumns struct {
	ID          sqlb.Col[string]
	ListID      sqlb.Col[string]
	Title       sqlb.TextCol[string]
	Status      sqlb.Col[TaskStatus]
	DueAt       sqlb.Col[time.Time]
	CompletedAt sqlb.Col[time.Time]
	CreatedAt   sqlb.Col[time.Time]
	UpdatedAt   sqlb.Col[time.Time]
}

// TaskCols are the typed columns of tasks.
var TaskCols = taskColumns{
	ID:          sqlb.Typed[string]("id"),
	ListID:      sqlb.Typed[string]("list_id"),
	Title:       sqlb.TextColumn[string]("title"),
	Status:      sqlb.Typed[TaskStatus]("status"),
	DueAt:       sqlb.Typed[time.Time]("due_at"),
	CompletedAt: sqlb.Typed[time.Time]("completed_at"),
	CreatedAt:   sqlb.Typed[time.Time]("created_at"),
	UpdatedAt:   sqlb.Typed[time.Time]("updated_at"),
}

// TaskUpdate is a typed update statement for tasks.
type TaskUpdate struct {
	stmt *sqlb.Update[Task]
}

// UpdateTask starts a typed update.
func UpdateTask() *TaskUpdate {
	return &TaskUpdate{stmt: sqlb.UpdateRows[Task]()}
}

// SetListID sets list_id.
func (u *TaskUpdate) SetListID(v string) *TaskUpdate {
	u.stmt.Set("list_id", v)
	return u
}

// SetTitle sets title.
func (u *TaskUpdate) SetTitle(v string) *TaskUpdate {
	u.stmt.Set("title", v)
	return u
}

// SetStatus sets status.
func (u *TaskUpdate) SetStatus(v TaskStatus) *TaskUpdate {
	u.stmt.Set("status", v)
	return u
}

// SetDueAt sets due_at.
func (u *TaskUpdate) SetDueAt(v *time.Time) *TaskUpdate {
	u.stmt.Set("due_at", v)
	return u
}

// SetCompletedAt sets completed_at.
func (u *TaskUpdate) SetCompletedAt(v *time.Time) *TaskUpdate {
	u.stmt.Set("completed_at", v)
	return u
}

// SetCreatedAt sets created_at.
func (u *TaskUpdate) SetCreatedAt(v time.Time) *TaskUpdate {
	u.stmt.Set("created_at", v)
	return u
}

// SetUpdatedAt sets updated_at.
func (u *TaskUpdate) SetUpdatedAt(v time.Time) *TaskUpdate {
	u.stmt.Set("updated_at", v)
	return u
}

// Where narrows the affected rows.
func (u *TaskUpdate) Where(preds ...sqlb.Pred) *TaskUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *TaskUpdate) Stmt() *sqlb.Update[Task] { return u.stmt }
