// Code generated by github.com/mind-vm/sqlb. DO NOT EDIT.

package rooms

import (
	"time"

	"github.com/mind-vm/sqlb"
)

type bookingColumns struct {
	ID       sqlb.Col[string]
	RoomID   sqlb.Col[string]
	StartsAt sqlb.Col[time.Time]
	EndsAt   sqlb.Col[time.Time]
	Status   sqlb.Col[BookingStatus]
}

// BookingCols are the typed columns of bookings.
var BookingCols = bookingColumns{
	ID:       sqlb.Typed[string]("id"),
	RoomID:   sqlb.Typed[string]("room_id"),
	StartsAt: sqlb.Typed[time.Time]("starts_at"),
	EndsAt:   sqlb.Typed[time.Time]("ends_at"),
	Status:   sqlb.Typed[BookingStatus]("status"),
}

// BookingUpdate is a typed update statement for bookings.
type BookingUpdate struct {
	stmt *sqlb.Update[Booking]
}

// UpdateBooking starts a typed update.
func UpdateBooking() *BookingUpdate {
	return &BookingUpdate{stmt: sqlb.UpdateRows[Booking]()}
}

// SetRoomID sets room_id.
func (u *BookingUpdate) SetRoomID(v string) *BookingUpdate {
	u.stmt.Set("room_id", v)
	return u
}

// SetStartsAt sets starts_at.
func (u *BookingUpdate) SetStartsAt(v time.Time) *BookingUpdate {
	u.stmt.Set("starts_at", v)
	return u
}

// SetEndsAt sets ends_at.
func (u *BookingUpdate) SetEndsAt(v time.Time) *BookingUpdate {
	u.stmt.Set("ends_at", v)
	return u
}

// SetStatus sets status.
func (u *BookingUpdate) SetStatus(v BookingStatus) *BookingUpdate {
	u.stmt.Set("status", v)
	return u
}

// Where narrows the affected rows.
func (u *BookingUpdate) Where(preds ...sqlb.Pred) *BookingUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *BookingUpdate) Stmt() *sqlb.Update[Booking] { return u.stmt }

type roomColumns struct {
	ID   sqlb.Col[string]
	Name sqlb.TextCol[string]
}

// RoomCols are the typed columns of rooms.
var RoomCols = roomColumns{
	ID:   sqlb.Typed[string]("id"),
	Name: sqlb.TextColumn[string]("name"),
}

// RoomUpdate is a typed update statement for rooms.
type RoomUpdate struct {
	stmt *sqlb.Update[Room]
}

// UpdateRoom starts a typed update.
func UpdateRoom() *RoomUpdate {
	return &RoomUpdate{stmt: sqlb.UpdateRows[Room]()}
}

// SetName sets name.
func (u *RoomUpdate) SetName(v string) *RoomUpdate {
	u.stmt.Set("name", v)
	return u
}

// Where narrows the affected rows.
func (u *RoomUpdate) Where(preds ...sqlb.Pred) *RoomUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *RoomUpdate) Stmt() *sqlb.Update[Room] { return u.stmt }
