// Code generated by github.com/mind-vm/sqlb. DO NOT EDIT.

package store

import (
	"time"

	"github.com/mind-vm/sqlb"
)

type noteColumns struct {
	ID        sqlb.Col[string]
	SpaceID   sqlb.Col[string]
	Title     sqlb.TextCol[string]
	Body      sqlb.TextCol[string]
	Status    sqlb.Col[NoteStatus]
	Pinned    sqlb.Col[bool]
	CreatedAt sqlb.Col[time.Time]
	UpdatedAt sqlb.Col[time.Time]
}

// NoteCols are the typed columns of notes.
var NoteCols = noteColumns{
	ID:        sqlb.Typed[string]("id"),
	SpaceID:   sqlb.Typed[string]("space_id"),
	Title:     sqlb.TextColumn[string]("title"),
	Body:      sqlb.TextColumn[string]("body"),
	Status:    sqlb.Typed[NoteStatus]("status"),
	Pinned:    sqlb.Typed[bool]("pinned"),
	CreatedAt: sqlb.Typed[time.Time]("created_at"),
	UpdatedAt: sqlb.Typed[time.Time]("updated_at"),
}

// NoteUpdate is a typed update statement for notes.
type NoteUpdate struct {
	stmt *sqlb.Update[Note]
}

// UpdateNote starts a typed update.
func UpdateNote() *NoteUpdate {
	return &NoteUpdate{stmt: sqlb.UpdateRows[Note]()}
}

// SetSpaceID sets space_id.
func (u *NoteUpdate) SetSpaceID(v string) *NoteUpdate {
	u.stmt.Set("space_id", v)
	return u
}

// SetTitle sets title.
func (u *NoteUpdate) SetTitle(v string) *NoteUpdate {
	u.stmt.Set("title", v)
	return u
}

// SetBody sets body.
func (u *NoteUpdate) SetBody(v string) *NoteUpdate {
	u.stmt.Set("body", v)
	return u
}

// SetStatus sets status.
func (u *NoteUpdate) SetStatus(v NoteStatus) *NoteUpdate {
	u.stmt.Set("status", v)
	return u
}

// SetPinned sets pinned.
func (u *NoteUpdate) SetPinned(v bool) *NoteUpdate {
	u.stmt.Set("pinned", v)
	return u
}

// SetCreatedAt sets created_at.
func (u *NoteUpdate) SetCreatedAt(v time.Time) *NoteUpdate {
	u.stmt.Set("created_at", v)
	return u
}

// SetUpdatedAt sets updated_at.
func (u *NoteUpdate) SetUpdatedAt(v time.Time) *NoteUpdate {
	u.stmt.Set("updated_at", v)
	return u
}

// Where narrows the affected rows.
func (u *NoteUpdate) Where(preds ...sqlb.Pred) *NoteUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *NoteUpdate) Stmt() *sqlb.Update[Note] { return u.stmt }

type spaceColumns struct {
	ID        sqlb.Col[string]
	Name      sqlb.TextCol[string]
	Slug      sqlb.TextCol[string]
	CreatedAt sqlb.Col[time.Time]
	UpdatedAt sqlb.Col[time.Time]
}

// SpaceCols are the typed columns of spaces.
var SpaceCols = spaceColumns{
	ID:        sqlb.Typed[string]("id"),
	Name:      sqlb.TextColumn[string]("name"),
	Slug:      sqlb.TextColumn[string]("slug"),
	CreatedAt: sqlb.Typed[time.Time]("created_at"),
	UpdatedAt: sqlb.Typed[time.Time]("updated_at"),
}

// SpaceUpdate is a typed update statement for spaces.
type SpaceUpdate struct {
	stmt *sqlb.Update[Space]
}

// UpdateSpace starts a typed update.
func UpdateSpace() *SpaceUpdate {
	return &SpaceUpdate{stmt: sqlb.UpdateRows[Space]()}
}

// SetName sets name.
func (u *SpaceUpdate) SetName(v string) *SpaceUpdate {
	u.stmt.Set("name", v)
	return u
}

// SetSlug sets slug.
func (u *SpaceUpdate) SetSlug(v string) *SpaceUpdate {
	u.stmt.Set("slug", v)
	return u
}

// SetCreatedAt sets created_at.
func (u *SpaceUpdate) SetCreatedAt(v time.Time) *SpaceUpdate {
	u.stmt.Set("created_at", v)
	return u
}

// SetUpdatedAt sets updated_at.
func (u *SpaceUpdate) SetUpdatedAt(v time.Time) *SpaceUpdate {
	u.stmt.Set("updated_at", v)
	return u
}

// Where narrows the affected rows.
func (u *SpaceUpdate) Where(preds ...sqlb.Pred) *SpaceUpdate {
	u.stmt.Where(preds...)
	return u
}

// Stmt exposes the underlying statement for what the wrapper does not
// cover, such as Everything, SetExpr, Exec and One.
func (u *SpaceUpdate) Stmt() *sqlb.Update[Space] { return u.stmt }
