// Code generated by github.com/mind-vm/sqlb. DO NOT EDIT.

package store

import (
	"encoding/json"
	"errors"

	"github.com/danielgtaylor/huma/v2"
	"github.com/mind-vm/sqlb"
	"github.com/mind-vm/sqlb/rest"
)

// NoteCreate is the request body for creating a Note.
//
// Read-only columns are absent: the database or a BeforeCreate hook owns them.
// A column with a default is optional, so leaving it out means the database
// supplies the value rather than the zero value overwriting it.
type NoteCreate struct {
	Title  string      `json:"title"`
	Body   string      `json:"body"`
	Status *NoteStatus `json:"status,omitempty" enum:"draft,published,archived"`
	Pinned *bool       `json:"pinned,omitempty"`
}

// Row builds the row to insert. It satisfies rest.CreateBody.
func (c NoteCreate) Row() (*Note, error) {
	row := &Note{}
	row.Title = c.Title
	row.Body = c.Body
	if c.Status != nil {
		row.Status = *c.Status
	}
	if c.Pinned != nil {
		row.Pinned = *c.Pinned
	}
	return row, nil
}

// NotePatch is the request body for patching a Note.
//
// Every field is a pointer and every field is optional, so a request writes
// only the columns it names. Immutable columns are absent: they are settable
// once, at create.
type NotePatch struct {
	Title  *string     `json:"title,omitempty"`
	Body   *string     `json:"body,omitempty"`
	Status *NoteStatus `json:"status,omitempty" enum:"draft,published,archived"`
	Pinned *bool       `json:"pinned,omitempty"`

	// present records which properties the request body actually carried.
	present map[string]bool
}

// UnmarshalJSON decodes the body and remembers which properties were present.
//
// Without this a nil pointer would be ambiguous: `{}` and `{"title": null}` decode
// identically, but the first must change nothing and the second must write NULL.
func (u *NotePatch) UnmarshalJSON(data []byte) error {
	type plain NotePatch
	if err := json.Unmarshal(data, (*plain)(u)); err != nil {
		return err
	}
	var keys map[string]json.RawMessage
	if err := json.Unmarshal(data, &keys); err != nil {
		return err
	}
	u.present = make(map[string]bool, len(keys))
	for k := range keys {
		u.present[k] = true
	}
	return nil
}

// Changes reports the columns the request named. It satisfies rest.UpdateBody.
func (u NotePatch) Changes() (map[string]any, error) {
	out := make(map[string]any, len(u.present))
	if u.present["title"] {
		if u.Title == nil {
			return nil, errors.New("title is not nullable and cannot be set to null")
		}
		out["title"] = *u.Title
	}
	if u.present["body"] {
		if u.Body == nil {
			return nil, errors.New("body is not nullable and cannot be set to null")
		}
		out["body"] = *u.Body
	}
	if u.present["status"] {
		if u.Status == nil {
			return nil, errors.New("status is not nullable and cannot be set to null")
		}
		out["status"] = *u.Status
	}
	if u.present["pinned"] {
		if u.Pinned == nil {
			return nil, errors.New("pinned is not nullable and cannot be set to null")
		}
		out["pinned"] = *u.Pinned
	}
	return out, nil
}

// Register mounts every exposed resource on api.
//
// The handlers are rest.Resource, instantiated per model. Registration is
// generic rather than reflective because query hooks are keyed by type: a
// BeforeQuery hook registered on a model applies to its REST reads too, which
// is how tenant scoping stops being something each handler must remember.
func Register(api huma.API, db sqlb.Executor) error {
	if err := rest.Resource[Note, NoteCreate, NotePatch](api, db, rest.Options{
		Path:            "/notes",
		Name:            "note",
		Tag:             "notes",
		Ops:             rest.OpCreate | rest.OpRead | rest.OpUpdate | rest.OpDelete | rest.OpList,
		Description:     "A note, belonging to exactly one space.",
		DefaultPageSize: 25,
		MaxPageSize:     100,
		Expandable:      []string{"space"},
	}); err != nil {
		return err
	}
	if err := rest.Resource[Space, rest.None[Space], rest.None[Space]](api, db, rest.Options{
		Path:        "/spaces",
		Name:        "space",
		Tag:         "spaces",
		Ops:         rest.OpRead | rest.OpList,
		Description: "A tenant. Every note belongs to exactly one.",
		Expandable:  []string{"notes"},
	}); err != nil {
		return err
	}
	return nil
}
